import type { IndustryWorkflowBundle, SetupAction } from '../types'

// ============================================================
// AGRICULTURE — Sales Pipeline
// ============================================================
export const AGRICULTURE_SALES_BUNDLE: IndustryWorkflowBundle = {
  id: 'agriculture-sales',
  industry: 'Agriculture',
  process: 'sales',
  name: 'Agriculture Sales Pipeline',
  description: 'Farm produce and agribusiness sales pipeline from buyer enquiry through sampling, order placement, harvest coordination, and delivery for Nigerian agricultural businesses.',
  icon: '🌾',
  setup_time_minutes: 15,
  pipeline: {
    id: 'agriculture-sales-pipeline',
    name: 'Agri Sales',
    icon: '🌾',
    description: 'Buyer enquiry to delivery and payment',
    category: 'sales',
    stages: [
      {
        name: 'Buyer Enquiry',
        color: '#6366F1',
        position: 1,
        purpose: 'Capture buyer interest in agricultural products with quantity and quality requirements',
        owner_role: 'Sales / Account Manager',
        entry_criteria: [
          'Buyer has contacted via WhatsApp, phone, or market referral',
          'Product interest expressed',
        ],
        exit_criteria: [
          'Product type, grade, and quantity requirements confirmed',
          'Buyer delivery location and timeline established',
        ],
        checklist: [
          { text: 'Record buyer name, company, phone number, and location (state and city)', required: true },
          { text: 'Identify product(s) of interest: rice, maize, cassava, palm oil, cocoa, cashew, sesame, etc.', required: true },
          { text: 'Confirm required quantity in standard units (tonnes, bags, litres, crates)', required: true },
          { text: 'Ask about quality specifications: grade, moisture content, foreign matter tolerance', required: true },
          { text: 'Confirm delivery location and whether buyer arranges own transport or needs delivery', required: true },
          { text: 'Ask about purchase timeline: immediate, next harvest season, or ongoing supply contract', required: true },
          { text: 'Determine if buyer is end-user, processor, exporter, or trader', required: false },
        ],
        sla_hint: '4 business hours',
      },
      {
        name: 'Sample / Quote',
        color: '#8B5CF6',
        position: 2,
        purpose: 'Provide product samples and formal pricing to buyer',
        owner_role: 'Sales / Quality Control',
        entry_criteria: [
          'Buyer requirements clearly documented',
          'Product available or harvest timeline known',
        ],
        exit_criteria: [
          'Sample sent or inspection arranged',
          'Price quote shared with buyer',
        ],
        checklist: [
          { text: 'Prepare product sample matching buyer specifications (1-5kg sample bag)', required: true },
          { text: 'Include quality certificate or lab test results if available (moisture, aflatoxin levels)', required: false },
          { text: 'Send sample via courier or arrange buyer visit to warehouse/farm for inspection', required: true },
          { text: 'Prepare price quote: unit price per tonne/bag in Naira, total for requested quantity', required: true },
          { text: 'Include delivery cost estimate based on buyer location (truck hire rates)', required: true },
          { text: 'Specify payment terms: 100% advance, 50% deposit + balance before loading, or LC for exports', required: true },
          { text: 'Set quote validity period (typically 7 days due to commodity price fluctuations)', required: true },
        ],
        sla_hint: '3 business days',
      },
      {
        name: 'Order Confirmed',
        color: '#EC4899',
        position: 3,
        purpose: 'Buyer has accepted quote and placed a firm order',
        owner_role: 'Sales Manager',
        entry_criteria: [
          'Buyer has approved sample quality',
          'Price and terms agreed',
        ],
        exit_criteria: [
          'Purchase order or written confirmation received',
          'Deposit payment received',
        ],
        checklist: [
          { text: 'Obtain written purchase order or WhatsApp confirmation with agreed terms', required: true },
          { text: 'Collect deposit payment (minimum 50%) and verify bank transfer receipt', required: true },
          { text: 'Issue deposit receipt and order confirmation to buyer', required: true },
          { text: 'Confirm delivery date based on stock availability or harvest schedule', required: true },
          { text: 'Reserve stock in warehouse or confirm with farm/aggregation centre', required: true },
          { text: 'Arrange quality inspection of bulk stock if buyer requires pre-shipment inspection', required: false },
        ],
        sla_hint: '2 business days',
      },
      {
        name: 'Harvest / Processing',
        color: '#F59E0B',
        position: 4,
        purpose: 'Product being harvested, processed, or prepared for shipment',
        owner_role: 'Operations / Farm Manager',
        entry_criteria: [
          'Order confirmed with deposit',
          'Product sourcing or harvest in progress',
        ],
        exit_criteria: [
          'Product harvested, processed, and ready for loading',
          'Quality meets buyer specifications',
        ],
        checklist: [
          { text: 'Coordinate harvest or aggregation from farms to meet order quantity', required: true },
          { text: 'Process product as required: cleaning, sorting, grading, drying, milling, packaging', required: true },
          { text: 'Conduct quality check: moisture content, foreign matter, size grading', required: true },
          { text: 'Package in buyer-specified packaging (50kg bags, 25kg bags, bulk, or custom)', required: true },
          { text: 'Weigh and count all bags/units and record total quantity', required: true },
          { text: 'Take photos of packed product for buyer confirmation before dispatch', required: true },
          { text: 'Arrange fumigation certificate if required for export or long-distance transport', required: false },
        ],
        sla_hint: '3-14 days depending on product',
      },
      {
        name: 'Delivery',
        color: '#10B981',
        position: 5,
        purpose: 'Product loaded and transported to buyer location',
        owner_role: 'Logistics Coordinator',
        entry_criteria: [
          'Product packed and ready for loading',
          'Balance payment received or COD arranged',
          'Transport arranged',
        ],
        exit_criteria: [
          'Product delivered to buyer location',
          'Buyer has inspected and accepted delivery',
        ],
        checklist: [
          { text: 'Collect balance payment before loading (or confirm COD arrangement with manager approval)', required: true },
          { text: 'Arrange truck and confirm driver details: name, phone, plate number', required: true },
          { text: 'Supervise loading and record number of bags/units loaded with photos', required: true },
          { text: 'Issue waybill with: product, quantity, origin, destination, driver details', required: true },
          { text: 'Share driver contact and estimated arrival time with buyer via WhatsApp', required: true },
          { text: 'Track truck progress and update buyer on delivery status', required: true },
          { text: 'Confirm delivery with buyer: quantity received, quality acceptable, any shortages', required: true },
        ],
        sla_hint: '1-5 days depending on distance',
      },
      {
        name: 'Payment Complete',
        color: '#059669',
        position: 6,
        purpose: 'Full payment received, transaction closed, relationship maintained',
        owner_role: 'Finance / Sales Manager',
        entry_criteria: [
          'Product delivered and accepted by buyer',
          'All payments received or final settlement agreed',
        ],
        exit_criteria: [
          'Full payment verified',
          'Final receipt issued',
          'Deal closed in CRM',
        ],
        checklist: [
          { text: 'Verify total payment received matches invoice amount (deposit + balance)', required: true },
          { text: 'Issue final receipt and invoice to buyer', required: true },
          { text: 'Resolve any claims: shortages, quality disputes, damaged goods during transit', required: true },
          { text: 'Send thank-you message and ask about next order requirements', required: true },
          { text: 'Tag buyer with product interest and volume tier for future marketing', required: true },
          { text: 'Update deal as Won in CRM with total revenue and product details', required: true },
          { text: 'Schedule follow-up for next harvest season or regular supply cycle', required: false },
        ],
        sla_hint: '3 business days after delivery',
      },
    ],
  },
  suggested_flows: ['welcome_menu', 'product_enquiry', 'payment_confirmation_flow', 'delivery_tracking_flow', 'feedback_collector'],
  suggested_automations: [
    { slug: 'welcome_message', priority: 'essential', description: 'Auto-greet buyers with available products and current season offerings' },
    { slug: 'payment_reminder', priority: 'essential', description: 'Remind buyers of outstanding balance before loading' },
    { slug: 'delivery_notification', priority: 'essential', description: 'Notify buyer when truck departs with delivery details' },
    { slug: 'follow_up_reminder', priority: 'recommended', description: 'Follow up with buyers before next harvest season' },
    { slug: 'vip_alert', priority: 'recommended', description: 'Alert manager when high-volume buyer places enquiry' },
    { slug: 'dormant_reactivation', priority: 'optional', description: 'Re-engage buyers who have not ordered in 90+ days' },
  ],
  suggested_segments: ['high_value_customers', 'repeat_buyers', 'active_last_30', 'dormant_60_plus', 'pending_payments', 'seasonal_buyers'],
  setup_actions: [
    { id: 'agri-sales-crops', title: 'Add crop types and grades as products', description: 'Set up your produce catalogue with crop types, grades, and current prices per tonne/bag', priority: 'essential', category: 'products', target_url: '/products', estimated_minutes: 15, icon: '🌾' },
    { id: 'agri-sales-welcome', title: 'Customise buyer welcome message', description: 'Edit the auto-greeting to include available products and current season offerings', priority: 'essential', category: 'automations', target_url: '/automations/new', target_params: { template: 'welcome_message' }, estimated_minutes: 5, icon: '👋' },
    { id: 'agri-sales-payment', title: 'Configure payment reminder for buyers', description: 'Set up reminders for outstanding balance before dispatch', priority: 'essential', category: 'automations', target_url: '/automations/new', target_params: { template: 'payment_reminder' }, estimated_minutes: 3, icon: '💰' },
    { id: 'agri-sales-locations', title: 'Add farm and warehouse locations', description: 'Set up your farm locations and storage facilities for logistics planning', priority: 'recommended', category: 'settings', target_url: '/inventory', estimated_minutes: 5, icon: '📍' },
    { id: 'agri-sales-seasonal', title: 'Set up seasonal buyer follow-ups', description: 'Configure follow-ups with buyers before next harvest season', priority: 'recommended', category: 'automations', target_url: '/automations/new', target_params: { template: 'follow_up_reminder' }, estimated_minutes: 5, icon: '📅' },
    { id: 'agri-sales-review', title: 'Set up buyer feedback request', description: 'Request feedback after successful delivery', priority: 'optional', category: 'automations', target_url: '/automations/new', target_params: { template: 'review_request' }, estimated_minutes: 3, icon: '⭐' },
  ],
  customization_hints: [
    'Add your specific crop types and grades as product tags',
    'Configure seasonal availability calendar for harvest-dependent products',
    'Set up price alert automations when commodity prices change significantly',
    'Add your warehouse and farm locations for logistics planning',
    'Configure quality specification templates for your main products',
  ],
}

// ============================================================
// AGRICULTURE — Procurement Pipeline
// ============================================================
export const AGRICULTURE_PROCUREMENT_BUNDLE: IndustryWorkflowBundle = {
  id: 'agriculture-procurement',
  industry: 'Agriculture',
  process: 'operations',
  name: 'Agriculture Procurement Pipeline',
  description: 'Input procurement pipeline for sourcing seeds, fertiliser, chemicals, equipment, and raw materials from suppliers for Nigerian agribusinesses.',
  icon: '🚜',
  setup_time_minutes: 12,
  pipeline: {
    id: 'agriculture-procurement-pipeline',
    name: 'Agri Procurement',
    icon: '🚜',
    description: 'Input need to supplier delivery and quality check',
    category: 'operations',
    stages: [
      {
        name: 'Input Need Identified',
        color: '#6366F1',
        position: 1,
        purpose: 'Farm or processing operation identifies need for inputs or materials',
        owner_role: 'Farm Manager / Procurement Officer',
        entry_criteria: [
          'Input requirement identified by farm or operations team',
          'Budget approved for procurement',
        ],
        exit_criteria: [
          'Specific input requirements documented',
          'Budget allocation confirmed',
        ],
        checklist: [
          { text: 'Document specific input needed: product name, specification, and quantity', required: true },
          { text: 'Specify quality requirements: brand preference, certification (NAFDAC, SON), expiry date minimum', required: true },
          { text: 'Confirm budget allocation in Naira for this procurement', required: true },
          { text: 'Set required delivery date based on planting season or production schedule', required: true },
          { text: 'Check if existing supplier relationships can fulfil this need', required: true },
        ],
        sla_hint: '1 business day',
      },
      {
        name: 'Supplier Sourcing',
        color: '#8B5CF6',
        position: 2,
        purpose: 'Identify and contact potential suppliers for required inputs',
        owner_role: 'Procurement Officer',
        entry_criteria: [
          'Input requirements documented',
          'Budget confirmed',
        ],
        exit_criteria: [
          'Minimum 2-3 supplier quotes obtained',
          'Supplier credentials verified',
        ],
        checklist: [
          { text: 'Contact existing approved suppliers for availability and pricing', required: true },
          { text: 'If new suppliers needed, source from agro-dealer networks, trade associations, or referrals', required: true },
          { text: 'Request quotes from minimum 3 suppliers for comparison', required: true },
          { text: 'Verify supplier credentials: CAC registration, NAFDAC certification for chemicals/fertiliser', required: true },
          { text: 'Check supplier track record: ask for references from other buyers', required: false },
          { text: 'Confirm supplier can deliver to your location within required timeline', required: true },
        ],
        sla_hint: '3 business days',
      },
      {
        name: 'Quote Comparison',
        color: '#EC4899',
        position: 3,
        purpose: 'Compare supplier quotes and select best option',
        owner_role: 'Procurement Officer / Manager',
        entry_criteria: [
          'Multiple supplier quotes received',
          'All quotes include delivery terms',
        ],
        exit_criteria: [
          'Preferred supplier selected',
          'Terms negotiated and agreed',
        ],
        checklist: [
          { text: 'Create comparison table: price per unit, total cost, delivery time, payment terms, quality guarantee', required: true },
          { text: 'Factor in delivery cost if not included in supplier price', required: true },
          { text: 'Negotiate price for bulk orders or long-term supply agreements', required: false },
          { text: 'Confirm payment terms: advance payment, part payment, or credit terms', required: true },
          { text: 'Get manager approval for selected supplier and total spend', required: true },
          { text: 'Communicate selection to chosen supplier and confirm order', required: true },
        ],
        sla_hint: '2 business days',
      },
      {
        name: 'Purchase Order',
        color: '#F59E0B',
        position: 4,
        purpose: 'Formal purchase order placed and payment initiated',
        owner_role: 'Procurement Officer / Finance',
        entry_criteria: [
          'Supplier selected and terms agreed',
          'Manager approval obtained',
        ],
        exit_criteria: [
          'Purchase order issued to supplier',
          'Payment made per agreed terms',
        ],
        checklist: [
          { text: 'Issue formal purchase order with: items, quantities, unit prices, total, delivery date, and terms', required: true },
          { text: 'Process payment via bank transfer per agreed terms (advance or deposit)', required: true },
          { text: 'Send payment confirmation to supplier with transfer receipt', required: true },
          { text: 'Confirm expected delivery date and logistics arrangement', required: true },
          { text: 'Set delivery tracking reminder for 2 days before expected date', required: true },
        ],
        sla_hint: '1 business day',
      },
      {
        name: 'Delivery',
        color: '#10B981',
        position: 5,
        purpose: 'Supplier delivers inputs to farm or warehouse',
        owner_role: 'Warehouse / Farm Manager',
        entry_criteria: [
          'Purchase order confirmed by supplier',
          'Payment made per terms',
        ],
        exit_criteria: [
          'Goods received at delivery location',
          'Quantity verified against purchase order',
        ],
        checklist: [
          { text: 'Confirm delivery date and time with supplier 24 hours before', required: true },
          { text: 'Prepare receiving area: warehouse space, weighing equipment, inspection tools', required: true },
          { text: 'Count and weigh all delivered items against purchase order', required: true },
          { text: 'Check packaging integrity: no tears, water damage, or tampering', required: true },
          { text: 'Verify product labels: brand, batch number, manufacturing date, expiry date', required: true },
          { text: 'Sign delivery note and retain copy; note any discrepancies', required: true },
        ],
        sla_hint: 'Per agreed delivery date',
      },
      {
        name: 'Quality Check',
        color: '#059669',
        position: 6,
        purpose: 'Verify delivered inputs meet quality specifications before acceptance',
        owner_role: 'Quality Control / Farm Manager',
        entry_criteria: [
          'Goods received and counted',
          'Delivery note signed with any discrepancies noted',
        ],
        exit_criteria: [
          'Quality approved or rejection communicated to supplier',
          'Goods stored properly',
          'Procurement closed in CRM',
        ],
        checklist: [
          { text: 'Inspect sample from delivered batch for quality: colour, smell, texture, concentration', required: true },
          { text: 'For seeds: check germination rate with sample test if time permits', required: false },
          { text: 'For chemicals/fertiliser: verify NAFDAC number matches registered product', required: true },
          { text: 'If quality issues found, document with photos and contact supplier immediately', required: true },
          { text: 'Store accepted goods properly: cool dry place, away from direct sunlight, pest-free', required: true },
          { text: 'Update inventory records with new stock quantities and batch details', required: true },
          { text: 'Close procurement in CRM and rate supplier performance for future reference', required: true },
        ],
        sla_hint: '24 hours after delivery',
      },
    ],
  },
  suggested_flows: ['welcome_menu', 'payment_confirmation_flow', 'delivery_tracking_flow', 'complaint_resolution_flow'],
  suggested_automations: [
    { slug: 'payment_reminder', priority: 'essential', description: 'Remind finance team of pending supplier payments' },
    { slug: 'delivery_notification', priority: 'essential', description: 'Alert warehouse when supplier delivery is expected' },
    { slug: 'follow_up_reminder', priority: 'recommended', description: 'Follow up with supplier if delivery is overdue' },
    { slug: 'overdue_payment_escalation', priority: 'recommended', description: 'Escalate quality issues not resolved within 48 hours' },
    { slug: 'booking_confirmation', priority: 'optional', description: 'Confirm purchase order receipt with supplier' },
  ],
  suggested_segments: ['pending_payments', 'active_last_30', 'repeat_buyers', 'high_value_customers', 'seasonal_buyers'],
  setup_actions: [
    { id: 'agri-proc-suppliers', title: 'Add approved supplier contacts', description: 'Create contact entries for your approved suppliers with product specialities and locations', priority: 'essential', category: 'contacts', target_url: '/contacts', estimated_minutes: 10, icon: '👥' },
    { id: 'agri-proc-welcome', title: 'Customise supplier communication', description: 'Set up auto-greeting for new supplier enquiries', priority: 'essential', category: 'automations', target_url: '/automations/new', target_params: { template: 'welcome_message' }, estimated_minutes: 5, icon: '👋' },
    { id: 'agri-proc-payment', title: 'Configure supplier payment reminders', description: 'Set up reminders for pending supplier payments to finance team', priority: 'essential', category: 'automations', target_url: '/automations/new', target_params: { template: 'payment_reminder' }, estimated_minutes: 3, icon: '💰' },
    { id: 'agri-proc-quality', title: 'Set up quality specification templates', description: 'Create quality spec templates for your most-purchased inputs', priority: 'recommended', category: 'settings', target_url: '/settings', estimated_minutes: 10, icon: '✅' },
    { id: 'agri-proc-delivery', title: 'Configure delivery tracking alerts', description: 'Set up alerts when supplier delivery is expected at warehouse', priority: 'recommended', category: 'automations', target_url: '/automations/new', target_params: { template: 'delivery_notification' }, estimated_minutes: 3, icon: '🚛' },
    { id: 'agri-proc-seasonal', title: 'Plan seasonal procurement calendar', description: 'Align procurement schedules with planting seasons', priority: 'optional', category: 'settings', target_url: '/settings', estimated_minutes: 10, icon: '📅' },
  ],
  customization_hints: [
    'Add your approved supplier list with contact details and product specialities',
    'Configure seasonal procurement calendar aligned with planting seasons',
    'Set up quality specification templates for your most-purchased inputs',
    'Add budget approval thresholds for different procurement values',
    'Track supplier performance scores for better future sourcing decisions',
  ],
}
