import type { IndustryWorkflowBundle, SetupAction } from '../types'

// ============================================================
// EDUCATION — Admissions Pipeline
// ============================================================
export const EDUCATION_ADMISSIONS_BUNDLE: IndustryWorkflowBundle = {
  id: 'education-admissions',
  industry: 'Education',
  process: 'sales',
  name: 'Education Admissions Pipeline',
  description: 'Student admissions pipeline from enquiry through application, assessment, offer, acceptance, and enrolment for Nigerian schools, colleges, and training centres.',
  icon: '🎓',
  setup_time_minutes: 15,
  pipeline: {
    id: 'education-admissions-pipeline',
    name: 'Student Admissions',
    icon: '🎓',
    description: 'Enquiry to enrolment',
    category: 'sales',
    stages: [
      {
        name: 'Enquiry',
        color: '#6366F1',
        position: 1,
        purpose: 'Capture prospective student or parent interest and programme requirements',
        owner_role: 'Admissions Officer',
        entry_criteria: [
          'Prospective student or parent has contacted via WhatsApp, phone, website, or walk-in',
          'Interest in a programme or course expressed',
        ],
        exit_criteria: [
          'Contact details captured',
          'Programme of interest identified',
          'Application process explained',
        ],
        checklist: [
          { text: 'Record student name, parent/guardian name (if minor), phone number, and email', required: true },
          { text: 'Identify programme or class of interest: nursery, primary, secondary, diploma, professional course', required: true },
          { text: 'Ask about student current school, class/level, and expected start term', required: true },
          { text: 'Share programme details: curriculum, duration, schedule, and tuition fees in Naira', required: true },
          { text: 'Explain admission requirements: age, previous results, entrance exam, documents needed', required: true },
          { text: 'Offer campus tour or virtual tour if available', required: false },
          { text: 'Share application form link or explain how to apply', required: true },
        ],
        sla_hint: '2 business hours',
      },
      {
        name: 'Application',
        color: '#8B5CF6',
        position: 2,
        purpose: 'Student submits formal application with required documents',
        owner_role: 'Admissions Officer',
        entry_criteria: [
          'Student or parent has decided to apply',
          'Application form shared',
        ],
        exit_criteria: [
          'Completed application form received',
          'Required documents submitted',
          'Application fee paid',
        ],
        checklist: [
          { text: 'Receive completed application form with all fields filled', required: true },
          { text: 'Collect required documents: birth certificate, previous school report card, passport photos', required: true },
          { text: 'For secondary/tertiary: collect WAEC/NECO results, JAMB score, or equivalent', required: false },
          { text: 'Collect application fee via bank transfer, POS, or cash and issue receipt', required: true },
          { text: 'Verify all documents are legible and complete', required: true },
          { text: 'Send application acknowledgement via WhatsApp with application number', required: true },
          { text: 'Schedule entrance assessment or interview date', required: true },
        ],
        sla_hint: '24 hours to process',
      },
      {
        name: 'Assessment',
        color: '#EC4899',
        position: 3,
        purpose: 'Student undergoes entrance examination, interview, or placement test',
        owner_role: 'Academic Coordinator / Examiner',
        entry_criteria: [
          'Application complete with all documents',
          'Assessment date scheduled',
        ],
        exit_criteria: [
          'Assessment completed',
          'Results evaluated',
          'Admission decision made',
        ],
        checklist: [
          { text: 'Send assessment reminder via WhatsApp 48 hours before with date, time, and venue', required: true },
          { text: 'Prepare assessment materials: exam papers, interview questions, practical test equipment', required: true },
          { text: 'Verify student identity on assessment day with application form and photo', required: true },
          { text: 'Conduct entrance exam, interview, or placement test as applicable', required: true },
          { text: 'Grade assessment and record scores in student file', required: true },
          { text: 'Review application holistically: assessment score, previous results, interview impression', required: true },
          { text: 'Make admission decision: admit, waitlist, or decline', required: true },
        ],
        sla_hint: '5 business days for results',
      },
      {
        name: 'Offer',
        color: '#F59E0B',
        position: 4,
        purpose: 'Admission offer communicated to successful applicant',
        owner_role: 'Admissions Officer',
        entry_criteria: [
          'Assessment completed and admission decision is positive',
          'Offer letter prepared',
        ],
        exit_criteria: [
          'Offer letter sent to student/parent',
          'Fee structure and payment deadline communicated',
        ],
        checklist: [
          { text: 'Prepare admission offer letter with: programme, class/level, start date, conditions', required: true },
          { text: 'Include detailed fee structure: tuition, development levy, uniform, books, transport, feeding', required: true },
          { text: 'Specify acceptance deadline (typically 2-4 weeks)', required: true },
          { text: 'Include list of items to bring on resumption day', required: true },
          { text: 'Send offer letter via WhatsApp and email to parent/guardian', required: true },
          { text: 'For waitlisted students, send waitlist notification with expected timeline', required: false },
          { text: 'For declined students, send polite decline with feedback if appropriate', required: false },
        ],
        sla_hint: '3 business days after assessment',
      },
      {
        name: 'Acceptance',
        color: '#3B82F6',
        position: 5,
        purpose: 'Student accepts offer and makes initial payment to secure place',
        owner_role: 'Admissions / Finance',
        entry_criteria: [
          'Offer letter sent to student/parent',
          'Student/parent has indicated acceptance',
        ],
        exit_criteria: [
          'Acceptance form signed',
          'Initial payment received',
          'Place secured in class',
        ],
        checklist: [
          { text: 'Receive signed acceptance form from parent/guardian', required: true },
          { text: 'Collect initial payment: acceptance fee or first term fees via bank transfer', required: true },
          { text: 'Verify payment and issue official receipt', required: true },
          { text: 'Assign student to specific class, section, or cohort', required: true },
          { text: 'Add student to class WhatsApp group or parent communication channel', required: false },
          { text: 'Send welcome pack: school calendar, uniform list, supply list, rules and regulations', required: true },
          { text: 'Set reminder for resumption date communication', required: true },
        ],
        sla_hint: 'Within acceptance deadline',
      },
      {
        name: 'Enrolled',
        color: '#059669',
        position: 6,
        purpose: 'Student has resumed and is actively enrolled in the programme',
        owner_role: 'Admissions / Class Teacher',
        entry_criteria: [
          'Fees paid (full or agreed instalment)',
          'Resumption date arrived',
        ],
        exit_criteria: [
          'Student has physically resumed',
          'All enrolment paperwork complete',
          'Student integrated into class',
          'Deal closed in CRM',
        ],
        checklist: [
          { text: 'Verify student attendance on resumption day', required: true },
          { text: 'Complete student registration in school management system', required: true },
          { text: 'Issue student ID card', required: false },
          { text: 'Confirm uniform and learning materials are in order', required: true },
          { text: 'Introduce student to class teacher and classmates', required: true },
          { text: 'Send welcome message to parent confirming successful enrolment', required: true },
          { text: 'Set up fee payment reminders for subsequent terms if on instalment plan', required: true },
          { text: 'Close admission deal in CRM with total fees and programme details', required: true },
        ],
        sla_hint: 'First week of term',
      },
    ],
  },
  suggested_flows: ['welcome_menu', 'admission_enquiry_flow', 'payment_confirmation_flow', 'feedback_collector', 'appointment_booking_flow'],
  suggested_automations: [
    { slug: 'welcome_message', priority: 'essential', description: 'Auto-greet enquiries with programme information and admission requirements' },
    { slug: 'booking_confirmation', priority: 'essential', description: 'Send application acknowledgement with application number' },
    { slug: 'appointment_reminder_24h', priority: 'essential', description: 'Remind students 24 hours before entrance assessment' },
    { slug: 'payment_reminder', priority: 'recommended', description: 'Remind parents of acceptance deadline and fee payment' },
    { slug: 'follow_up_reminder', priority: 'recommended', description: 'Follow up with enquiries who have not applied within 7 days' },
    { slug: 'dormant_reactivation', priority: 'optional', description: 'Re-engage past enquiries before new admission cycle' },
  ],
  suggested_segments: ['new_contacts_7d', 'active_last_30', 'dormant_60_plus', 'pending_payments', 'seasonal_buyers', 'referral_sources'],
  setup_actions: [
    { id: 'edu-admit-programmes', title: 'Add programmes and classes to products', description: 'Set up your programmes, classes, and fee structures for quick sharing with prospective parents', priority: 'essential', category: 'products', target_url: '/products', estimated_minutes: 15, icon: '📚' },
    { id: 'edu-admit-welcome', title: 'Customise admissions enquiry greeting', description: 'Edit the auto-greeting to include programme information and admission requirements', priority: 'essential', category: 'automations', target_url: '/automations/new', target_params: { template: 'welcome_message' }, estimated_minutes: 5, icon: '👋' },
    { id: 'edu-admit-assessment', title: 'Set up assessment reminder', description: 'Configure 24-hour reminder before entrance assessment with venue details', priority: 'essential', category: 'automations', target_url: '/automations/new', target_params: { template: 'appointment_reminder_24h' }, estimated_minutes: 3, icon: '📅' },
    { id: 'edu-admit-followup', title: 'Configure application follow-up', description: 'Set up follow-up for applications not completed within 48 hours', priority: 'recommended', category: 'automations', target_url: '/automations/new', target_params: { template: 'follow_up_reminder' }, estimated_minutes: 3, icon: '📞' },
    { id: 'edu-admit-acceptance', title: 'Set up acceptance deadline reminder', description: 'Remind parents of acceptance deadline and fee payment', priority: 'recommended', category: 'automations', target_url: '/automations/new', target_params: { template: 'payment_reminder' }, estimated_minutes: 3, icon: '⏰' },
    { id: 'edu-admit-segments', title: 'Review admission cycle segments', description: 'Check auto-created segments for new enquiries and dormant prospects', priority: 'optional', category: 'segments', target_url: '/segments', target_params: { template: 'new_contacts_7d' }, estimated_minutes: 5, icon: '📊' },
  ],
  customization_hints: [
    'Add your specific programmes, classes, and fee structures for quick sharing',
    'Configure admission cycle dates: application open, assessment dates, resumption dates',
    'Set up automated reminders aligned with your school calendar',
    'Add entrance exam scheduling with available dates and venues',
    'Configure parent communication preferences: WhatsApp group, individual messages, or both',
  ],
}

// ============================================================
// EDUCATION — Fee Collection Pipeline
// ============================================================
export const EDUCATION_FEES_BUNDLE: IndustryWorkflowBundle = {
  id: 'education-fees',
  industry: 'Education',
  process: 'operations',
  name: 'Education Fee Collection Pipeline',
  description: 'School fee collection pipeline from invoice generation through payment reminders, collection, receipting, and reconciliation for Nigerian educational institutions.',
  icon: '💰',
  setup_time_minutes: 10,
  pipeline: {
    id: 'education-fees-pipeline',
    name: 'Fee Collection',
    icon: '💰',
    description: 'Invoice to reconciliation',
    category: 'operations',
    stages: [
      {
        name: 'Invoice Generated',
        color: '#6366F1',
        position: 1,
        purpose: 'Term or session fee invoice created and sent to parent/guardian',
        owner_role: 'Bursar / Finance Officer',
        entry_criteria: [
          'New term or session is approaching',
          'Fee structure approved for the term',
        ],
        exit_criteria: [
          'Invoice generated for each student',
          'Invoice sent to parent/guardian',
        ],
        checklist: [
          { text: 'Generate fee invoice per student with breakdown: tuition, development levy, books, uniform, transport, feeding', required: true },
          { text: 'Apply any discounts: sibling discount, staff child discount, scholarship, early payment discount', required: true },
          { text: 'Include payment deadline and late payment penalty information', required: true },
          { text: 'Include school bank account details for transfer payment', required: true },
          { text: 'Send invoice to parent via WhatsApp with student name and class clearly stated', required: true },
          { text: 'For instalment plans, include instalment schedule with due dates', required: false },
        ],
        sla_hint: '2 weeks before term starts',
      },
      {
        name: 'Payment Reminder',
        color: '#F59E0B',
        position: 2,
        purpose: 'Follow up with parents who have not yet paid',
        owner_role: 'Bursar / Admin',
        entry_criteria: [
          'Invoice sent but payment not yet received',
          'Payment deadline approaching or passed',
        ],
        exit_criteria: [
          'Parent has acknowledged and committed to payment date',
          'Or payment has been received',
        ],
        checklist: [
          { text: 'Send first reminder via WhatsApp 7 days before payment deadline', required: true },
          { text: 'Send second reminder 3 days before deadline with bank account details', required: true },
          { text: 'Send final reminder on deadline day emphasising late payment consequences', required: true },
          { text: 'For overdue payments, send polite but firm reminder with outstanding amount', required: true },
          { text: 'If parent requests instalment arrangement, document agreed schedule and get approval', required: false },
          { text: 'Escalate to school management if payment is 2+ weeks overdue with no response', required: true },
        ],
        sla_hint: 'Automated reminders at 7, 3, and 0 days',
      },
      {
        name: 'Payment Received',
        color: '#10B981',
        position: 3,
        purpose: 'Payment received and verified against invoice',
        owner_role: 'Bursar / Finance Officer',
        entry_criteria: [
          'Parent has made payment via bank transfer, POS, cash, or online',
        ],
        exit_criteria: [
          'Payment verified against invoice amount',
          'Payment recorded in finance system',
        ],
        checklist: [
          { text: 'Verify payment amount matches invoice (full payment or agreed instalment)', required: true },
          { text: 'Match payment to correct student using reference or sender name', required: true },
          { text: 'Record payment in school finance system: amount, date, method, reference number', required: true },
          { text: 'If partial payment, update outstanding balance and next instalment due date', required: true },
          { text: 'If overpayment, note credit balance for next term', required: false },
          { text: 'Send payment acknowledgement to parent via WhatsApp within 24 hours', required: true },
        ],
        sla_hint: '24 hours to process',
      },
      {
        name: 'Receipt Issued',
        color: '#3B82F6',
        position: 4,
        purpose: 'Official receipt issued to parent as proof of payment',
        owner_role: 'Bursar',
        entry_criteria: [
          'Payment verified and recorded',
        ],
        exit_criteria: [
          'Official receipt generated and sent to parent',
          'Student fee status updated',
        ],
        checklist: [
          { text: 'Generate official school receipt with: student name, class, amount paid, date, receipt number', required: true },
          { text: 'Include breakdown of what the payment covers', required: true },
          { text: 'Send receipt to parent via WhatsApp (photo or PDF)', required: true },
          { text: 'Update student fee status: fully paid, partial, or outstanding balance', required: true },
          { text: 'If fully paid, mark student as cleared for the term', required: true },
          { text: 'File receipt copy in school records', required: true },
        ],
        sla_hint: '48 hours after payment verification',
      },
      {
        name: 'Reconciled',
        color: '#059669',
        position: 5,
        purpose: 'End-of-period reconciliation of all fee payments against expected revenue',
        owner_role: 'Bursar / School Accountant',
        entry_criteria: [
          'Payment deadline has passed',
          'Majority of payments collected',
        ],
        exit_criteria: [
          'All payments reconciled against invoices',
          'Outstanding balances identified and escalated',
          'Term fee collection closed',
        ],
        checklist: [
          { text: 'Reconcile total payments received against total invoices issued for the term', required: true },
          { text: 'Identify all students with outstanding balances and total amount owed', required: true },
          { text: 'Generate fee collection summary report: total expected, total collected, collection rate percentage', required: true },
          { text: 'Escalate chronic defaulters to school management for action', required: true },
          { text: 'Send final reminder to parents with outstanding balances', required: true },
          { text: 'Close fee collection cycle in CRM and archive for the term', required: true },
          { text: 'Prepare financial report for school management or board', required: true },
        ],
        sla_hint: '4 weeks after term starts',
      },
    ],
  },
  suggested_flows: ['payment_confirmation_flow', 'complaint_resolution_flow', 'feedback_collector'],
  suggested_automations: [
    { slug: 'payment_reminder', priority: 'essential', description: 'Automated fee reminders at 7 days, 3 days, and deadline day' },
    { slug: 'booking_confirmation', priority: 'essential', description: 'Send payment acknowledgement when fee is received' },
    { slug: 'overdue_payment_escalation', priority: 'essential', description: 'Escalate fees overdue by 2+ weeks to management' },
    { slug: 'delivery_notification', priority: 'recommended', description: 'Send receipt to parent when payment is processed' },
    { slug: 'dormant_reactivation', priority: 'optional', description: 'Re-engage parents of students who did not re-enrol for new term' },
  ],
  suggested_segments: ['pending_payments', 'active_last_30', 'high_value_customers', 'repeat_buyers', 'dormant_60_plus'],
  setup_actions: [
    { id: 'edu-fees-structure', title: 'Set up fee structure templates', description: 'Configure fee templates for each class and programme with instalment options', priority: 'essential', category: 'settings', target_url: '/invoices', estimated_minutes: 15, icon: '💰' },
    { id: 'edu-fees-reminders', title: 'Configure fee payment reminders', description: 'Set up automated reminders at 7 days, 3 days, deadline, and overdue', priority: 'essential', category: 'automations', target_url: '/automations/new', target_params: { template: 'payment_reminder' }, estimated_minutes: 5, icon: '⏰' },
    { id: 'edu-fees-confirmation', title: 'Set up payment acknowledgement', description: 'Configure auto-confirmation when fee payment is received', priority: 'essential', category: 'automations', target_url: '/automations/new', target_params: { template: 'booking_confirmation' }, estimated_minutes: 3, icon: '✅' },
    { id: 'edu-fees-escalation', title: 'Set up overdue fee escalation', description: 'Configure escalation for fees overdue by 2+ weeks to management', priority: 'recommended', category: 'automations', target_url: '/automations/new', target_params: { template: 'overdue_payment_escalation' }, estimated_minutes: 3, icon: '🚨' },
    { id: 'edu-fees-discounts', title: 'Configure discount rules', description: 'Set up sibling discounts, early payment discounts, and scholarship percentages', priority: 'recommended', category: 'settings', target_url: '/settings', estimated_minutes: 5, icon: '🎁' },
    { id: 'edu-fees-instalments', title: 'Set up instalment plan options', description: 'Configure approved payment schedules for parents who need to pay in instalments', priority: 'optional', category: 'settings', target_url: '/installments', estimated_minutes: 10, icon: '📅' },
  ],
  customization_hints: [
    'Set up your fee structure templates for each class and programme',
    'Configure payment deadline dates aligned with your school calendar',
    'Add instalment plan options with your approved payment schedules',
    'Set up automated reminder sequences: 7 days, 3 days, deadline, overdue',
    'Configure discount rules: sibling, early payment, scholarship percentages',
  ],
}
