import type { IndustryWorkflowBundle } from '../types'

// ============================================================
// HEALTHCARE — Consultation Pipeline
// ============================================================
export const HEALTHCARE_CONSULTATION_BUNDLE: IndustryWorkflowBundle = {
  id: 'healthcare-consultation',
  industry: 'Healthcare',
  process: 'sales',
  name: 'Healthcare Consultation Pipeline',
  description: 'Patient consultation pipeline from enquiry through appointment booking, consultation, treatment, and follow-up for Nigerian clinics and hospitals.',
  icon: '🩺',
  setup_time_minutes: 15,
  pipeline: {
    id: 'healthcare-consultation-pipeline',
    name: 'Patient Consultations',
    icon: '🩺',
    description: 'Patient enquiry to follow-up care',
    category: 'sales',
    stages: [
      {
        name: 'Patient Enquiry',
        color: '#6366F1',
        position: 1,
        purpose: 'Capture patient interest and initial health concern',
        owner_role: 'Receptionist / Patient Coordinator',
        entry_criteria: [
          'Patient has contacted via WhatsApp, phone, or walk-in',
          'Basic health concern communicated',
        ],
        exit_criteria: [
          'Patient contact details recorded',
          'Health concern categorised',
          'Appropriate department or specialist identified',
        ],
        checklist: [
          { text: 'Record patient full name, phone number, date of birth, and gender', required: true },
          { text: 'Ask about primary health concern or symptoms in patient own words', required: true },
          { text: 'Check if patient is new or returning (search existing records by phone number)', required: true },
          { text: 'Identify appropriate department: general practice, dental, eye clinic, lab, specialist', required: true },
          { text: 'Ask if patient has health insurance (HMO name and ID number)', required: false },
          { text: 'Inform patient of consultation fee in Naira and accepted payment methods', required: true },
          { text: 'Offer available appointment slots or walk-in availability', required: true },
        ],
        sla_hint: '1 business hour',
      },
      {
        name: 'Appointment Booked',
        color: '#8B5CF6',
        position: 2,
        purpose: 'Appointment scheduled with appropriate healthcare provider',
        owner_role: 'Receptionist',
        entry_criteria: [
          'Patient has agreed to book an appointment',
          'Available slot identified',
        ],
        exit_criteria: [
          'Appointment confirmed with date, time, and doctor',
          'Patient reminded of what to bring',
        ],
        checklist: [
          { text: 'Book appointment slot in scheduling system with doctor name and time', required: true },
          { text: 'Send appointment confirmation via WhatsApp with date, time, doctor name, and clinic address', required: true },
          { text: 'Inform patient what to bring: previous test results, medication list, HMO card, valid ID', required: true },
          { text: 'Advise on fasting requirements if applicable (e.g., blood tests require 8-12 hour fast)', required: false },
          { text: 'Set automated reminder for 24 hours before appointment', required: true },
          { text: 'Inform patient of cancellation/rescheduling policy', required: true },
        ],
        sla_hint: '30 minutes to confirm',
      },
      {
        name: 'Consultation',
        color: '#EC4899',
        position: 3,
        purpose: 'Patient sees the doctor for examination and diagnosis',
        owner_role: 'Doctor / Healthcare Provider',
        entry_criteria: [
          'Patient has arrived and checked in at reception',
          'Consultation fee paid or HMO verified',
        ],
        exit_criteria: [
          'Examination completed',
          'Diagnosis or preliminary assessment made',
          'Treatment plan or next steps communicated to patient',
        ],
        checklist: [
          { text: 'Verify patient identity and confirm appointment details', required: true },
          { text: 'Collect consultation fee via POS, bank transfer, or cash (or verify HMO authorisation)', required: true },
          { text: 'Record patient vitals: blood pressure, temperature, weight, pulse', required: true },
          { text: 'Conduct examination and document findings in patient record', required: true },
          { text: 'Order any required tests: blood work, X-ray, ultrasound, urinalysis', required: false },
          { text: 'Provide diagnosis or preliminary assessment to patient', required: true },
          { text: 'Prescribe medication or treatment plan with clear instructions', required: true },
        ],
        sla_hint: '30-60 minutes per consultation',
      },
      {
        name: 'Treatment / Tests',
        color: '#F59E0B',
        position: 4,
        purpose: 'Patient undergoes prescribed tests or begins treatment',
        owner_role: 'Lab Technician / Nurse',
        entry_criteria: [
          'Doctor has ordered tests or prescribed treatment',
          'Patient has consented to proceed',
        ],
        exit_criteria: [
          'All ordered tests completed and results available',
          'Treatment administered as prescribed',
          'Results communicated to doctor for review',
        ],
        checklist: [
          { text: 'Collect payment for tests or treatment (separate from consultation fee)', required: true },
          { text: 'Conduct ordered tests following standard laboratory protocols', required: true },
          { text: 'Administer prescribed treatment: injections, dressing, minor procedures', required: false },
          { text: 'Record all test results in patient file', required: true },
          { text: 'Flag any critical or abnormal results for immediate doctor attention', required: true },
          { text: 'Inform patient of expected timeline for results (same day, 24 hours, 3 days)', required: true },
        ],
        sla_hint: 'Same day for basic tests, 1-3 days for specialised',
      },
      {
        name: 'Results & Prescription',
        color: '#10B981',
        position: 5,
        purpose: 'Doctor reviews results and provides final prescription or referral',
        owner_role: 'Doctor',
        entry_criteria: [
          'Test results available',
          'Doctor has reviewed results',
        ],
        exit_criteria: [
          'Final diagnosis communicated to patient',
          'Prescription issued or referral made',
          'Follow-up appointment scheduled if needed',
        ],
        checklist: [
          { text: 'Review all test results and update diagnosis', required: true },
          { text: 'Communicate results to patient via WhatsApp or in-person follow-up', required: true },
          { text: 'Issue prescription with medication names, dosages, and duration', required: true },
          { text: 'If referral needed, provide referral letter with specialist name and contact', required: false },
          { text: 'Schedule follow-up appointment if ongoing monitoring required', required: true },
          { text: 'Advise patient on lifestyle changes, diet, or precautions', required: false },
        ],
        sla_hint: '24 hours after results available',
      },
      {
        name: 'Follow-Up',
        color: '#059669',
        position: 6,
        purpose: 'Post-consultation follow-up to monitor patient progress',
        owner_role: 'Patient Coordinator / Doctor',
        entry_criteria: [
          'Initial treatment or prescription provided',
          'Follow-up timeline established',
        ],
        exit_criteria: [
          'Patient progress checked',
          'Treatment adjusted if needed',
          'Case closed or ongoing care plan established',
        ],
        checklist: [
          { text: 'Send follow-up message via WhatsApp asking about patient condition and medication compliance', required: true },
          { text: 'Ask if patient is experiencing any side effects from prescribed medication', required: true },
          { text: 'Schedule follow-up appointment if symptoms persist or worsen', required: true },
          { text: 'Update patient record with follow-up notes', required: true },
          { text: 'If treatment complete, request feedback on clinic experience', required: false },
          { text: 'Tag patient for annual check-up reminder if applicable', required: false },
          { text: 'Close case in CRM or set next follow-up date', required: true },
        ],
        sla_hint: '3-7 days after consultation',
      },
    ],
  },
  suggested_flows: ['welcome_menu', 'appointment_booking_flow', 'payment_confirmation_flow', 'feedback_collector', 'delivery_tracking_flow'],
  suggested_automations: [
    { slug: 'welcome_message', priority: 'essential', description: 'Auto-greet patients with clinic services and booking instructions' },
    { slug: 'appointment_reminder_24h', priority: 'essential', description: 'Remind patients 24 hours before scheduled appointment' },
    { slug: 'booking_confirmation', priority: 'essential', description: 'Send confirmation when appointment is booked' },
    { slug: 'follow_up_reminder', priority: 'recommended', description: 'Follow up with patients 3 days after consultation' },
    { slug: 'review_request', priority: 'recommended', description: 'Request Google review after positive follow-up' },
    { slug: 'dormant_reactivation', priority: 'optional', description: 'Remind patients due for annual check-ups or screenings' },
  ],
  suggested_segments: ['active_last_30', 'appointment_no_shows', 'new_contacts_7d', 'dormant_60_plus', 'repeat_buyers', 'high_value_customers'],
  customization_hints: [
    'Add your specific departments and specialists for accurate appointment routing',
    'Configure consultation fees per department and update regularly',
    'Set up HMO verification workflow for insured patients',
    'Add your clinic address with Google Maps link for appointment confirmations',
    'Configure follow-up timing based on condition type (acute: 3 days, chronic: 2 weeks)',
  ],
}

// ============================================================
// HEALTHCARE — Pharmacy Dispensing Pipeline
// ============================================================
export const HEALTHCARE_DISPENSING_BUNDLE: IndustryWorkflowBundle = {
  id: 'healthcare-dispensing',
  industry: 'Healthcare',
  process: 'operations',
  name: 'Pharmacy Dispensing Pipeline',
  description: 'Pharmacy dispensing pipeline from prescription receipt through verification, dispensing, and patient follow-up for Nigerian pharmacies.',
  icon: '💊',
  setup_time_minutes: 10,
  pipeline: {
    id: 'healthcare-dispensing-pipeline',
    name: 'Pharmacy Dispensing',
    icon: '💊',
    description: 'Prescription to dispensing and follow-up',
    category: 'operations',
    stages: [
      {
        name: 'Prescription Received',
        color: '#6366F1',
        position: 1,
        purpose: 'Receive and log prescription from patient or referring doctor',
        owner_role: 'Pharmacy Technician',
        entry_criteria: [
          'Patient has presented a prescription (physical or WhatsApp photo)',
          'Prescription is from a licensed medical practitioner',
        ],
        exit_criteria: [
          'Prescription logged in system',
          'All medications identified',
          'Patient contact details recorded',
        ],
        checklist: [
          { text: 'Record patient name, phone number, and prescribing doctor name', required: true },
          { text: 'Verify prescription is signed by a licensed medical practitioner', required: true },
          { text: 'List all prescribed medications with dosages and quantities', required: true },
          { text: 'Check prescription date (must be within 30 days for most medications)', required: true },
          { text: 'Flag any controlled substances requiring special handling (NAFDAC Schedule)', required: true },
          { text: 'Ask patient about known allergies or current medications', required: true },
        ],
        sla_hint: '10 minutes',
      },
      {
        name: 'Verification',
        color: '#8B5CF6',
        position: 2,
        purpose: 'Pharmacist verifies prescription accuracy and checks for interactions',
        owner_role: 'Pharmacist',
        entry_criteria: [
          'Prescription logged in system',
          'Patient allergy information collected',
        ],
        exit_criteria: [
          'Prescription verified by pharmacist',
          'Drug interactions checked',
          'Stock availability confirmed',
        ],
        checklist: [
          { text: 'Verify dosages are appropriate for patient age, weight, and condition', required: true },
          { text: 'Check for drug-drug interactions with patient current medications', required: true },
          { text: 'Check for drug-allergy contraindications', required: true },
          { text: 'Verify all prescribed medications are in stock', required: true },
          { text: 'If any medication out of stock, identify suitable alternatives and contact prescribing doctor', required: true },
          { text: 'Calculate total cost and inform patient before dispensing', required: true },
        ],
        sla_hint: '15 minutes',
      },
      {
        name: 'Dispensing',
        color: '#F59E0B',
        position: 3,
        purpose: 'Prepare and dispense medications to patient',
        owner_role: 'Pharmacist / Pharmacy Technician',
        entry_criteria: [
          'Prescription verified by pharmacist',
          'All medications available',
          'Patient has agreed to proceed with purchase',
        ],
        exit_criteria: [
          'All medications dispensed and labelled',
          'Patient counselled on usage',
          'Payment collected',
        ],
        checklist: [
          { text: 'Count or measure each medication accurately', required: true },
          { text: 'Label each medication with: patient name, drug name, dosage, frequency, and expiry date', required: true },
          { text: 'Counsel patient on how to take each medication: timing, with/without food, storage', required: true },
          { text: 'Warn patient about common side effects and when to seek medical attention', required: true },
          { text: 'Collect payment via POS, bank transfer, or cash and issue receipt', required: true },
          { text: 'Record dispensing in pharmacy register as required by PCN regulations', required: true },
          { text: 'Update inventory to reflect dispensed quantities', required: true },
        ],
        sla_hint: '20 minutes',
      },
      {
        name: 'Follow-Up',
        color: '#059669',
        position: 4,
        purpose: 'Check on patient medication compliance and outcomes',
        owner_role: 'Pharmacist / Patient Care',
        entry_criteria: [
          'Medications dispensed to patient',
          'Follow-up timeline established based on medication type',
        ],
        exit_criteria: [
          'Patient contacted for follow-up',
          'Medication compliance confirmed',
          'Refill scheduled if needed',
        ],
        checklist: [
          { text: 'Send WhatsApp message after 3 days asking if patient is taking medication as directed', required: true },
          { text: 'Ask about any side effects or difficulties with the medication', required: true },
          { text: 'Remind patient to complete full course of antibiotics if applicable', required: true },
          { text: 'If medication is ongoing (chronic condition), set refill reminder before supply runs out', required: true },
          { text: 'Advise patient to return to doctor if symptoms do not improve', required: false },
          { text: 'Update patient record with follow-up notes', required: true },
        ],
        sla_hint: '3 days after dispensing',
      },
    ],
  },
  suggested_flows: ['welcome_menu', 'delivery_tracking_flow', 'payment_confirmation_flow', 'feedback_collector'],
  suggested_automations: [
    { slug: 'welcome_message', priority: 'essential', description: 'Auto-greet pharmacy customers with services and operating hours' },
    { slug: 'payment_reminder', priority: 'recommended', description: 'Remind patients with pending prescriptions to collect medications' },
    { slug: 'follow_up_reminder', priority: 'essential', description: 'Follow up 3 days after dispensing to check medication compliance' },
    { slug: 'dormant_reactivation', priority: 'recommended', description: 'Remind chronic patients when refill is due based on prescription duration' },
    { slug: 'review_request', priority: 'optional', description: 'Request feedback after positive follow-up interaction' },
  ],
  suggested_segments: ['active_last_30', 'repeat_buyers', 'dormant_60_plus', 'new_contacts_7d', 'high_value_customers'],
  customization_hints: [
    'Set up medication categories for better inventory tracking',
    'Configure refill reminders based on common prescription durations (7, 14, 30, 90 days)',
    'Add your pharmacy PCN licence number to receipts and communications',
    'Set up controlled substance tracking with additional verification steps',
    'Configure delivery option for patients who cannot visit the pharmacy',
  ],
}
