import type { IndustryWorkflowBundle } from '../types'

// ============================================================
// HOTELS — Reservation Pipeline
// ============================================================
export const HOTEL_RESERVATION_BUNDLE: IndustryWorkflowBundle = {
  id: 'hotel-reservation',
  industry: 'Hotels',
  process: 'sales',
  name: 'Hotel Reservation Pipeline',
  description: 'Room booking pipeline from enquiry through availability check, deposit, pre-arrival, check-in, and checkout for Nigerian hotels and guest houses.',
  icon: '🏨',
  setup_time_minutes: 15,
  pipeline: {
    id: 'hotel-reservation-pipeline',
    name: 'Hotel Reservations',
    icon: '🏨',
    description: 'Booking enquiry to checkout',
    category: 'sales',
    stages: [
      {
        name: 'Enquiry',
        color: '#6366F1',
        position: 1,
        purpose: 'Capture guest booking interest and requirements',
        owner_role: 'Reservations Agent',
        entry_criteria: [
          'Guest has contacted via WhatsApp, phone, website, or walk-in',
          'Basic booking interest expressed',
        ],
        exit_criteria: [
          'Check-in and check-out dates confirmed',
          'Room type preference identified',
          'Number of guests established',
        ],
        checklist: [
          { text: 'Record guest full name, phone number, and email address', required: true },
          { text: 'Confirm check-in date, check-out date, and number of nights', required: true },
          { text: 'Ask number of guests (adults and children)', required: true },
          { text: 'Identify room type preference: standard, deluxe, suite, or executive', required: true },
          { text: 'Ask purpose of visit: business, leisure, event, or corporate booking', required: false },
          { text: 'Check if guest has any special requirements: airport pickup, extra bed, dietary needs', required: false },
          { text: 'Note if booking is corporate (company name and corporate rate code)', required: false },
        ],
        sla_hint: '1 business hour',
      },
      {
        name: 'Availability Check',
        color: '#8B5CF6',
        position: 2,
        purpose: 'Verify room availability for requested dates and room type',
        owner_role: 'Reservations Agent',
        entry_criteria: [
          'Guest dates and room preference captured',
        ],
        exit_criteria: [
          'Availability confirmed or alternative dates/rooms proposed',
          'Rate communicated to guest',
        ],
        checklist: [
          { text: 'Check room availability in booking system for requested dates and room type', required: true },
          { text: 'If requested room unavailable, identify alternative room types or nearby dates', required: true },
          { text: 'Calculate total cost: nightly rate x nights + VAT + service charge in Naira', required: true },
          { text: 'Check for applicable discounts: corporate rate, long-stay discount, returning guest', required: false },
          { text: 'Communicate available options and pricing to guest via WhatsApp', required: true },
        ],
        sla_hint: '30 minutes',
      },
      {
        name: 'Quote Sent',
        color: '#EC4899',
        position: 3,
        purpose: 'Formal rate quote shared with guest for confirmation',
        owner_role: 'Reservations Agent',
        entry_criteria: [
          'Room availability confirmed',
          'Guest has expressed interest in proceeding',
        ],
        exit_criteria: [
          'Guest has accepted the quote',
          'Payment instructions shared',
        ],
        checklist: [
          { text: 'Send formal booking quote with room type, dates, nightly rate, total amount in Naira', required: true },
          { text: 'Include breakdown: room rate, VAT (7.5%), service charge, and any extras', required: true },
          { text: 'Specify deposit requirement: typically 50% or first night to confirm booking', required: true },
          { text: 'Include cancellation policy: free cancellation 48h before, 50% charge within 48h', required: true },
          { text: 'Share bank account details for transfer payment', required: true },
          { text: 'Set quote validity: 24 hours for peak periods, 48 hours for regular periods', required: true },
        ],
        sla_hint: '2 business hours',
      },
      {
        name: 'Deposit Paid',
        color: '#F59E0B',
        position: 4,
        purpose: 'Deposit received, booking confirmed in system',
        owner_role: 'Reservations Agent / Finance',
        entry_criteria: [
          'Guest has accepted the quote',
          'Deposit payment initiated',
        ],
        exit_criteria: [
          'Deposit verified in bank account',
          'Booking confirmed in reservation system',
          'Confirmation sent to guest',
        ],
        checklist: [
          { text: 'Verify deposit amount received matches required amount', required: true },
          { text: 'Record payment reference and method in booking system', required: true },
          { text: 'Block room in reservation system for confirmed dates', required: true },
          { text: 'Generate booking confirmation number', required: true },
          { text: 'Send booking confirmation via WhatsApp with: confirmation number, dates, room type, balance due', required: true },
          { text: 'Issue deposit receipt to guest', required: true },
        ],
        sla_hint: '2 business hours after payment',
      },
      {
        name: 'Pre-Arrival',
        color: '#3B82F6',
        position: 5,
        purpose: 'Prepare for guest arrival with pre-arrival communication and room preparation',
        owner_role: 'Front Desk / Housekeeping',
        entry_criteria: [
          'Booking confirmed with deposit',
          'Check-in date is within 3 days',
        ],
        exit_criteria: [
          'Guest reminded of booking details',
          'Room assigned and prepared',
          'Balance payment status confirmed',
        ],
        checklist: [
          { text: 'Send pre-arrival message 48 hours before check-in with hotel address and directions', required: true },
          { text: 'Confirm estimated arrival time with guest', required: true },
          { text: 'Remind guest of outstanding balance if not fully paid', required: true },
          { text: 'Assign specific room number based on guest preferences and availability', required: true },
          { text: 'Ensure room is cleaned, inspected, and amenities stocked', required: true },
          { text: 'Arrange airport pickup if requested (confirm flight details and driver assignment)', required: false },
          { text: 'Prepare welcome amenities for VIP or returning guests', required: false },
        ],
        sla_hint: '48 hours before check-in',
      },
      {
        name: 'Checked In',
        color: '#10B981',
        position: 6,
        purpose: 'Guest has arrived and checked into the hotel',
        owner_role: 'Front Desk',
        entry_criteria: [
          'Guest has arrived at the hotel',
          'Room is ready',
        ],
        exit_criteria: [
          'Guest registered and checked in',
          'Room key issued',
          'Outstanding balance collected or payment arrangement confirmed',
        ],
        checklist: [
          { text: 'Verify guest identity with valid ID (NIN, passport, or driver licence)', required: true },
          { text: 'Collect outstanding balance: bank transfer, POS, or cash', required: true },
          { text: 'Complete guest registration card with emergency contact', required: true },
          { text: 'Issue room key card or key and explain room location', required: true },
          { text: 'Brief guest on hotel facilities: restaurant, gym, pool, Wi-Fi password, breakfast times', required: true },
          { text: 'Share front desk WhatsApp number for in-stay requests', required: true },
          { text: 'Record check-in time in system', required: true },
        ],
        sla_hint: '15 minutes check-in process',
      },
      {
        name: 'Checked Out',
        color: '#059669',
        position: 7,
        purpose: 'Guest has departed, room cleared, post-stay follow-up initiated',
        owner_role: 'Front Desk / Housekeeping',
        entry_criteria: [
          'Guest has requested checkout or checkout time reached',
        ],
        exit_criteria: [
          'Room inspected and cleared',
          'Final bill settled',
          'Feedback requested',
          'Deal closed in CRM',
        ],
        checklist: [
          { text: 'Generate final bill including room charges, restaurant, minibar, laundry, and extras', required: true },
          { text: 'Collect any outstanding charges via POS, transfer, or cash', required: true },
          { text: 'Issue final receipt and invoice (for corporate guests, issue company invoice)', required: true },
          { text: 'Collect room key and check room for damages or missing items', required: true },
          { text: 'Send thank-you message via WhatsApp within 2 hours of checkout', required: true },
          { text: 'Request Google review or TripAdvisor review if guest had positive experience', required: false },
          { text: 'Tag guest as returning-guest for future promotions and loyalty pricing', required: true },
          { text: 'Update booking as completed in CRM with total revenue', required: true },
        ],
        sla_hint: '10 minutes checkout, 2 hours for follow-up',
      },
    ],
  },
  suggested_flows: ['welcome_menu', 'hotel_booking_flow', 'payment_confirmation_flow', 'feedback_collector', 'complaint_resolution_flow'],
  suggested_automations: [
    { slug: 'welcome_message', priority: 'essential', description: 'Auto-greet booking enquiries with room types and rates' },
    { slug: 'booking_confirmation', priority: 'essential', description: 'Send confirmation when deposit is verified' },
    { slug: 'appointment_reminder_24h', priority: 'essential', description: 'Send pre-arrival reminder 24 hours before check-in' },
    { slug: 'payment_reminder', priority: 'recommended', description: 'Remind guests of outstanding balance 48 hours before arrival' },
    { slug: 'post_checkout_feedback', priority: 'recommended', description: 'Request feedback and review 2 hours after checkout' },
    { slug: 'dormant_reactivation', priority: 'optional', description: 'Send special rates to past guests who have not returned in 90+ days' },
  ],
  suggested_segments: ['active_last_30', 'high_value_customers', 'repeat_buyers', 'dormant_60_plus', 'new_contacts_7d', 'seasonal_buyers'],
  customization_hints: [
    'Set up room type catalogue with photos and current rates for quick sharing',
    'Configure corporate rate codes for your business clients',
    'Add seasonal pricing rules for peak periods (December, Easter, public holidays)',
    'Set up automated pre-arrival messages with your hotel address and landmark directions',
    'Create VIP guest tags for returning guests who deserve special treatment',
  ],
}

// ============================================================
// HOTELS — Event Booking Pipeline
// ============================================================
export const HOTEL_EVENT_BUNDLE: IndustryWorkflowBundle = {
  id: 'hotel-event',
  industry: 'Hotels',
  process: 'operations',
  name: 'Hotel Event Booking Pipeline',
  description: 'Event and conference booking pipeline from venue enquiry through inspection, proposal, planning, and post-event follow-up.',
  icon: '🎉',
  setup_time_minutes: 15,
  pipeline: {
    id: 'hotel-event-pipeline',
    name: 'Event Bookings',
    icon: '🎉',
    description: 'Event enquiry to post-event follow-up',
    category: 'operations',
    stages: [
      {
        name: 'Enquiry',
        color: '#6366F1',
        position: 1,
        purpose: 'Capture event requirements and initial details',
        owner_role: 'Events Coordinator',
        entry_criteria: [
          'Client has enquired about hosting an event at the hotel',
        ],
        exit_criteria: [
          'Event type, date, and estimated guest count captured',
          'Venue inspection scheduled',
        ],
        checklist: [
          { text: 'Record client name, company (if corporate), phone number, and email', required: true },
          { text: 'Identify event type: wedding reception, corporate conference, birthday, seminar, end-of-year party', required: true },
          { text: 'Confirm preferred event date(s) and duration (half-day, full-day, multi-day)', required: true },
          { text: 'Ask estimated number of guests (minimum and maximum)', required: true },
          { text: 'Identify requirements: catering, AV equipment, decoration, accommodation for guests', required: true },
          { text: 'Ask budget range to recommend appropriate venue and package', required: false },
          { text: 'Schedule venue inspection within 5 business days', required: true },
        ],
        sla_hint: '4 business hours',
      },
      {
        name: 'Venue Inspection',
        color: '#8B5CF6',
        position: 2,
        purpose: 'Client visits and inspects the event venue',
        owner_role: 'Events Coordinator',
        entry_criteria: [
          'Inspection date and time confirmed with client',
          'Venue prepared for viewing',
        ],
        exit_criteria: [
          'Client has viewed the venue',
          'Specific requirements discussed on-site',
          'Client feedback on venue suitability collected',
        ],
        checklist: [
          { text: 'Send inspection reminder via WhatsApp 24 hours before scheduled visit', required: true },
          { text: 'Prepare venue for viewing: clean, well-lit, sample table setup if possible', required: true },
          { text: 'Walk client through venue: main hall, breakout rooms, restrooms, parking, generator backup', required: true },
          { text: 'Discuss seating arrangements and capacity for their guest count', required: true },
          { text: 'Show AV capabilities: projector, sound system, microphones, lighting', required: true },
          { text: 'Discuss catering options and show sample menus with per-head pricing', required: true },
          { text: 'Take note of any special requests: stage setup, photo booth area, VIP lounge', required: false },
        ],
        sla_hint: '5 business days from enquiry',
      },
      {
        name: 'Proposal Sent',
        color: '#EC4899',
        position: 3,
        purpose: 'Formal event proposal with pricing shared with client',
        owner_role: 'Events Coordinator / Sales Manager',
        entry_criteria: [
          'Venue inspection completed',
          'Client has expressed interest in proceeding',
        ],
        exit_criteria: [
          'Proposal accepted by client',
          'Payment terms agreed',
        ],
        checklist: [
          { text: 'Prepare detailed proposal: venue hire, catering per head, AV, decoration, accommodation in Naira', required: true },
          { text: 'Include floor plan or seating layout for the event', required: false },
          { text: 'Specify payment terms: 50% deposit to confirm, 30% two weeks before, 20% balance on event day', required: true },
          { text: 'Include cancellation and date-change policy', required: true },
          { text: 'Send proposal via email with WhatsApp notification', required: true },
          { text: 'Follow up within 3 days if no response received', required: true },
        ],
        sla_hint: '3 business days after inspection',
      },
      {
        name: 'Deposit Paid',
        color: '#F59E0B',
        position: 4,
        purpose: 'Deposit received, event date confirmed and blocked',
        owner_role: 'Events Coordinator / Finance',
        entry_criteria: [
          'Client has accepted the proposal',
          'Deposit payment received',
        ],
        exit_criteria: [
          'Deposit verified',
          'Event date blocked on venue calendar',
          'Booking confirmation sent',
        ],
        checklist: [
          { text: 'Verify deposit amount (minimum 50% of total) received in hotel bank account', required: true },
          { text: 'Issue official deposit receipt', required: true },
          { text: 'Block event date on venue calendar to prevent double-booking', required: true },
          { text: 'Send booking confirmation with event details, date, and outstanding balance', required: true },
          { text: 'Set reminder for second payment instalment (2 weeks before event)', required: true },
          { text: 'Assign dedicated event coordinator as client single point of contact', required: true },
        ],
        sla_hint: '24 hours to process',
      },
      {
        name: 'Event Planning',
        color: '#3B82F6',
        position: 5,
        purpose: 'Detailed event planning and coordination with client',
        owner_role: 'Events Coordinator',
        entry_criteria: [
          'Booking confirmed with deposit',
          'Event is within 4 weeks',
        ],
        exit_criteria: [
          'All event details finalised',
          'Vendor coordination complete',
          'Run sheet prepared',
        ],
        checklist: [
          { text: 'Conduct planning meeting with client to finalise all details', required: true },
          { text: 'Confirm final guest count and adjust catering order accordingly', required: true },
          { text: 'Finalise menu selection with chef and confirm any dietary requirements', required: true },
          { text: 'Coordinate with decoration vendor if external decorator being used', required: false },
          { text: 'Prepare event run sheet with timeline: setup, guest arrival, programme, teardown', required: true },
          { text: 'Confirm AV requirements and test all equipment', required: true },
          { text: 'Arrange accommodation block for out-of-town guests if needed', required: false },
          { text: 'Collect balance payment (remaining 50%) minimum 3 days before event', required: true },
        ],
        sla_hint: '2-4 weeks before event',
      },
      {
        name: 'Event Day',
        color: '#10B981',
        position: 6,
        purpose: 'Event execution day with on-site coordination',
        owner_role: 'Events Coordinator / Duty Manager',
        entry_criteria: [
          'Full payment received',
          'All preparations complete',
          'Event day has arrived',
        ],
        exit_criteria: [
          'Event successfully executed',
          'No major incidents',
          'Client satisfied with service',
        ],
        checklist: [
          { text: 'Arrive at venue 3 hours before event start for final setup', required: true },
          { text: 'Verify all setup matches agreed plan: seating, decoration, AV, signage', required: true },
          { text: 'Brief all staff on event timeline, VIP guests, and special instructions', required: true },
          { text: 'Ensure generator is fuelled and on standby (critical for Nigerian events)', required: true },
          { text: 'Coordinate food service timing with kitchen based on event programme', required: true },
          { text: 'Be available throughout event to handle any issues or last-minute requests', required: true },
          { text: 'Take photos of event setup and execution for hotel portfolio (with client permission)', required: false },
        ],
        sla_hint: 'Full event duration',
      },
      {
        name: 'Post-Event',
        color: '#059669',
        position: 7,
        purpose: 'Post-event cleanup, reconciliation, and client follow-up',
        owner_role: 'Events Coordinator',
        entry_criteria: [
          'Event has concluded',
          'Guests have departed',
        ],
        exit_criteria: [
          'Venue restored to original condition',
          'Final reconciliation complete',
          'Client feedback collected',
          'Deal closed in CRM',
        ],
        checklist: [
          { text: 'Supervise venue cleanup and restoration', required: true },
          { text: 'Check for any damages to venue or equipment and document with photos', required: true },
          { text: 'Reconcile final bill: any extras, additional guests, bar tab, overtime charges', required: true },
          { text: 'Send final invoice if additional charges apply, or confirm no extra charges', required: true },
          { text: 'Send thank-you message to client within 24 hours', required: true },
          { text: 'Request feedback and permission to use event photos for marketing', required: true },
          { text: 'Ask for referral: does client know anyone planning an event?', required: false },
          { text: 'Update CRM with final event revenue and close the deal', required: true },
        ],
        sla_hint: '48 hours after event',
      },
    ],
  },
  suggested_flows: ['welcome_menu', 'catering_enquiry_flow', 'payment_confirmation_flow', 'feedback_collector', 'complaint_resolution_flow'],
  suggested_automations: [
    { slug: 'welcome_message', priority: 'essential', description: 'Auto-greet event enquiries with venue brochure and capacity info' },
    { slug: 'booking_confirmation', priority: 'essential', description: 'Send confirmation when event deposit is received' },
    { slug: 'payment_reminder', priority: 'essential', description: 'Remind client of balance payment 2 weeks and 3 days before event' },
    { slug: 'appointment_reminder_24h', priority: 'recommended', description: 'Send event-day reminder to client 24 hours before' },
    { slug: 'post_checkout_feedback', priority: 'recommended', description: 'Request feedback and review 48 hours after event' },
    { slug: 'dormant_reactivation', priority: 'optional', description: 'Re-engage past event clients before festive seasons' },
  ],
  suggested_segments: ['event_leads', 'high_value_customers', 'repeat_buyers', 'referral_sources', 'seasonal_buyers', 'active_last_30'],
  customization_hints: [
    'Create event packages at different price points for quick quoting (silver, gold, platinum)',
    'Set up seasonal promotions for December parties, Valentine events, and corporate year-end',
    'Add your venue photos and capacity details to the event enquiry flow',
    'Configure payment milestone reminders based on your standard payment terms',
    'Tag events by type for targeted marketing to past clients',
  ],
}
