import type { IndustryWorkflowBundle, SetupAction } from '../types'

// ============================================================
// LOGISTICS — Shipment Pipeline
// ============================================================
export const LOGISTICS_SHIPMENT_BUNDLE: IndustryWorkflowBundle = {
  id: 'logistics-shipment',
  industry: 'Logistics',
  process: 'sales',
  name: 'Logistics Shipment Pipeline',
  description: 'Shipment tracking pipeline from booking through pickup, hub processing, last-mile delivery, and proof of delivery for Nigerian logistics and courier companies.',
  icon: '🚚',
  setup_time_minutes: 12,
  pipeline: {
    id: 'logistics-shipment-pipeline',
    name: 'Shipment Tracking',
    icon: '🚚',
    description: 'Booking to proof of delivery',
    category: 'sales',
    stages: [
      {
        name: 'Booking',
        color: '#6366F1',
        position: 1,
        purpose: 'Customer books a shipment with origin, destination, and package details',
        owner_role: 'Customer Service / Booking Agent',
        entry_criteria: [
          'Customer has contacted via WhatsApp, phone, walk-in, or website',
          'Shipment request communicated',
        ],
        exit_criteria: [
          'Shipment details captured and waybill number generated',
          'Pickup or drop-off arranged',
          'Payment collected or payment terms agreed',
        ],
        checklist: [
          { text: 'Record sender full name, phone number, and pickup address with state and LGA', required: true },
          { text: 'Record receiver full name, phone number, and delivery address with state and LGA', required: true },
          { text: 'Document package details: description, weight (kg), dimensions, quantity of items', required: true },
          { text: 'Classify shipment type: document, parcel, fragile, perishable, or oversized', required: true },
          { text: 'Calculate shipping cost based on weight, dimensions, origin-destination, and service level', required: true },
          { text: 'Offer service level: same-day (within city), next-day, standard (2-5 days), economy', required: true },
          { text: 'Collect payment via bank transfer, POS, or cash and issue receipt', required: true },
          { text: 'Generate waybill number and share with sender via WhatsApp', required: true },
          { text: 'Schedule pickup time or confirm drop-off location and hours', required: true },
        ],
        sla_hint: '30 minutes for booking',
      },
      {
        name: 'Picked Up',
        color: '#8B5CF6',
        position: 2,
        purpose: 'Package collected from sender or received at drop-off point',
        owner_role: 'Dispatch Rider / Pickup Agent',
        entry_criteria: [
          'Booking confirmed and waybill generated',
          'Pickup scheduled or sender arriving at drop-off',
        ],
        exit_criteria: [
          'Package physically collected and inspected',
          'Package scanned into system',
          'Sender notified of successful pickup',
        ],
        checklist: [
          { text: 'Arrive at pickup location within scheduled time window', required: true },
          { text: 'Verify package matches booking description: weight, dimensions, item count', required: true },
          { text: 'Inspect package condition and note any pre-existing damage with photos', required: true },
          { text: 'Ensure package is properly sealed and labelled with waybill sticker', required: true },
          { text: 'Have sender sign pickup confirmation (digital or physical)', required: true },
          { text: 'Scan waybill barcode to update status to Picked Up in tracking system', required: true },
          { text: 'Send pickup confirmation to sender via WhatsApp with tracking link', required: true },
        ],
        sla_hint: 'Within 2 hours of scheduled pickup',
      },
      {
        name: 'At Hub',
        color: '#EC4899',
        position: 3,
        purpose: 'Package received at sorting hub for processing and routing',
        owner_role: 'Hub Supervisor',
        entry_criteria: [
          'Package picked up and in transit to hub',
          'Waybill scanned at pickup',
        ],
        exit_criteria: [
          'Package received and scanned at hub',
          'Sorted to correct destination route',
          'Loaded onto outbound vehicle',
        ],
        checklist: [
          { text: 'Receive package at hub and scan waybill to confirm arrival', required: true },
          { text: 'Verify package condition: no damage during transit from pickup', required: true },
          { text: 'Sort package by destination state, city, and delivery zone', required: true },
          { text: 'For interstate shipments, assign to correct outbound truck or bus route', required: true },
          { text: 'For intercity shipments, assign to local dispatch rider or delivery vehicle', required: true },
          { text: 'Load package onto outbound vehicle and record manifest', required: true },
          { text: 'Update tracking status and send transit notification to sender and receiver', required: true },
        ],
        sla_hint: '4-8 hours at hub',
      },
      {
        name: 'In Transit',
        color: '#F59E0B',
        position: 4,
        purpose: 'Package in transit between hubs or to destination city',
        owner_role: 'Transport Coordinator',
        entry_criteria: [
          'Package loaded onto outbound vehicle',
          'Manifest recorded',
        ],
        exit_criteria: [
          'Package arrived at destination hub or delivery zone',
          'Ready for last-mile delivery',
        ],
        checklist: [
          { text: 'Track vehicle location and estimated arrival time', required: true },
          { text: 'For interstate: monitor truck progress and update ETA if delayed', required: true },
          { text: 'If using partner carrier (e.g., GIG, ABC Transport), track partner waybill', required: false },
          { text: 'Notify receiver of expected delivery date via WhatsApp', required: true },
          { text: 'Scan package at destination hub upon arrival', required: true },
          { text: 'Assign to last-mile delivery rider or schedule receiver pickup', required: true },
        ],
        sla_hint: 'Same-day to 3 days depending on route',
      },
      {
        name: 'Out for Delivery',
        color: '#10B981',
        position: 5,
        purpose: 'Package assigned to delivery rider for final delivery to receiver',
        owner_role: 'Dispatch Rider / Delivery Agent',
        entry_criteria: [
          'Package at destination hub or delivery zone',
          'Delivery rider assigned',
        ],
        exit_criteria: [
          'Package delivered to receiver',
          'Proof of delivery captured',
        ],
        checklist: [
          { text: 'Assign package to delivery rider with receiver address and phone number', required: true },
          { text: 'Send out-for-delivery notification to receiver via WhatsApp with rider contact', required: true },
          { text: 'Rider calls receiver 30 minutes before arrival to confirm availability', required: true },
          { text: 'If cash on delivery (COD), collect payment from receiver before handing over package', required: false },
          { text: 'Have receiver verify package contents and sign delivery confirmation', required: true },
          { text: 'Take photo of delivered package as proof of delivery (POD)', required: true },
          { text: 'If receiver unavailable, attempt redelivery or arrange alternative (neighbour, office, pickup point)', required: true },
        ],
        sla_hint: 'Within 4 hours of assignment',
      },
      {
        name: 'Delivered',
        color: '#059669',
        position: 6,
        purpose: 'Package successfully delivered with proof of delivery confirmed',
        owner_role: 'Customer Service',
        entry_criteria: [
          'Delivery rider has confirmed delivery',
          'Proof of delivery photo uploaded',
        ],
        exit_criteria: [
          'Delivery confirmed in system',
          'Sender and receiver notified',
          'Shipment closed in CRM',
        ],
        checklist: [
          { text: 'Verify proof of delivery photo is clear and shows package at delivery location', required: true },
          { text: 'Update tracking status to Delivered with timestamp', required: true },
          { text: 'Send delivery confirmation to sender via WhatsApp', required: true },
          { text: 'Send delivery confirmation to receiver via WhatsApp', required: true },
          { text: 'If COD, confirm payment collected and remit to finance', required: false },
          { text: 'Request delivery rating from receiver (1-5 stars)', required: false },
          { text: 'Close shipment in CRM and update customer lifetime shipment count', required: true },
        ],
        sla_hint: '1 hour for confirmation after delivery',
      },
    ],
  },
  suggested_flows: ['welcome_menu', 'delivery_tracking_flow', 'payment_confirmation_flow', 'complaint_resolution_flow', 'feedback_collector'],
  suggested_automations: [
    { slug: 'welcome_message', priority: 'essential', description: 'Auto-greet customers with shipping rates and booking instructions' },
    { slug: 'delivery_notification', priority: 'essential', description: 'Notify sender and receiver at each tracking milestone' },
    { slug: 'booking_confirmation', priority: 'essential', description: 'Send waybill and tracking details after booking' },
    { slug: 'payment_reminder', priority: 'recommended', description: 'Remind customers with pending COD collections' },
    { slug: 'review_request', priority: 'recommended', description: 'Request rating after successful delivery' },
    { slug: 'dormant_reactivation', priority: 'optional', description: 'Re-engage customers who have not shipped in 60+ days' },
  ],
  suggested_segments: ['active_last_30', 'repeat_buyers', 'high_value_customers', 'new_contacts_7d', 'dormant_60_plus'],
  setup_actions: [
    { id: 'logistics-ship-routes', title: 'Set up route pricing matrix', description: 'Configure origin-to-destination rates per kg for your coverage areas', priority: 'essential', category: 'settings', target_url: '/settings', estimated_minutes: 15, icon: '🗺️' },
    { id: 'logistics-ship-welcome', title: 'Customise shipping enquiry greeting', description: 'Edit the auto-greeting to include shipping rates and booking instructions', priority: 'essential', category: 'automations', target_url: '/automations/new', target_params: { template: 'welcome_message' }, estimated_minutes: 5, icon: '👋' },
    { id: 'logistics-ship-tracking', title: 'Set up tracking milestone notifications', description: 'Configure auto-notifications at each tracking stage for sender and receiver', priority: 'essential', category: 'automations', target_url: '/automations/new', target_params: { template: 'delivery_notification' }, estimated_minutes: 5, icon: '📲' },
    { id: 'logistics-ship-hubs', title: 'Add hub locations', description: 'Set up your hub and warehouse locations for accurate tracking updates', priority: 'recommended', category: 'settings', target_url: '/inventory', estimated_minutes: 5, icon: '📍' },
    { id: 'logistics-ship-cod', title: 'Configure COD reconciliation workflow', description: 'Set up cash-on-delivery reconciliation process for COD shipments', priority: 'recommended', category: 'settings', target_url: '/settings', estimated_minutes: 5, icon: '💰' },
    { id: 'logistics-ship-feedback', title: 'Set up delivery rating request', description: 'Request customer rating after successful delivery', priority: 'optional', category: 'automations', target_url: '/automations/new', target_params: { template: 'review_request' }, estimated_minutes: 3, icon: '⭐' },
  ],
  customization_hints: [
    'Set up your route pricing matrix: origin state to destination state rates per kg',
    'Configure service levels with realistic delivery timelines for your coverage area',
    'Add your hub locations for accurate tracking updates',
    'Set up automated tracking notifications at each stage transition',
    'Configure COD reconciliation workflow for cash-on-delivery shipments',
  ],
}

// ============================================================
// LOGISTICS — Claims Pipeline
// ============================================================
export const LOGISTICS_CLAIMS_BUNDLE: IndustryWorkflowBundle = {
  id: 'logistics-claims',
  industry: 'Logistics',
  process: 'operations',
  name: 'Logistics Claims Pipeline',
  description: 'Damage and loss claims pipeline from claim filing through investigation, resolution, and compensation for Nigerian logistics companies.',
  icon: '📋',
  setup_time_minutes: 10,
  pipeline: {
    id: 'logistics-claims-pipeline',
    name: 'Claims Management',
    icon: '📋',
    description: 'Claim filed to resolution',
    category: 'operations',
    stages: [
      {
        name: 'Claim Filed',
        color: '#EF4444',
        position: 1,
        purpose: 'Customer reports damage, loss, or delivery issue and files a formal claim',
        owner_role: 'Customer Service',
        entry_criteria: [
          'Customer has reported an issue with their shipment',
          'Waybill number provided',
        ],
        exit_criteria: [
          'Claim logged with all supporting documentation',
          'Claim reference number issued to customer',
          'Investigation team notified',
        ],
        checklist: [
          { text: 'Record customer name, phone number, and waybill number', required: true },
          { text: 'Identify claim type: damaged goods, lost package, partial delivery, wrong delivery, delayed delivery', required: true },
          { text: 'Collect evidence from customer: photos of damage, description of missing items, delivery photos', required: true },
          { text: 'Record declared value of goods and any insurance coverage', required: true },
          { text: 'Check shipment history in tracking system for anomalies', required: true },
          { text: 'Generate claim reference number and share with customer via WhatsApp', required: true },
          { text: 'Set expectation with customer: investigation will take 3-5 business days', required: true },
          { text: 'Escalate to operations manager for investigation', required: true },
        ],
        sla_hint: '2 business hours to log claim',
      },
      {
        name: 'Investigation',
        color: '#F59E0B',
        position: 2,
        purpose: 'Internal investigation to determine cause and liability',
        owner_role: 'Operations Manager',
        entry_criteria: [
          'Claim logged with supporting documentation',
          'Investigation assigned to operations team',
        ],
        exit_criteria: [
          'Root cause identified',
          'Liability determined (company, partner, or customer)',
          'Resolution recommendation prepared',
        ],
        checklist: [
          { text: 'Review complete shipment tracking history: pickup, hub scans, transit, delivery', required: true },
          { text: 'Interview pickup rider, hub staff, and delivery rider involved in the shipment', required: true },
          { text: 'Check CCTV footage at hub if available for the relevant date and time', required: false },
          { text: 'If partner carrier involved, file claim with partner and request their investigation', required: false },
          { text: 'Compare customer evidence (photos, description) with pickup condition report', required: true },
          { text: 'Determine liability: packaging failure, handling damage, theft, misrouting, or customer error', required: true },
          { text: 'Calculate compensation amount based on declared value, insurance, and company policy', required: true },
          { text: 'Prepare investigation report with findings and recommended resolution', required: true },
        ],
        sla_hint: '3-5 business days',
      },
      {
        name: 'Resolution Offered',
        color: '#3B82F6',
        position: 3,
        purpose: 'Resolution proposed to customer based on investigation findings',
        owner_role: 'Customer Service Manager',
        entry_criteria: [
          'Investigation completed',
          'Resolution recommendation approved by management',
        ],
        exit_criteria: [
          'Customer has accepted or negotiated the resolution',
          'Final resolution agreed',
        ],
        checklist: [
          { text: 'Contact customer via WhatsApp with investigation findings summary', required: true },
          { text: 'Present resolution offer: full refund, partial refund, replacement shipment, or credit', required: true },
          { text: 'If claim denied, explain reason clearly with supporting evidence', required: true },
          { text: 'If customer disputes resolution, escalate to senior management for review', required: false },
          { text: 'Document customer response and final agreed resolution', required: true },
          { text: 'Get customer written acceptance of resolution via WhatsApp message', required: true },
        ],
        sla_hint: '24 hours after investigation',
      },
      {
        name: 'Compensation Processed',
        color: '#10B981',
        position: 4,
        purpose: 'Agreed compensation paid or replacement arranged',
        owner_role: 'Finance / Customer Service',
        entry_criteria: [
          'Resolution accepted by customer',
          'Compensation amount or action approved',
        ],
        exit_criteria: [
          'Compensation paid or replacement delivered',
          'Customer confirmed satisfaction',
          'Claim closed in system',
        ],
        checklist: [
          { text: 'Process refund via bank transfer to customer account (collect account details)', required: true },
          { text: 'If replacement shipment, arrange new pickup and delivery at no charge', required: false },
          { text: 'If credit issued, apply to customer account for future shipments', required: false },
          { text: 'Send payment confirmation or replacement tracking to customer via WhatsApp', required: true },
          { text: 'Ask customer to confirm receipt of compensation', required: true },
          { text: 'Document lessons learned and update handling procedures if needed', required: true },
          { text: 'Close claim in CRM with final resolution details and total cost', required: true },
          { text: 'If staff negligence identified, initiate internal disciplinary process', required: false },
        ],
        sla_hint: '3 business days for payment',
      },
    ],
  },
  suggested_flows: ['complaint_resolution_flow', 'payment_confirmation_flow', 'delivery_tracking_flow', 'feedback_collector'],
  suggested_automations: [
    { slug: 'booking_confirmation', priority: 'essential', description: 'Send claim reference number when claim is filed' },
    { slug: 'follow_up_reminder', priority: 'essential', description: 'Update customer on investigation progress every 2 days' },
    { slug: 'overdue_payment_escalation', priority: 'recommended', description: 'Escalate claims not resolved within 5 business days' },
    { slug: 'review_request', priority: 'optional', description: 'Request feedback after claim resolution' },
  ],
  suggested_segments: ['pending_payments', 'active_last_30', 'high_value_customers', 'repeat_buyers'],
  setup_actions: [
    { id: 'logistics-claims-policy', title: 'Define compensation policy in settings', description: 'Set maximum liability per kg, insurance options, and excluded items', priority: 'essential', category: 'settings', target_url: '/settings', estimated_minutes: 10, icon: '📋' },
    { id: 'logistics-claims-confirm', title: 'Set up claim acknowledgement', description: 'Configure auto-confirmation with claim reference number when claim is filed', priority: 'essential', category: 'automations', target_url: '/automations/new', target_params: { template: 'booking_confirmation' }, estimated_minutes: 3, icon: '✅' },
    { id: 'logistics-claims-updates', title: 'Configure investigation progress updates', description: 'Set up auto-updates to customer every 2 days during investigation', priority: 'essential', category: 'automations', target_url: '/automations/new', target_params: { template: 'follow_up_reminder' }, estimated_minutes: 5, icon: '📞' },
    { id: 'logistics-claims-escalation', title: 'Set up claim escalation rules', description: 'Configure escalation for claims not resolved within 5 business days', priority: 'recommended', category: 'automations', target_url: '/automations/new', target_params: { template: 'overdue_payment_escalation' }, estimated_minutes: 3, icon: '🚨' },
    { id: 'logistics-claims-categories', title: 'Set up claim category tags', description: 'Create tags for claim types (damage, loss, delay, shortage) with investigation checklists', priority: 'recommended', category: 'contacts', target_url: '/contacts', target_params: { tab: 'tags' }, estimated_minutes: 5, icon: '🏷️' },
    { id: 'logistics-claims-feedback', title: 'Set up post-resolution feedback', description: 'Request feedback after claim resolution', priority: 'optional', category: 'automations', target_url: '/automations/new', target_params: { template: 'review_request' }, estimated_minutes: 3, icon: '⭐' },
  ],
  customization_hints: [
    'Define your compensation policy: maximum liability per kg, insurance options, excluded items',
    'Set up claim categories with standard investigation checklists',
    'Configure escalation rules for high-value claims above your threshold',
    'Add partner carrier claim procedures for shipments handled by third parties',
    'Track claim rates by route and hub to identify problem areas',
  ],
}
