import type { IndustryWorkflowBundle } from '../types'

// ============================================================
// MANUFACTURING — Sales Pipeline
// ============================================================
export const MANUFACTURING_SALES_BUNDLE: IndustryWorkflowBundle = {
  id: 'manufacturing-sales',
  industry: 'Manufacturing',
  process: 'sales',
  name: 'Manufacturing Sales Pipeline',
  description: 'B2B manufacturing sales pipeline from RFQ through technical review, quotation, sample approval, production, and delivery for Nigerian manufacturers.',
  icon: '🏭',
  setup_time_minutes: 15,
  pipeline: {
    id: 'manufacturing-sales-pipeline',
    name: 'Manufacturing Sales',
    icon: '🏭',
    description: 'RFQ to delivery and payment',
    category: 'sales',
    stages: [
      {
        name: 'RFQ Received',
        color: '#6366F1',
        position: 1,
        purpose: 'Capture buyer request for quotation with product specifications',
        owner_role: 'Sales / Business Development',
        entry_criteria: [
          'Buyer has submitted a request for quotation via WhatsApp, email, or in-person',
          'Product or service requirement communicated',
        ],
        exit_criteria: [
          'RFQ logged with full specifications',
          'Feasibility assessment initiated',
        ],
        checklist: [
          { text: 'Record buyer company name, contact person, phone number, and email', required: true },
          { text: 'Document product specifications: dimensions, material, finish, colour, weight tolerances', required: true },
          { text: 'Confirm required quantity and whether this is a one-time order or recurring supply', required: true },
          { text: 'Ask for technical drawings, samples, or reference images if available', required: true },
          { text: 'Confirm required delivery date and delivery location (state and city)', required: true },
          { text: 'Ask about packaging requirements: bulk, individual, branded, export-grade', required: false },
          { text: 'Determine if buyer requires SON or NAFDAC certification for the product', required: false },
        ],
        sla_hint: '4 business hours',
      },
      {
        name: 'Technical Review',
        color: '#8B5CF6',
        position: 2,
        purpose: 'Engineering team reviews feasibility and production requirements',
        owner_role: 'Production Manager / Engineer',
        entry_criteria: [
          'RFQ logged with complete specifications',
          'Technical drawings or samples received if applicable',
        ],
        exit_criteria: [
          'Feasibility confirmed or alternative proposed',
          'Bill of materials and production cost estimated',
        ],
        checklist: [
          { text: 'Review product specifications against factory capabilities and equipment', required: true },
          { text: 'Identify required raw materials and check current stock or supplier availability', required: true },
          { text: 'Estimate production time per unit and total lead time for requested quantity', required: true },
          { text: 'Calculate bill of materials (BOM) cost in Naira', required: true },
          { text: 'Identify any tooling, moulds, or dies needed (and associated setup costs)', required: true },
          { text: 'Flag any specifications that cannot be met and propose alternatives to sales team', required: true },
          { text: 'Estimate quality control requirements and testing procedures', required: false },
        ],
        sla_hint: '2 business days',
      },
      {
        name: 'Quotation Sent',
        color: '#EC4899',
        position: 3,
        purpose: 'Formal quotation with pricing and terms shared with buyer',
        owner_role: 'Sales Manager',
        entry_criteria: [
          'Technical review completed',
          'Production cost estimated',
        ],
        exit_criteria: [
          'Quotation accepted by buyer',
          'Terms and conditions agreed',
        ],
        checklist: [
          { text: 'Prepare quotation with: unit price, total price, MOQ, lead time, payment terms in Naira', required: true },
          { text: 'Include tooling or setup costs separately if applicable', required: true },
          { text: 'Specify payment terms: 50% deposit to start production, 50% before dispatch', required: true },
          { text: 'Include delivery terms: ex-factory, delivered to buyer location, or FOB for exports', required: true },
          { text: 'Set quotation validity period (typically 14-30 days)', required: true },
          { text: 'Send quotation via email with WhatsApp notification to buyer', required: true },
          { text: 'Follow up within 5 business days if no response received', required: true },
        ],
        sla_hint: '3 business days after technical review',
      },
      {
        name: 'Sample Approval',
        color: '#F59E0B',
        position: 4,
        purpose: 'Produce and get buyer approval on product sample before bulk production',
        owner_role: 'Production / Quality Control',
        entry_criteria: [
          'Quotation accepted by buyer',
          'Sample production requested or required',
        ],
        exit_criteria: [
          'Sample produced and sent to buyer',
          'Buyer has approved sample for bulk production',
        ],
        checklist: [
          { text: 'Produce sample unit(s) matching agreed specifications exactly', required: true },
          { text: 'Conduct internal quality check on sample before sending to buyer', required: true },
          { text: 'Send sample to buyer via courier with tracking number', required: true },
          { text: 'Include sample evaluation form for buyer to document feedback', required: false },
          { text: 'Follow up with buyer within 5 days for sample feedback', required: true },
          { text: 'If revisions needed, document changes and produce revised sample', required: true },
          { text: 'Obtain written sample approval from buyer before proceeding to bulk production', required: true },
        ],
        sla_hint: '5-10 business days',
      },
      {
        name: 'Purchase Order',
        color: '#3B82F6',
        position: 5,
        purpose: 'Formal purchase order received and deposit collected',
        owner_role: 'Sales / Finance',
        entry_criteria: [
          'Sample approved by buyer',
          'Buyer ready to place bulk order',
        ],
        exit_criteria: [
          'Purchase order received',
          'Deposit payment verified',
          'Production scheduled',
        ],
        checklist: [
          { text: 'Receive formal purchase order with quantity, specifications, delivery date, and price', required: true },
          { text: 'Verify PO details match approved quotation and sample specifications', required: true },
          { text: 'Collect deposit payment (minimum 50%) and verify bank transfer receipt', required: true },
          { text: 'Issue deposit receipt and order acknowledgement to buyer', required: true },
          { text: 'Schedule production slot with factory floor and confirm lead time', required: true },
          { text: 'Order raw materials if not in stock (confirm supplier delivery timeline)', required: true },
        ],
        sla_hint: '2 business days to process',
      },
      {
        name: 'Production',
        color: '#10B981',
        position: 6,
        purpose: 'Bulk production in progress with quality monitoring',
        owner_role: 'Production Manager',
        entry_criteria: [
          'Purchase order confirmed with deposit',
          'Raw materials available',
          'Production slot scheduled',
        ],
        exit_criteria: [
          'Production completed',
          'Quality control passed',
          'Goods ready for packaging and dispatch',
        ],
        checklist: [
          { text: 'Verify all raw materials are available and meet quality standards before starting', required: true },
          { text: 'Begin production per approved specifications and sample', required: true },
          { text: 'Conduct in-process quality checks at key production stages', required: true },
          { text: 'Send production progress update to buyer at 50% completion', required: true },
          { text: 'Conduct final quality control inspection on completed batch', required: true },
          { text: 'Document any deviations from specification and get buyer approval if needed', required: true },
          { text: 'Package finished goods per buyer requirements with proper labelling', required: true },
        ],
        sla_hint: 'Per agreed lead time (typically 2-6 weeks)',
      },
      {
        name: 'Delivery',
        color: '#059669',
        position: 7,
        purpose: 'Finished goods dispatched and delivered to buyer',
        owner_role: 'Logistics / Sales',
        entry_criteria: [
          'Production completed and QC passed',
          'Balance payment received or COD arranged',
        ],
        exit_criteria: [
          'Goods delivered to buyer',
          'Delivery confirmed and accepted',
          'Full payment received',
          'Deal closed in CRM',
        ],
        checklist: [
          { text: 'Collect balance payment (remaining 50%) before dispatch', required: true },
          { text: 'Arrange transport: own truck, hired truck, or buyer-arranged pickup', required: true },
          { text: 'Prepare delivery documents: waybill, packing list, delivery note, invoice', required: true },
          { text: 'Take photos of loaded goods for documentation', required: true },
          { text: 'Share driver details and estimated arrival time with buyer via WhatsApp', required: true },
          { text: 'Confirm delivery with buyer: quantity correct, quality acceptable, no damage', required: true },
          { text: 'Issue final receipt and close deal in CRM with total revenue', required: true },
          { text: 'Ask buyer about next order requirements and schedule follow-up', required: false },
        ],
        sla_hint: '1-5 days depending on distance',
      },
    ],
  },
  suggested_flows: ['welcome_menu', 'product_enquiry', 'payment_confirmation_flow', 'delivery_tracking_flow', 'complaint_resolution_flow'],
  suggested_automations: [
    { slug: 'welcome_message', priority: 'essential', description: 'Auto-greet buyers with product catalogue and MOQ information' },
    { slug: 'payment_reminder', priority: 'essential', description: 'Remind buyers of outstanding balance before dispatch' },
    { slug: 'delivery_notification', priority: 'essential', description: 'Notify buyer when goods are dispatched with tracking details' },
    { slug: 'follow_up_reminder', priority: 'recommended', description: 'Follow up with buyer 30 days after delivery for reorder' },
    { slug: 'vip_alert', priority: 'recommended', description: 'Alert sales manager when high-volume buyer sends enquiry' },
    { slug: 'dormant_reactivation', priority: 'optional', description: 'Re-engage buyers who have not ordered in 90+ days' },
  ],
  suggested_segments: ['high_value_customers', 'repeat_buyers', 'active_last_30', 'pending_payments', 'dormant_60_plus', 'new_contacts_7d'],
  customization_hints: [
    'Add your product catalogue with specifications, MOQs, and lead times',
    'Configure standard payment terms for different buyer categories',
    'Set up production capacity alerts to avoid over-committing on delivery dates',
    'Add quality control checklist templates for your specific products',
    'Configure automated production progress updates at key milestones',
  ],
}

// ============================================================
// MANUFACTURING — Production Pipeline
// ============================================================
export const MANUFACTURING_PRODUCTION_BUNDLE: IndustryWorkflowBundle = {
  id: 'manufacturing-production',
  industry: 'Manufacturing',
  process: 'operations',
  name: 'Manufacturing Production Pipeline',
  description: 'Internal production tracking pipeline from production order through material check, manufacturing, quality control, packaging, and dispatch.',
  icon: '⚙️',
  setup_time_minutes: 12,
  pipeline: {
    id: 'manufacturing-production-pipeline',
    name: 'Production Tracking',
    icon: '⚙️',
    description: 'Production order to dispatch',
    category: 'operations',
    stages: [
      {
        name: 'Production Order',
        color: '#6366F1',
        position: 1,
        purpose: 'Internal production order created from confirmed sales order',
        owner_role: 'Production Planner',
        entry_criteria: [
          'Sales order confirmed with deposit',
          'Specifications and quantity finalised',
        ],
        exit_criteria: [
          'Production order created with all specifications',
          'Production slot assigned on schedule',
        ],
        checklist: [
          { text: 'Create production order with: product, quantity, specifications, deadline', required: true },
          { text: 'Attach approved sample reference or technical drawing', required: true },
          { text: 'Assign production to specific machine line or work station', required: true },
          { text: 'Calculate raw material requirements from bill of materials (BOM)', required: true },
          { text: 'Set production start date and estimated completion date', required: true },
        ],
        sla_hint: '4 business hours',
      },
      {
        name: 'Material Check',
        color: '#8B5CF6',
        position: 2,
        purpose: 'Verify all raw materials are available for production',
        owner_role: 'Store Keeper / Procurement',
        entry_criteria: [
          'Production order created',
          'BOM calculated',
        ],
        exit_criteria: [
          'All materials available and issued to production floor',
          'Any shortages resolved through procurement',
        ],
        checklist: [
          { text: 'Check inventory for all required raw materials against BOM quantities', required: true },
          { text: 'If materials in stock, issue materials to production floor with material issue note', required: true },
          { text: 'If materials short, raise purchase requisition with procurement team', required: true },
          { text: 'Verify material quality: check batch numbers, expiry dates, supplier certificates', required: true },
          { text: 'Record material lot numbers for traceability', required: true },
          { text: 'Confirm material availability date if procurement needed (update production schedule)', required: true },
        ],
        sla_hint: '1 business day',
      },
      {
        name: 'In Production',
        color: '#F59E0B',
        position: 3,
        purpose: 'Manufacturing in progress on factory floor',
        owner_role: 'Production Supervisor',
        entry_criteria: [
          'All materials issued to production floor',
          'Machine/line available and set up',
        ],
        exit_criteria: [
          'Production run completed',
          'Output quantity recorded',
          'Ready for quality control',
        ],
        checklist: [
          { text: 'Set up machine/line per product specifications (tooling, moulds, settings)', required: true },
          { text: 'Run first-piece inspection before full production run', required: true },
          { text: 'Monitor production run for consistency: dimensions, weight, appearance', required: true },
          { text: 'Record production output: good units, rejected units, scrap', required: true },
          { text: 'Log any machine downtime, material issues, or specification deviations', required: true },
          { text: 'Ensure NAFDAC/SON compliance steps followed if applicable', required: false },
          { text: 'Clean and maintain equipment after production run', required: true },
        ],
        sla_hint: 'Per production schedule',
      },
      {
        name: 'Quality Control',
        color: '#10B981',
        position: 4,
        purpose: 'Inspect finished goods against specifications and quality standards',
        owner_role: 'Quality Control Officer',
        entry_criteria: [
          'Production run completed',
          'Goods moved to QC inspection area',
        ],
        exit_criteria: [
          'QC inspection completed',
          'Goods approved or rejected with documented reasons',
        ],
        checklist: [
          { text: 'Inspect sample from batch per AQL (Acceptable Quality Level) standards', required: true },
          { text: 'Check dimensions, weight, colour, finish against approved specifications', required: true },
          { text: 'Conduct functional testing if applicable (strength, durability, performance)', required: true },
          { text: 'Document inspection results with pass/fail for each parameter', required: true },
          { text: 'If batch fails QC, document defects and route back to production for rework', required: true },
          { text: 'Issue QC approval certificate for passed batch', required: true },
          { text: 'Take photos of finished product for buyer pre-dispatch approval if required', required: false },
        ],
        sla_hint: '1 business day',
      },
      {
        name: 'Packaging',
        color: '#3B82F6',
        position: 5,
        purpose: 'Package finished goods per buyer requirements for dispatch',
        owner_role: 'Packaging / Warehouse',
        entry_criteria: [
          'QC approved',
          'Packaging materials available',
        ],
        exit_criteria: [
          'All goods packaged and labelled',
          'Ready for dispatch',
        ],
        checklist: [
          { text: 'Package goods per buyer specifications: cartons, pallets, shrink wrap, custom packaging', required: true },
          { text: 'Label each package with: product name, quantity, batch number, date, buyer reference', required: true },
          { text: 'Include required documentation inside packaging: QC certificate, user manual, warranty card', required: false },
          { text: 'Weigh and count all packages, record total package count and gross weight', required: true },
          { text: 'Move packaged goods to dispatch area and update inventory', required: true },
          { text: 'Notify sales team that goods are ready for dispatch', required: true },
        ],
        sla_hint: '1 business day',
      },
      {
        name: 'Dispatched',
        color: '#059669',
        position: 6,
        purpose: 'Goods loaded and dispatched to buyer or pickup completed',
        owner_role: 'Logistics / Dispatch',
        entry_criteria: [
          'Goods packaged and in dispatch area',
          'Balance payment confirmed by finance',
          'Transport arranged',
        ],
        exit_criteria: [
          'Goods loaded and departed',
          'Delivery confirmed by buyer',
          'Production order closed',
        ],
        checklist: [
          { text: 'Verify balance payment received before loading (confirm with finance)', required: true },
          { text: 'Load goods onto truck with supervision, count packages against packing list', required: true },
          { text: 'Issue waybill and delivery note to driver', required: true },
          { text: 'Take photos of loaded truck for documentation', required: true },
          { text: 'Share driver details and ETA with buyer via WhatsApp', required: true },
          { text: 'Track delivery and confirm receipt with buyer', required: true },
          { text: 'Close production order in system with final output and yield data', required: true },
        ],
        sla_hint: '1-5 days for delivery',
      },
    ],
  },
  suggested_flows: ['delivery_tracking_flow', 'payment_confirmation_flow', 'complaint_resolution_flow'],
  suggested_automations: [
    { slug: 'delivery_notification', priority: 'essential', description: 'Notify buyer when goods are dispatched' },
    { slug: 'payment_reminder', priority: 'essential', description: 'Remind finance to confirm balance before dispatch' },
    { slug: 'overdue_payment_escalation', priority: 'recommended', description: 'Escalate if production is delayed beyond scheduled date' },
    { slug: 'new_enquiry_auto_assign', priority: 'recommended', description: 'Auto-assign production orders to available production lines' },
    { slug: 'review_request', priority: 'optional', description: 'Request buyer feedback after delivery' },
  ],
  suggested_segments: ['pending_payments', 'high_value_customers', 'repeat_buyers', 'active_last_30'],
  customization_hints: [
    'Add your specific product lines and standard specifications',
    'Configure production capacity per machine line for scheduling',
    'Set up standard BOM templates for your most common products',
    'Add quality control parameter templates for each product type',
    'Configure lead time estimates based on your actual production capacity',
  ],
}
