import type { IndustryWorkflowBundle } from '../types'

// ============================================================
// PROFESSIONAL SERVICES — Sales Pipeline
// ============================================================
export const PROFESSIONAL_SERVICES_SALES_BUNDLE: IndustryWorkflowBundle = {
  id: 'professional-services-sales',
  industry: 'Professional Services',
  process: 'sales',
  name: 'Professional Services Sales Pipeline',
  description: 'Consultative sales pipeline for law firms, accounting practices, consulting agencies, and other professional service providers in Nigeria.',
  icon: '💼',
  setup_time_minutes: 15,
  pipeline: {
    id: 'professional-services-sales-pipeline',
    name: 'Professional Services Sales',
    icon: '💼',
    description: 'Lead to signed retainer',
    category: 'sales',
    stages: [
      {
        name: 'Initial Contact',
        color: '#6366F1',
        position: 1,
        purpose: 'Capture inbound lead and establish first communication',
        owner_role: 'Business Development',
        entry_criteria: [
          'Prospect has reached out via WhatsApp, email, website, or referral',
          'Basic contact information available',
        ],
        exit_criteria: [
          'Contact record created in CRM with full details',
          'Initial response sent within SLA',
          'Discovery call scheduled or needs assessment initiated',
        ],
        checklist: [
          { text: 'Record prospect name, company, phone number, and email address', required: true },
          { text: 'Identify how prospect found you: referral, Google, social media, or existing relationship', required: true },
          { text: 'Capture initial enquiry: what service do they need and what problem are they trying to solve', required: true },
          { text: 'Send acknowledgement message within 2 hours with your firm profile or capability statement', required: true },
          { text: 'Check for potential conflicts of interest (especially for law firms)', required: false },
          { text: 'Schedule discovery call or meeting within 3 business days', required: true },
        ],
        sla_hint: '2 business hours',
      },
      {
        name: 'Discovery Call',
        color: '#8B5CF6',
        position: 2,
        purpose: 'Conduct initial consultation to understand client needs and assess fit',
        owner_role: 'Senior Consultant / Partner',
        entry_criteria: [
          'Discovery call or meeting scheduled',
          'Prospect has confirmed attendance',
        ],
        exit_criteria: [
          'Client needs clearly documented',
          'Scope of work broadly defined',
          'Decision-maker identified',
        ],
        checklist: [
          { text: 'Send meeting reminder via WhatsApp 24 hours before scheduled call', required: true },
          { text: 'Prepare by reviewing prospect company background and industry', required: true },
          { text: 'During call: document specific challenges, goals, and desired outcomes', required: true },
          { text: 'Identify decision-maker and budget authority (is this person the final approver?)', required: true },
          { text: 'Discuss timeline expectations and any regulatory deadlines', required: true },
          { text: 'Send call summary and next steps via WhatsApp or email within 4 hours', required: true },
        ],
        sla_hint: '3 business days from initial contact',
      },
      {
        name: 'Needs Assessment',
        color: '#EC4899',
        position: 3,
        purpose: 'Deep-dive analysis of client requirements to prepare accurate proposal',
        owner_role: 'Senior Consultant',
        entry_criteria: [
          'Discovery call completed',
          'Client has agreed to proceed with detailed assessment',
        ],
        exit_criteria: [
          'Detailed scope of work documented',
          'Resource requirements estimated',
          'Pricing model determined (fixed fee, hourly, retainer)',
        ],
        checklist: [
          { text: 'Request relevant documents from client: financial statements, contracts, company registration (CAC), TIN', required: true },
          { text: 'Conduct detailed analysis of client situation and requirements', required: true },
          { text: 'Identify specific deliverables and milestones for the engagement', required: true },
          { text: 'Estimate hours and resources needed for each deliverable', required: true },
          { text: 'Determine pricing model: fixed project fee, hourly rate, monthly retainer, or success-based', required: true },
          { text: 'Identify any third-party costs: filing fees, regulatory charges, travel expenses', required: false },
        ],
        sla_hint: '5 business days',
      },
      {
        name: 'Proposal Sent',
        color: '#F59E0B',
        position: 4,
        purpose: 'Formal proposal or engagement letter shared with client for review',
        owner_role: 'Senior Consultant / Partner',
        entry_criteria: [
          'Needs assessment completed',
          'Pricing approved internally',
        ],
        exit_criteria: [
          'Client has received and acknowledged the proposal',
          'Client feedback or questions addressed',
        ],
        checklist: [
          { text: 'Prepare professional proposal with: executive summary, scope, deliverables, timeline, and fees in Naira', required: true },
          { text: 'Include payment terms: deposit percentage, milestone payments, or monthly retainer amount', required: true },
          { text: 'Include terms and conditions: confidentiality, liability limitations, termination clause', required: true },
          { text: 'Send proposal via email with WhatsApp notification that proposal has been sent', required: true },
          { text: 'Schedule follow-up call 3 days after sending if no response', required: true },
          { text: 'Address any client questions or requested modifications promptly', required: true },
        ],
        sla_hint: '3 business days to prepare, 5 days for client review',
      },
      {
        name: 'Contract Review',
        color: '#10B981',
        position: 5,
        purpose: 'Finalise engagement terms and prepare contract for signing',
        owner_role: 'Partner / Legal',
        entry_criteria: [
          'Client has verbally accepted the proposal or requested final terms',
          'Any negotiated changes agreed upon',
        ],
        exit_criteria: [
          'Engagement letter or contract signed by both parties',
          'Initial payment terms agreed',
        ],
        checklist: [
          { text: 'Prepare formal engagement letter or service agreement incorporating agreed terms', required: true },
          { text: 'Include specific deliverables, deadlines, and acceptance criteria', required: true },
          { text: 'Specify payment schedule: retainer amount, billing cycle, payment method (bank transfer)', required: true },
          { text: 'Include dispute resolution mechanism and governing law (Nigerian law)', required: true },
          { text: 'Send contract for client review and signature', required: true },
          { text: 'Allow 5 business days for client legal review', required: false },
        ],
        sla_hint: '5 business days',
      },
      {
        name: 'Retainer Signed',
        color: '#059669',
        position: 6,
        purpose: 'Engagement confirmed, initial payment received, ready for project kickoff',
        owner_role: 'Partner / Business Development',
        entry_criteria: [
          'Contract signed by both parties',
          'Initial payment or retainer received',
        ],
        exit_criteria: [
          'Payment verified',
          'Project team assigned',
          'Kickoff meeting scheduled',
          'Deal marked as Won in CRM',
        ],
        checklist: [
          { text: 'Verify initial payment or retainer deposit received in firm bank account', required: true },
          { text: 'Issue official receipt and engagement confirmation letter', required: true },
          { text: 'Assign project team: lead consultant, support staff, and partner oversight', required: true },
          { text: 'Schedule kickoff meeting with client within 5 business days', required: true },
          { text: 'Set up client folder with all documents: contract, proposal, correspondence', required: true },
          { text: 'Update deal as Won in CRM with engagement value and expected duration', required: true },
          { text: 'Send welcome pack with team contacts, communication protocols, and project timeline', required: true },
        ],
        sla_hint: '3 business days after signing',
      },
    ],
  },
  suggested_flows: ['welcome_menu', 'appointment_booking_flow', 'lead_capture', 'feedback_collector', 'payment_confirmation_flow'],
  suggested_automations: [
    { slug: 'welcome_message', priority: 'essential', description: 'Auto-greet new enquiries with firm profile and service overview' },
    { slug: 'follow_up_reminder', priority: 'essential', description: 'Follow up on proposals not responded to within 5 days' },
    { slug: 'appointment_reminder_24h', priority: 'essential', description: 'Remind clients 24 hours before scheduled consultations' },
    { slug: 'payment_reminder', priority: 'recommended', description: 'Remind clients of outstanding retainer or milestone payments' },
    { slug: 'new_enquiry_auto_assign', priority: 'recommended', description: 'Auto-assign new enquiries to available consultants round-robin' },
    { slug: 'vip_alert', priority: 'optional', description: 'Alert partner when high-value prospect enquires' },
  ],
  suggested_segments: ['active_last_30', 'high_value_customers', 'pending_payments', 'new_contacts_7d', 'dormant_60_plus', 'referral_sources'],
  customization_hints: [
    'Add your specific service lines as tags (tax advisory, litigation, audit, HR consulting)',
    'Configure proposal templates for your most common engagement types',
    'Set up partner approval workflow for proposals above a certain value threshold',
    'Add your firm bank account details to payment confirmation templates',
    'Customise discovery call agenda template for your practice area',
  ],
}

// ============================================================
// PROFESSIONAL SERVICES — Project Delivery Pipeline
// ============================================================
export const PROFESSIONAL_SERVICES_DELIVERY_BUNDLE: IndustryWorkflowBundle = {
  id: 'professional-services-delivery',
  industry: 'Professional Services',
  process: 'operations',
  name: 'Professional Services Delivery Pipeline',
  description: 'Project delivery pipeline tracking engagements from kickoff through execution, client review, and final delivery with milestone-based billing.',
  icon: '📋',
  setup_time_minutes: 15,
  pipeline: {
    id: 'professional-services-delivery-pipeline',
    name: 'Project Delivery',
    icon: '📋',
    description: 'Project kickoff to delivery and invoicing',
    category: 'operations',
    stages: [
      {
        name: 'Kickoff',
        color: '#6366F1',
        position: 1,
        purpose: 'Formally launch the engagement with client alignment meeting',
        owner_role: 'Project Lead',
        entry_criteria: [
          'Contract signed and initial payment received',
          'Project team assigned',
        ],
        exit_criteria: [
          'Kickoff meeting completed',
          'Project plan shared with client',
          'Communication protocols established',
        ],
        checklist: [
          { text: 'Conduct kickoff meeting with client stakeholders and project team', required: true },
          { text: 'Review scope, deliverables, timeline, and milestones with client', required: true },
          { text: 'Establish communication protocol: primary contact, update frequency, preferred channel (WhatsApp/email)', required: true },
          { text: 'Request all necessary documents and access from client', required: true },
          { text: 'Share project plan with milestones and deadlines', required: true },
          { text: 'Set up shared folder or document repository for the engagement', required: true },
        ],
        sla_hint: '5 business days after contract signing',
      },
      {
        name: 'Discovery',
        color: '#8B5CF6',
        position: 2,
        purpose: 'Gather all information and data needed for the engagement',
        owner_role: 'Project Lead / Analyst',
        entry_criteria: [
          'Kickoff completed',
          'Client has agreed to provide required information',
        ],
        exit_criteria: [
          'All required documents and data received from client',
          'Initial analysis completed',
          'Findings documented for team review',
        ],
        checklist: [
          { text: 'Send formal document request list to client with deadlines for each item', required: true },
          { text: 'Follow up on outstanding documents every 48 hours', required: true },
          { text: 'Review all received documents for completeness and accuracy', required: true },
          { text: 'Conduct stakeholder interviews if required by engagement scope', required: false },
          { text: 'Document initial findings and flag any issues or risks early', required: true },
          { text: 'Update client on discovery progress via weekly status message', required: true },
        ],
        sla_hint: '5-10 business days',
      },
      {
        name: 'In Progress',
        color: '#F59E0B',
        position: 3,
        purpose: 'Active work on deliverables by the project team',
        owner_role: 'Project Team',
        entry_criteria: [
          'Discovery phase completed',
          'All required information available',
        ],
        exit_criteria: [
          'Draft deliverables completed',
          'Internal quality review passed',
          'Ready for client review',
        ],
        checklist: [
          { text: 'Execute work plan according to agreed milestones and timeline', required: true },
          { text: 'Send weekly progress update to client via WhatsApp or email', required: true },
          { text: 'Flag any scope changes or additional requirements immediately to client', required: true },
          { text: 'Conduct internal peer review of draft deliverables before sharing with client', required: true },
          { text: 'Track time spent against budget for hourly engagements', required: true },
          { text: 'Prepare draft deliverables for client review', required: true },
        ],
        sla_hint: 'Per project plan (typically 2-8 weeks)',
      },
      {
        name: 'Client Review',
        color: '#EC4899',
        position: 4,
        purpose: 'Client reviews draft deliverables and provides feedback',
        owner_role: 'Project Lead',
        entry_criteria: [
          'Draft deliverables completed and internally reviewed',
          'Deliverables shared with client',
        ],
        exit_criteria: [
          'Client feedback received',
          'All comments and questions documented',
          'Revision scope agreed',
        ],
        checklist: [
          { text: 'Send draft deliverables to client with clear review instructions and deadline', required: true },
          { text: 'Schedule review meeting if deliverables are complex or require walkthrough', required: false },
          { text: 'Follow up if no feedback received within agreed review period', required: true },
          { text: 'Document all client feedback, comments, and change requests', required: true },
          { text: 'Assess if requested changes are within original scope or require change order', required: true },
          { text: 'If out of scope, prepare change order with additional fees for client approval', required: false },
        ],
        sla_hint: '5 business days for client review',
      },
      {
        name: 'Revision',
        color: '#3B82F6',
        position: 5,
        purpose: 'Incorporate client feedback and finalise deliverables',
        owner_role: 'Project Team',
        entry_criteria: [
          'Client feedback received and documented',
          'Revision scope agreed (within scope or change order approved)',
        ],
        exit_criteria: [
          'All revisions completed',
          'Final deliverables approved by client',
        ],
        checklist: [
          { text: 'Address each client comment and change request systematically', required: true },
          { text: 'Conduct internal review of revised deliverables', required: true },
          { text: 'Send revised deliverables to client with summary of changes made', required: true },
          { text: 'Obtain formal client approval or sign-off on final deliverables', required: true },
          { text: 'If additional revision rounds needed, agree timeline and manage expectations', required: false },
        ],
        sla_hint: '3-5 business days',
      },
      {
        name: 'Delivered & Invoiced',
        color: '#059669',
        position: 6,
        purpose: 'Final deliverables handed over, invoice issued, engagement closed',
        owner_role: 'Project Lead / Finance',
        entry_criteria: [
          'Client has approved final deliverables',
          'All engagement work completed',
        ],
        exit_criteria: [
          'Final deliverables formally handed over',
          'Invoice issued and payment received',
          'Engagement closed in CRM',
        ],
        checklist: [
          { text: 'Prepare final deliverable package with all documents, reports, and supporting materials', required: true },
          { text: 'Send formal handover email with deliverable list and any implementation recommendations', required: true },
          { text: 'Issue final invoice with detailed breakdown of services rendered', required: true },
          { text: 'Include bank account details for payment and set payment due date (typically 14-30 days)', required: true },
          { text: 'Follow up on payment if not received within due date', required: true },
          { text: 'Request client testimonial or referral after successful engagement', required: false },
          { text: 'Conduct internal project debrief: lessons learned, profitability analysis', required: true },
          { text: 'Update CRM: mark deal as completed with final revenue and close date', required: true },
        ],
        sla_hint: '5 business days for invoicing, 14-30 days payment terms',
      },
    ],
  },
  suggested_flows: ['feedback_collector', 'payment_confirmation_flow', 'complaint_resolution_flow', 'appointment_booking_flow'],
  suggested_automations: [
    { slug: 'payment_reminder', priority: 'essential', description: 'Remind clients of outstanding invoices at 7, 14, and 30 days' },
    { slug: 'appointment_reminder_24h', priority: 'essential', description: 'Remind clients 24 hours before scheduled meetings' },
    { slug: 'overdue_payment_escalation', priority: 'recommended', description: 'Escalate overdue invoices to partner after 30 days' },
    { slug: 'review_request', priority: 'recommended', description: 'Request testimonial 7 days after project completion' },
    { slug: 'follow_up_reminder', priority: 'optional', description: 'Schedule quarterly check-in with past clients for repeat business' },
  ],
  suggested_segments: ['high_value_customers', 'pending_payments', 'active_last_30', 'repeat_buyers', 'referral_sources', 'dormant_60_plus'],
  customization_hints: [
    'Set up milestone-based billing triggers aligned with your project stages',
    'Configure weekly status update templates for different engagement types',
    'Add your standard terms and conditions to proposal templates',
    'Set up partner approval gates for deliverables above certain value thresholds',
    'Create engagement type tags for better reporting (audit, advisory, litigation, etc.)',
  ],
}
