import type { IndustryWorkflowBundle, SetupAction } from '../types'

// ============================================================
// REAL ESTATE — Sales Pipeline
// ============================================================
export const REAL_ESTATE_SALES_BUNDLE: IndustryWorkflowBundle = {
  id: 'real-estate-sales',
  industry: 'Real Estate',
  process: 'sales',
  name: 'Real Estate Sales Pipeline',
  description: 'Property sales from initial enquiry through site visits, documentation, payment plans, and closing with Nigerian land registry compliance.',
  icon: '🏠',
  setup_time_minutes: 20,
  pipeline: {
    id: 'real-estate-sales-pipeline',
    name: 'Property Sales',
    icon: '🏠',
    description: 'Property enquiry to closing and handover',
    category: 'sales',
    stages: [
      {
        name: 'Enquiry',
        color: '#6366F1',
        position: 1,
        purpose: 'Capture property interest and qualify buyer budget, location preference, and timeline',
        owner_role: 'Sales Agent',
        entry_criteria: [
          'Prospect has contacted via WhatsApp, website form, or referral',
          'Basic contact information captured',
        ],
        exit_criteria: [
          'Budget range confirmed',
          'Preferred location and property type identified',
          'At least one matching property identified for viewing',
        ],
        checklist: [
          { text: 'Record prospect full name, phone number, and email address', required: true },
          { text: 'Ask budget range in Naira (e.g., ₦20M-₦50M for Lagos mainland)', required: true },
          { text: 'Confirm preferred location: state, LGA, and specific area or estate', required: true },
          { text: 'Identify property type: land, flat, duplex, semi-detached, detached, commercial', required: true },
          { text: 'Ask timeline: immediate purchase, 3 months, 6 months, or just exploring', required: true },
          { text: 'Check if prospect needs mortgage or will pay outright/installment', required: false },
          { text: 'Send initial property brochure or listing photos via WhatsApp', required: true },
        ],
        sla_hint: '2 business hours',
      },
      {
        name: 'Site Visit Scheduled',
        color: '#8B5CF6',
        position: 2,
        purpose: 'Arrange physical property inspection with prospect',
        owner_role: 'Sales Agent',
        entry_criteria: [
          'Prospect has expressed interest in at least one property',
          'Budget aligns with available properties',
        ],
        exit_criteria: [
          'Site visit date and time confirmed with prospect',
          'Property access arranged with estate or developer',
        ],
        checklist: [
          { text: 'Propose 2-3 available dates and times for site visit', required: true },
          { text: 'Confirm exact property address and share Google Maps pin via WhatsApp', required: true },
          { text: 'Arrange access with estate security or developer site office', required: true },
          { text: 'Prepare property fact sheet: size (sqm), title document type, amenities, estate fees', required: true },
          { text: 'Send visit confirmation message with date, time, address, and your phone number', required: true },
          { text: 'Remind prospect 24 hours before scheduled visit via WhatsApp', required: true },
        ],
        sla_hint: '24 hours to schedule, visit within 5 business days',
      },
      {
        name: 'Site Visit Done',
        color: '#EC4899',
        position: 3,
        purpose: 'Post-visit follow-up to gauge interest and address concerns',
        owner_role: 'Sales Agent',
        entry_criteria: [
          'Prospect has physically visited the property',
          'Agent was present during the visit',
        ],
        exit_criteria: [
          'Prospect feedback collected',
          'Prospect has indicated interest to proceed or requested alternatives',
        ],
        checklist: [
          { text: 'Send thank-you message within 2 hours of visit completion', required: true },
          { text: 'Ask prospect for feedback: what they liked, concerns, and questions', required: true },
          { text: 'Address any concerns about the property (flooding, road access, security, title)', required: true },
          { text: 'If prospect wants alternatives, identify and share 2-3 similar properties', required: false },
          { text: 'Share neighbourhood information: schools, hospitals, markets, transport links', required: false },
          { text: 'Ask if prospect is ready to make an offer or needs more time', required: true },
        ],
        sla_hint: '24 hours after visit',
      },
      {
        name: 'Offer Made',
        color: '#F59E0B',
        position: 4,
        purpose: 'Prospect has made a formal or verbal offer on the property',
        owner_role: 'Sales Agent / Sales Manager',
        entry_criteria: [
          'Prospect has indicated willingness to purchase',
          'Offer amount communicated (may differ from asking price)',
        ],
        exit_criteria: [
          'Offer accepted by seller/developer',
          'Both parties agree on price and payment terms',
        ],
        checklist: [
          { text: 'Record offer amount and compare with asking price', required: true },
          { text: 'Present offer to property owner or developer with prospect profile', required: true },
          { text: 'Negotiate if offer is below asking price (typical range: 5-15% below asking in Lagos)', required: false },
          { text: 'Confirm payment structure: outright, installment plan, or mortgage', required: true },
          { text: 'If installment, agree on deposit amount (typically 30-50%), duration, and schedule', required: true },
          { text: 'Get written acceptance from seller/developer', required: true },
          { text: 'Communicate acceptance to prospect and outline next steps', required: true },
        ],
        sla_hint: '3 business days',
      },
      {
        name: 'Documentation',
        color: '#10B981',
        position: 5,
        purpose: 'Legal documentation, title verification, and contract preparation',
        owner_role: 'Legal / Sales Manager',
        entry_criteria: [
          'Offer accepted by both parties',
          'Payment terms agreed',
        ],
        exit_criteria: [
          'All title documents verified',
          'Sales agreement or contract of sale signed by both parties',
        ],
        checklist: [
          { text: 'Verify property title document: C of O, R of O, Governor\u2019s Consent, or Deed of Assignment', required: true },
          { text: 'Conduct search at Land Registry to confirm title is genuine and unencumbered', required: true },
          { text: 'Verify survey plan matches actual property boundaries', required: true },
          { text: 'Prepare or review Contract of Sale / Deed of Assignment with lawyer', required: true },
          { text: 'Include all agreed terms: price, payment schedule, completion date, penalties', required: true },
          { text: 'Both parties sign contract in presence of witnesses', required: true },
          { text: 'Collect signed copies and share scanned version with buyer via WhatsApp or email', required: true },
        ],
        sla_hint: '5-10 business days',
      },
      {
        name: 'Payment Plan',
        color: '#3B82F6',
        position: 6,
        purpose: 'Track payment milestones and collect funds per agreed schedule',
        owner_role: 'Finance / Sales Agent',
        entry_criteria: [
          'Contract signed by both parties',
          'Payment schedule agreed and documented',
        ],
        exit_criteria: [
          'All payments received and verified',
          'Final balance cleared',
        ],
        checklist: [
          { text: 'Set up payment schedule in CRM with due dates and amounts in Naira', required: true },
          { text: 'Collect initial deposit and verify bank transfer receipt', required: true },
          { text: 'Issue official receipt for each payment received', required: true },
          { text: 'Send payment reminder 3 days before each instalment due date', required: true },
          { text: 'Track cumulative payments against total purchase price', required: true },
          { text: 'Escalate overdue payments after 7 days with formal notice', required: true },
          { text: 'Update buyer on remaining balance after each payment', required: true },
        ],
        sla_hint: 'Per agreed schedule (typically 6-24 months)',
      },
      {
        name: 'Closed',
        color: '#059669',
        position: 7,
        purpose: 'Transaction complete, property handed over, all documents transferred',
        owner_role: 'Sales Manager / Legal',
        entry_criteria: [
          'Full payment received and verified',
          'All legal documentation complete',
        ],
        exit_criteria: [
          'Property keys or allocation letter handed to buyer',
          'Title transfer initiated or completed',
          'Deal marked as Won in CRM',
        ],
        checklist: [
          { text: 'Confirm full payment received and issue final receipt', required: true },
          { text: 'Prepare and hand over allocation letter or title documents to buyer', required: true },
          { text: 'Hand over property keys (for built properties) with inventory checklist', required: true },
          { text: 'Initiate Governor\u2019s Consent application for title transfer (if applicable)', required: true },
          { text: 'Send congratulations message and welcome pack via WhatsApp', required: true },
          { text: 'Request referral: ask buyer if they know anyone looking for property', required: false },
          { text: 'Update deal as Won in CRM with final amount and close date', required: true },
        ],
        sla_hint: '5 business days after final payment',
      },
    ],
  },
  suggested_flows: ['welcome_menu', 'property_enquiry_flow', 'feedback_collector', 'payment_confirmation_flow', 'lead_capture'],
  suggested_automations: [
    { slug: 'welcome_message', priority: 'essential', description: 'Auto-greet property enquiries with available listings summary' },
    { slug: 'follow_up_reminder', priority: 'essential', description: 'Follow up 48 hours after site visit if no response' },
    { slug: 'payment_reminder', priority: 'essential', description: 'Remind buyers 3 days before instalment due date' },
    { slug: 'overdue_payment_escalation', priority: 'recommended', description: 'Escalate overdue instalments to sales manager after 7 days' },
    { slug: 'review_request', priority: 'recommended', description: 'Request testimonial after successful property handover' },
    { slug: 'dormant_reactivation', priority: 'optional', description: 'Re-engage prospects who enquired but never visited' },
  ],
  suggested_segments: ['property_seekers', 'high_value_customers', 'pending_payments', 'active_last_30', 'dormant_60_plus', 'referral_sources'],
  setup_actions: [
    { id: 'realestate-sales-listings', title: 'Add property listing tags', description: 'Create tags for your estates and developments (e.g., Lekki Phase 1, Banana Island, Maitama) for property matching', priority: 'essential', category: 'contacts', target_url: '/contacts', target_params: { tab: 'tags' }, estimated_minutes: 5, icon: '🏘️' },
    { id: 'realestate-sales-payment-plans', title: 'Configure payment plan templates', description: 'Set up your standard instalment structures for different property price ranges', priority: 'essential', category: 'settings', target_url: '/installments', estimated_minutes: 10, icon: '💳' },
    { id: 'realestate-sales-welcome', title: 'Customise property enquiry welcome message', description: 'Edit the auto-greeting to include your available listings summary and office address', priority: 'essential', category: 'automations', target_url: '/automations/new', target_params: { template: 'welcome_message' }, estimated_minutes: 5, icon: '👋' },
    { id: 'realestate-sales-viewing', title: 'Set up site visit reminder automation', description: 'Configure reminder timing for property viewings (Lagos vs Abuja market)', priority: 'recommended', category: 'automations', target_url: '/automations/new', target_params: { template: 'appointment_reminder_24h' }, estimated_minutes: 3, icon: '📅' },
    { id: 'realestate-sales-followup', title: 'Configure post-viewing follow-up', description: 'Set the 48-hour follow-up automation for prospects who visited but have not responded', priority: 'recommended', category: 'automations', target_url: '/automations/new', target_params: { template: 'follow_up_reminder' }, estimated_minutes: 3, icon: '📞' },
    { id: 'realestate-sales-segments', title: 'Review property seeker segments', description: 'Check location-based segments for areas you cover', priority: 'optional', category: 'segments', target_url: '/segments', target_params: { template: 'property_seekers' }, estimated_minutes: 5, icon: '📊' },
  ],
  customization_hints: [
    'Add your specific estate or development names as tags for property matching',
    'Configure payment plan templates for your standard instalment structures',
    'Set up location-based segments for different areas you cover',
    'Add your lawyer and surveyor contacts for quick documentation referrals',
    'Customise site visit reminder timing based on your market (Lagos vs Abuja)',
  ],
}

// ============================================================
// REAL ESTATE — Tenant Onboarding Pipeline
// ============================================================
export const REAL_ESTATE_TENANT_BUNDLE: IndustryWorkflowBundle = {
  id: 'real-estate-tenant',
  industry: 'Real Estate',
  process: 'operations',
  name: 'Tenant Onboarding Pipeline',
  description: 'Manage tenant applications from screening through agreement signing, payment collection, and move-in for Nigerian rental properties.',
  icon: '🏢',
  setup_time_minutes: 15,
  pipeline: {
    id: 'real-estate-tenant-pipeline',
    name: 'Tenant Onboarding',
    icon: '🏢',
    description: 'Tenant application to move-in',
    category: 'operations',
    stages: [
      {
        name: 'Application',
        color: '#6366F1',
        position: 1,
        purpose: 'Receive and log tenant application with basic requirements',
        owner_role: 'Property Manager',
        entry_criteria: [
          'Prospective tenant has expressed interest in a rental property',
          'Property is available for rent',
        ],
        exit_criteria: [
          'Application form completed with all required information',
          'Tenant budget confirmed to match rental price',
        ],
        checklist: [
          { text: 'Collect tenant full name, phone number, email, and current address', required: true },
          { text: 'Confirm rental budget matches property rent (annual rent in Naira)', required: true },
          { text: 'Ask for preferred move-in date', required: true },
          { text: 'Collect employer name and work address for employed tenants', required: true },
          { text: 'Ask for guarantor details: name, phone, address, and relationship', required: true },
          { text: 'Share property details: rent amount, service charge, agency fee, caution deposit', required: true },
        ],
        sla_hint: '24 hours',
      },
      {
        name: 'Screening',
        color: '#8B5CF6',
        position: 2,
        purpose: 'Verify tenant identity, employment, and references',
        owner_role: 'Property Manager',
        entry_criteria: [
          'Application form completed',
          'Tenant has agreed to screening process',
        ],
        exit_criteria: [
          'Identity verified with valid ID',
          'Employment or income source confirmed',
          'References checked',
        ],
        checklist: [
          { text: 'Verify tenant identity with valid government ID (NIN, voter card, international passport, or driver licence)', required: true },
          { text: 'Confirm employment with employer verification call or employment letter', required: true },
          { text: 'For self-employed tenants, request CAC registration or business proof', required: true },
          { text: 'Call guarantor to confirm relationship and willingness to guarantee', required: true },
          { text: 'Check previous landlord reference if tenant is relocating', required: false },
          { text: 'Assess if tenant income can support rent (rent should not exceed 40% of income)', required: true },
        ],
        sla_hint: '3 business days',
      },
      {
        name: 'Agreement Drafting',
        color: '#EC4899',
        position: 3,
        purpose: 'Prepare tenancy agreement with all terms and conditions',
        owner_role: 'Property Manager / Legal',
        entry_criteria: [
          'Tenant screening passed',
          'Landlord has approved the tenant',
        ],
        exit_criteria: [
          'Tenancy agreement drafted and reviewed',
          'Both parties agree on all terms',
        ],
        checklist: [
          { text: 'Draft tenancy agreement with property address, rent amount, and duration (typically 1-2 years)', required: true },
          { text: 'Include all charges: annual rent, service charge, agency fee (typically 10% of rent), legal fee, caution deposit', required: true },
          { text: 'Specify payment terms: full year upfront or agreed instalment structure', required: true },
          { text: 'Include house rules: maintenance responsibilities, noise policy, pet policy, subletting restrictions', required: true },
          { text: 'Add termination clause with notice period (typically 3-6 months)', required: true },
          { text: 'Share draft agreement with tenant for review via WhatsApp or email', required: true },
          { text: 'Address any tenant questions or requested amendments', required: false },
        ],
        sla_hint: '3 business days',
      },
      {
        name: 'Payment',
        color: '#F59E0B',
        position: 4,
        purpose: 'Collect all required payments before move-in',
        owner_role: 'Finance / Property Manager',
        entry_criteria: [
          'Tenancy agreement agreed by both parties',
          'Payment breakdown shared with tenant',
        ],
        exit_criteria: [
          'All payments received and verified',
          'Receipts issued for all payments',
        ],
        checklist: [
          { text: 'Share payment breakdown: rent + service charge + agency fee + legal fee + caution deposit', required: true },
          { text: 'Provide bank account details for transfer payment', required: true },
          { text: 'Verify each payment as it comes in against bank statement', required: true },
          { text: 'Issue official receipt for rent payment', required: true },
          { text: 'Issue separate receipts for agency fee, legal fee, and caution deposit', required: true },
          { text: 'Confirm total amount received matches total due', required: true },
        ],
        sla_hint: '5 business days',
      },
      {
        name: 'Move-in Preparation',
        color: '#10B981',
        position: 5,
        purpose: 'Prepare property for tenant and complete all pre-move-in tasks',
        owner_role: 'Property Manager',
        entry_criteria: [
          'All payments received and verified',
          'Tenancy agreement signed by both parties',
        ],
        exit_criteria: [
          'Property cleaned and ready for occupancy',
          'Keys and access arranged',
        ],
        checklist: [
          { text: 'Sign tenancy agreement with tenant, landlord, and witnesses', required: true },
          { text: 'Conduct property inspection with tenant and document condition with photos', required: true },
          { text: 'Ensure all utilities are functional: electricity (prepaid meter), water, gas', required: true },
          { text: 'Arrange professional cleaning of property before handover', required: true },
          { text: 'Prepare keys: main door, room keys, gate remote, mailbox key', required: true },
          { text: 'Introduce tenant to estate management or facility manager', required: false },
          { text: 'Share emergency contacts: plumber, electrician, estate security', required: true },
        ],
        sla_hint: '3 business days',
      },
      {
        name: 'Tenant Active',
        color: '#059669',
        position: 6,
        purpose: 'Tenant has moved in, ongoing relationship management',
        owner_role: 'Property Manager',
        entry_criteria: [
          'Tenant has received keys and moved in',
          'All documentation complete',
        ],
        exit_criteria: [
          'Tenant settled and no outstanding issues',
          'Renewal reminder set for 3 months before lease expiry',
        ],
        checklist: [
          { text: 'Send welcome message with property management contact details', required: true },
          { text: 'Follow up after 1 week to check if tenant has any issues', required: true },
          { text: 'Set renewal reminder for 3 months before tenancy expiry date', required: true },
          { text: 'Add tenant to property WhatsApp group if applicable', required: false },
          { text: 'File all signed documents: agreement, receipts, ID copies, guarantor form', required: true },
          { text: 'Update CRM with tenancy start date, end date, and rent amount', required: true },
        ],
        sla_hint: '7 days post move-in',
      },
    ],
  },
  suggested_flows: ['welcome_menu', 'tenant_application_flow', 'payment_confirmation_flow', 'complaint_resolution_flow', 'feedback_collector'],
  suggested_automations: [
    { slug: 'welcome_message', priority: 'essential', description: 'Auto-greet rental enquiries with available properties' },
    { slug: 'payment_reminder', priority: 'essential', description: 'Remind tenants of upcoming rent payments' },
    { slug: 'follow_up_reminder', priority: 'recommended', description: 'Follow up on applications not completed within 48 hours' },
    { slug: 'booking_confirmation', priority: 'recommended', description: 'Confirm viewing appointments automatically' },
    { slug: 'review_request', priority: 'optional', description: 'Request tenant feedback after 30 days of occupancy' },
  ],
  suggested_segments: ['property_seekers', 'pending_payments', 'active_last_30', 'new_contacts_7d', 'location_lagos', 'location_abuja'],
  setup_actions: [
    { id: 'realestate-tenant-properties', title: 'Add property tags for tenant matching', description: 'Create tags for your rental properties (residential, commercial, short-let) with location', priority: 'essential', category: 'contacts', target_url: '/contacts', target_params: { tab: 'tags' }, estimated_minutes: 5, icon: '🏠' },
    { id: 'realestate-tenant-rent-reminder', title: 'Configure rent payment reminders', description: 'Set up automated rent reminders based on your payment collection cycle', priority: 'essential', category: 'automations', target_url: '/automations/new', target_params: { template: 'payment_reminder' }, estimated_minutes: 5, icon: '💰' },
    { id: 'realestate-tenant-welcome', title: 'Customise rental enquiry greeting', description: 'Edit the auto-greeting to include available properties and viewing schedule', priority: 'essential', category: 'automations', target_url: '/automations/new', target_params: { template: 'welcome_message' }, estimated_minutes: 5, icon: '👋' },
    { id: 'realestate-tenant-screening', title: 'Set up tenant screening checklist', description: 'Customise the screening checklist based on your landlord requirements', priority: 'recommended', category: 'flows', target_url: '/flows', estimated_minutes: 10, icon: '✅' },
    { id: 'realestate-tenant-agreement', title: 'Add tenancy agreement template', description: 'Upload your standard tenancy agreement for quick generation during onboarding', priority: 'recommended', category: 'settings', target_url: '/settings', estimated_minutes: 5, icon: '📄' },
    { id: 'realestate-tenant-review', title: 'Set up tenant feedback request', description: 'Configure feedback request 30 days after occupancy', priority: 'optional', category: 'automations', target_url: '/automations/new', target_params: { template: 'review_request' }, estimated_minutes: 3, icon: '⭐' },
  ],
  customization_hints: [
    'Add your specific properties as tags for easy matching with enquiries',
    'Configure rent reminder timing based on your payment collection cycle',
    'Set up segments for different property types (residential, commercial, short-let)',
    'Add your standard tenancy agreement template for quick generation',
    'Customise screening checklist based on your landlord requirements',
  ],
}
