import type { IndustryWorkflowBundle } from '../types'

// ============================================================
// RESTAURANT — Order Pipeline
// ============================================================
export const RESTAURANT_ORDER_BUNDLE: IndustryWorkflowBundle = {
  id: 'restaurant-order',
  industry: 'Restaurant',
  process: 'sales',
  name: 'Restaurant Order Pipeline',
  description: 'Fast-moving order pipeline for walk-in, WhatsApp, and delivery app orders with Nigerian food service context.',
  icon: '🍽️',
  setup_time_minutes: 10,
  pipeline: {
    id: 'restaurant-order-pipeline',
    name: 'Restaurant Orders',
    icon: '🍽️',
    description: 'Customer order to delivery or pickup',
    category: 'sales',
    stages: [
      {
        name: 'Order Received',
        color: '#6366F1',
        position: 1,
        purpose: 'Capture customer order from WhatsApp, walk-in, phone call, or delivery app',
        owner_role: 'Order Taker / Cashier',
        entry_criteria: [
          'Customer has placed an order through any channel',
          'Menu items and quantities specified',
        ],
        exit_criteria: [
          'Order details confirmed with customer',
          'Payment method agreed (prepay or pay on delivery)',
        ],
        checklist: [
          { text: 'Record all menu items with quantities and any special requests (extra pepper, no onions, etc.)', required: true },
          { text: 'Confirm order total in Naira and communicate to customer', required: true },
          { text: 'For delivery orders, collect full delivery address with landmark', required: true },
          { text: 'Confirm payment method: bank transfer before preparation, POS on pickup, or cash on delivery', required: true },
          { text: 'Provide estimated preparation time (e.g., 30-45 minutes for standard orders)', required: true },
          { text: 'Assign order number and share with customer via WhatsApp', required: true },
        ],
        sla_hint: '5 minutes',
      },
      {
        name: 'Payment Confirmed',
        color: '#8B5CF6',
        position: 2,
        purpose: 'Verify payment before starting food preparation (for prepaid orders)',
        owner_role: 'Cashier',
        entry_criteria: [
          'Order details confirmed',
          'For prepaid orders: customer has initiated payment',
        ],
        exit_criteria: [
          'Payment verified or COD approved',
          'Order sent to kitchen',
        ],
        checklist: [
          { text: 'For bank transfer: verify payment receipt matches order amount', required: true },
          { text: 'For POS: confirm transaction successful on terminal', required: true },
          { text: 'For cash on delivery: confirm with manager if order value exceeds COD limit', required: true },
          { text: 'Send payment confirmation to customer via WhatsApp', required: true },
          { text: 'Forward order ticket to kitchen with preparation priority noted', required: true },
        ],
        sla_hint: '10 minutes',
      },
      {
        name: 'Preparing',
        color: '#F59E0B',
        position: 3,
        purpose: 'Kitchen is actively preparing the order',
        owner_role: 'Kitchen Staff / Chef',
        entry_criteria: [
          'Payment confirmed or COD approved',
          'Order ticket received in kitchen',
        ],
        exit_criteria: [
          'All items prepared and quality-checked',
          'Order packaged for delivery or plated for dine-in',
        ],
        checklist: [
          { text: 'Verify all ingredients available before starting preparation', required: true },
          { text: 'Prepare each menu item according to standard recipe and customer specifications', required: true },
          { text: 'Quality-check each item: taste, temperature, presentation, portion size', required: true },
          { text: 'Package delivery orders in appropriate containers (leak-proof for soups and stews)', required: true },
          { text: 'Include napkins, cutlery, and condiments (pepper sauce, ketchup) in delivery package', required: true },
          { text: 'Notify front desk or dispatch that order is ready', required: true },
        ],
        sla_hint: '30-45 minutes',
      },
      {
        name: 'Ready',
        color: '#10B981',
        position: 4,
        purpose: 'Order prepared and waiting for pickup or dispatch rider',
        owner_role: 'Front Desk / Dispatch',
        entry_criteria: [
          'Kitchen has completed and packaged the order',
          'Quality check passed',
        ],
        exit_criteria: [
          'Order collected by customer (pickup) or handed to dispatch rider (delivery)',
        ],
        checklist: [
          { text: 'Verify packaged order matches order ticket (all items present, correct quantities)', required: true },
          { text: 'For pickup: notify customer via WhatsApp that order is ready for collection', required: true },
          { text: 'For delivery: assign dispatch rider and hand over package with delivery address', required: true },
          { text: 'For delivery: share rider name and phone number with customer', required: true },
          { text: 'Ensure hot items are kept warm while waiting for collection or dispatch', required: false },
        ],
        sla_hint: '15 minutes',
      },
      {
        name: 'Delivered / Picked Up',
        color: '#059669',
        position: 5,
        purpose: 'Order successfully delivered to customer or collected from restaurant',
        owner_role: 'Dispatch / Cashier',
        entry_criteria: [
          'Customer has received the order',
        ],
        exit_criteria: [
          'Delivery confirmed',
          'COD payment collected if applicable',
          'Order closed in system',
        ],
        checklist: [
          { text: 'Confirm delivery with customer via WhatsApp or rider confirmation', required: true },
          { text: 'If COD: collect payment from rider and reconcile with order amount', required: true },
          { text: 'Send thank-you message with invitation to order again', required: true },
          { text: 'Ask for feedback if customer is a repeat buyer', required: false },
          { text: 'Update order as completed in system with final amount and delivery time', required: true },
          { text: 'Tag frequent customers for loyalty programme or special offers', required: false },
        ],
        sla_hint: '30-60 minutes from dispatch',
      },
    ],
  },
  suggested_flows: ['welcome_menu', 'restaurant_order_flow', 'feedback_collector', 'payment_confirmation_flow', 'delivery_tracking_flow'],
  suggested_automations: [
    { slug: 'welcome_message', priority: 'essential', description: 'Auto-greet new customers with menu link and ordering instructions' },
    { slug: 'payment_reminder', priority: 'essential', description: 'Remind customer to pay if order placed but no payment after 15 minutes' },
    { slug: 'delivery_notification', priority: 'essential', description: 'Notify customer when food is ready and dispatched' },
    { slug: 'review_request', priority: 'recommended', description: 'Ask for review after delivery confirmation' },
    { slug: 'dormant_reactivation', priority: 'optional', description: 'Send special offer to customers who have not ordered in 30+ days' },
  ],
  suggested_segments: ['active_last_30', 'repeat_buyers', 'dormant_60_plus', 'high_value_customers', 'new_contacts_7d', 'location_lagos'],
  customization_hints: [
    'Upload your current menu as a WhatsApp catalogue or PDF for easy sharing',
    'Set preparation time estimates per menu category (rice dishes: 30min, grills: 45min)',
    'Configure delivery zones and fees based on distance from your restaurant',
    'Add your popular combos as quick-reply options in the order flow',
    'Set up daily specials automation to broadcast menu highlights each morning',
  ],
}

// ============================================================
// RESTAURANT — Catering Pipeline
// ============================================================
export const RESTAURANT_CATERING_BUNDLE: IndustryWorkflowBundle = {
  id: 'restaurant-catering',
  industry: 'Restaurant',
  process: 'operations',
  name: 'Restaurant Catering Pipeline',
  description: 'Event catering pipeline from enquiry through menu planning, deposit collection, preparation, and event-day delivery for Nigerian celebrations.',
  icon: '🎂',
  setup_time_minutes: 15,
  pipeline: {
    id: 'restaurant-catering-pipeline',
    name: 'Catering Orders',
    icon: '🎂',
    description: 'Catering enquiry to event completion',
    category: 'operations',
    stages: [
      {
        name: 'Enquiry',
        color: '#6366F1',
        position: 1,
        purpose: 'Capture event details and catering requirements',
        owner_role: 'Catering Manager',
        entry_criteria: [
          'Customer has enquired about catering services',
          'Basic event details shared',
        ],
        exit_criteria: [
          'Event date, location, and guest count confirmed',
          'Budget range discussed',
          'Menu preferences noted',
        ],
        checklist: [
          { text: 'Record event type: wedding reception (owambe), birthday, corporate event, burial, naming ceremony', required: true },
          { text: 'Confirm event date, start time, and expected duration', required: true },
          { text: 'Get event venue address and confirm kitchen/serving access', required: true },
          { text: 'Confirm expected number of guests (minimum and maximum)', required: true },
          { text: 'Ask budget range per head or total budget in Naira', required: true },
          { text: 'Note dietary requirements: halal, vegetarian, allergies, cultural preferences', required: false },
          { text: 'Ask about service style: buffet, plated, small chops station, or combination', required: true },
        ],
        sla_hint: '4 business hours',
      },
      {
        name: 'Menu Planning',
        color: '#8B5CF6',
        position: 2,
        purpose: 'Design custom menu based on event type, guest count, and budget',
        owner_role: 'Catering Manager / Chef',
        entry_criteria: [
          'Event details confirmed',
          'Budget range established',
        ],
        exit_criteria: [
          'Menu proposal created with itemised pricing',
          'Customer has reviewed menu options',
        ],
        checklist: [
          { text: 'Create menu proposal with 2-3 options at different price points per head', required: true },
          { text: 'Include Nigerian staples appropriate to event: jollof rice, fried rice, pounded yam, egusi, pepper soup', required: true },
          { text: 'Add small chops selection: spring rolls, samosa, puff puff, chicken wings, gizdodo', required: false },
          { text: 'Include drinks package: soft drinks, water, zobo, chapman, or full bar service', required: true },
          { text: 'Calculate per-head cost and total cost including service staff and equipment', required: true },
          { text: 'Share menu proposal via WhatsApp with photos of signature dishes', required: true },
        ],
        sla_hint: '2 business days',
      },
      {
        name: 'Quote Sent',
        color: '#EC4899',
        position: 3,
        purpose: 'Formal quotation shared with customer for approval',
        owner_role: 'Catering Manager',
        entry_criteria: [
          'Menu selected by customer',
          'Final guest count confirmed',
        ],
        exit_criteria: [
          'Customer has accepted the quote',
          'Payment terms agreed',
        ],
        checklist: [
          { text: 'Generate formal quote with menu items, quantities, per-head rate, and total in Naira', required: true },
          { text: 'Include service extras: chafing dishes, serving staff, table setup, decoration', required: true },
          { text: 'Specify payment terms: 50% deposit to confirm, balance 3 days before event', required: true },
          { text: 'Include cancellation policy and date-change terms', required: true },
          { text: 'Send quote via WhatsApp and follow up within 48 hours if no response', required: true },
        ],
        sla_hint: '24 hours',
      },
      {
        name: 'Deposit Paid',
        color: '#F59E0B',
        position: 4,
        purpose: 'Deposit received, event booking confirmed',
        owner_role: 'Finance / Catering Manager',
        entry_criteria: [
          'Customer has accepted the quote',
          'Deposit payment initiated',
        ],
        exit_criteria: [
          'Deposit verified (minimum 50% of total)',
          'Event date blocked on calendar',
          'Confirmation sent to customer',
        ],
        checklist: [
          { text: 'Verify deposit amount matches agreed percentage (typically 50%) of total quote', required: true },
          { text: 'Issue official receipt for deposit payment', required: true },
          { text: 'Block event date on catering calendar to prevent double-booking', required: true },
          { text: 'Send booking confirmation message with event details summary', required: true },
          { text: 'Set reminder for balance payment 5 days before event', required: true },
          { text: 'Begin preliminary ingredient sourcing for bulk items', required: false },
        ],
        sla_hint: '24 hours to verify',
      },
      {
        name: 'Preparation',
        color: '#3B82F6',
        position: 5,
        purpose: 'Active food preparation and logistics planning for the event',
        owner_role: 'Chef / Kitchen Team',
        entry_criteria: [
          'Full payment received (deposit + balance)',
          'Event is within 3 days',
        ],
        exit_criteria: [
          'All food items prepared or prepped',
          'Equipment and staff logistics confirmed',
        ],
        checklist: [
          { text: 'Verify balance payment received and issue final receipt', required: true },
          { text: 'Purchase all ingredients from verified suppliers (Oyingbo, Mile 12, or trusted vendors)', required: true },
          { text: 'Prepare items that can be made ahead: small chops, sauces, marinades', required: true },
          { text: 'Confirm serving staff availability and assign roles (servers, drink station, cleanup)', required: true },
          { text: 'Prepare equipment checklist: chafing dishes, coolers, serving utensils, gas cylinders', required: true },
          { text: 'Arrange transport: van or truck for food, equipment, and staff to venue', required: true },
          { text: 'Call customer to confirm final guest count and any last-minute changes', required: true },
        ],
        sla_hint: '2-3 days before event',
      },
      {
        name: 'Delivery / Setup',
        color: '#10B981',
        position: 6,
        purpose: 'Transport food and equipment to venue, set up serving stations',
        owner_role: 'Catering Manager / Team Lead',
        entry_criteria: [
          'All food prepared and packed for transport',
          'Equipment loaded and transport arranged',
        ],
        exit_criteria: [
          'Food and equipment delivered to venue',
          'Serving stations set up and ready',
          'Service commenced',
        ],
        checklist: [
          { text: 'Load all food items in insulated containers to maintain temperature', required: true },
          { text: 'Verify all equipment loaded against checklist before departing', required: true },
          { text: 'Arrive at venue minimum 2 hours before serving time', required: true },
          { text: 'Set up serving stations, chafing dishes, and drink area', required: true },
          { text: 'Do final food quality check: temperature, presentation, taste', required: true },
          { text: 'Brief serving staff on service flow and customer expectations', required: true },
          { text: 'Notify customer that setup is complete and service is ready to begin', required: true },
        ],
        sla_hint: '2 hours before event start',
      },
      {
        name: 'Event Complete',
        color: '#059669',
        position: 7,
        purpose: 'Event concluded, cleanup done, post-event follow-up',
        owner_role: 'Catering Manager',
        entry_criteria: [
          'Event has concluded',
          'Food service completed',
        ],
        exit_criteria: [
          'Venue cleaned and equipment collected',
          'Customer feedback collected',
          'Deal closed in CRM',
        ],
        checklist: [
          { text: 'Supervise cleanup: pack leftover food, collect all equipment, clean serving area', required: true },
          { text: 'Verify all equipment returned and accounted for (no missing chafing dishes or coolers)', required: true },
          { text: 'Send thank-you message to customer within 24 hours', required: true },
          { text: 'Request feedback and photos from the event for portfolio', required: true },
          { text: 'Ask for referral: does customer know anyone planning an event?', required: false },
          { text: 'Update deal as Won in CRM with final amount and event details', required: true },
          { text: 'Add customer to VIP list for future event promotions', required: false },
        ],
        sla_hint: '24 hours after event',
      },
    ],
  },
  suggested_flows: ['welcome_menu', 'catering_enquiry_flow', 'payment_confirmation_flow', 'feedback_collector'],
  suggested_automations: [
    { slug: 'welcome_message', priority: 'essential', description: 'Auto-greet catering enquiries with menu options and pricing guide' },
    { slug: 'payment_reminder', priority: 'essential', description: 'Remind customer of balance payment 5 days before event' },
    { slug: 'booking_confirmation', priority: 'essential', description: 'Send confirmation when deposit is received' },
    { slug: 'appointment_reminder_24h', priority: 'recommended', description: 'Send event-day reminder to customer 24 hours before' },
    { slug: 'review_request', priority: 'recommended', description: 'Request review and photos 24 hours after event' },
    { slug: 'dormant_reactivation', priority: 'optional', description: 'Re-engage past catering clients before festive seasons' },
  ],
  suggested_segments: ['event_leads', 'high_value_customers', 'repeat_buyers', 'active_last_30', 'referral_sources', 'seasonal_buyers'],
  customization_hints: [
    'Create menu packages at different price points for quick quoting',
    'Set up seasonal promotions for December parties, Easter, and Sallah celebrations',
    'Add your signature dishes with photos for the catering enquiry flow',
    'Configure balance payment reminder timing based on your preparation lead time',
    'Tag events by type (wedding, corporate, birthday) for targeted marketing',
  ],
}
