import type { IndustryWorkflowBundle } from '../types'

// ============================================================
// RETAIL — Sales Pipeline
// ============================================================
export const RETAIL_SALES_BUNDLE: IndustryWorkflowBundle = {
  id: 'retail-sales',
  industry: 'Retail',
  process: 'sales',
  name: 'Retail Sales Pipeline',
  description: 'End-to-end retail sales from WhatsApp product enquiry through payment, delivery, and repeat purchase tracking.',
  icon: '🛒',
  setup_time_minutes: 15,
  pipeline: {
    id: 'retail-sales-pipeline',
    name: 'Retail Sales',
    icon: '🛒',
    description: 'Product enquiry to delivery and repeat purchase',
    category: 'sales',
    stages: [
      {
        name: 'Product Enquiry',
        color: '#6366F1',
        position: 1,
        purpose: 'Capture and qualify inbound product interest from WhatsApp, Instagram DMs, or walk-ins',
        owner_role: 'Sales Rep',
        entry_criteria: [
          'Customer has sent a message asking about a product',
          'Contact record exists in CRM with valid phone number',
        ],
        exit_criteria: [
          'Product identified and availability confirmed',
          'Customer budget range established',
          'Quote or price list shared with customer',
        ],
        checklist: [
          { text: 'Confirm customer phone number is valid Nigerian mobile format (080/081/090/091/070)', required: true },
          { text: 'Identify specific product(s) customer is asking about', required: true },
          { text: 'Check current stock availability in inventory system', required: true },
          { text: 'Ask customer preferred delivery location (Lagos, Abuja, or other state)', required: false },
          { text: 'Tag contact with product category interest (e.g., electronics, fashion, groceries)', required: true },
          { text: 'Send product photos and current price list via WhatsApp', required: true },
        ],
        sla_hint: '2 business hours',
      },
      {
        name: 'Quote Sent',
        color: '#8B5CF6',
        position: 2,
        purpose: 'Formal pricing shared with customer including delivery fees and payment options',
        owner_role: 'Sales Rep',
        entry_criteria: [
          'Customer has confirmed interest in specific product(s)',
          'Stock availability verified',
        ],
        exit_criteria: [
          'Customer has acknowledged receipt of quote',
          'Customer has indicated intent to proceed or requested changes',
        ],
        checklist: [
          { text: 'Generate itemised quote with product name, quantity, unit price, and total in Naira (₦)', required: true },
          { text: 'Include delivery fee based on customer location (within Lagos vs interstate)', required: true },
          { text: 'List accepted payment methods: bank transfer, POS, cash on delivery (if applicable)', required: true },
          { text: 'Include bank account details for transfer payment (bank name, account number, account name)', required: true },
          { text: 'Set quote validity period (e.g., 48 hours) and communicate to customer', required: true },
          { text: 'Send quote via WhatsApp and confirm customer received it', required: true },
        ],
        sla_hint: '4 business hours',
      },
      {
        name: 'Payment Pending',
        color: '#EC4899',
        position: 3,
        purpose: 'Awaiting customer payment confirmation via bank transfer, POS, or other method',
        owner_role: 'Sales Rep',
        entry_criteria: [
          'Quote accepted by customer',
          'Customer has confirmed they will make payment',
        ],
        exit_criteria: [
          'Payment received and verified in bank account or POS terminal',
          'Payment receipt or transfer confirmation screenshot collected',
        ],
        checklist: [
          { text: 'Confirm customer has the correct bank account details for transfer', required: true },
          { text: 'Set payment reminder for 24 hours if no payment received', required: true },
          { text: 'Ask customer to send transfer receipt or screenshot after payment', required: true },
          { text: 'Verify payment amount matches invoice total (check for shortfall or overpayment)', required: true },
          { text: 'Cross-check payment against bank statement or POS transaction log', required: true },
          { text: 'Record payment method and transaction reference in CRM deal notes', required: true },
        ],
        sla_hint: '24 hours',
      },
      {
        name: 'Order Confirmed',
        color: '#F59E0B',
        position: 4,
        purpose: 'Payment verified, order is being prepared for dispatch',
        owner_role: 'Operations Manager',
        entry_criteria: [
          'Payment fully received and verified',
          'Stock confirmed available for the ordered items',
        ],
        exit_criteria: [
          'Order packed and labelled with customer details',
          'Dispatch rider or logistics partner assigned',
        ],
        checklist: [
          { text: 'Send order confirmation message to customer via WhatsApp with order summary', required: true },
          { text: 'Generate order reference number and share with customer', required: true },
          { text: 'Reserve stock in inventory system to prevent overselling', required: true },
          { text: 'Print or write delivery label with customer name, phone, and full address', required: true },
          { text: 'Assign dispatch rider or select logistics partner (GIG Logistics, Kwik, or in-house)', required: true },
          { text: 'Confirm estimated delivery date and communicate to customer', required: true },
        ],
        sla_hint: '4 business hours',
      },
      {
        name: 'Out for Delivery',
        color: '#10B981',
        position: 5,
        purpose: 'Order dispatched and in transit to customer',
        owner_role: 'Dispatch Coordinator',
        entry_criteria: [
          'Order packed and handed to dispatch rider or logistics partner',
          'Customer notified of dispatch with tracking info',
        ],
        exit_criteria: [
          'Customer confirms receipt of order',
          'Proof of delivery obtained (photo or signature)',
        ],
        checklist: [
          { text: 'Send dispatch notification to customer with rider name and phone number', required: true },
          { text: 'Share waybill or tracking number if using logistics partner', required: true },
          { text: 'Confirm delivery address with rider before dispatch', required: true },
          { text: 'Follow up with rider after 2 hours if no delivery confirmation', required: false },
          { text: 'Collect proof of delivery photo from rider showing package with customer', required: true },
        ],
        sla_hint: '24 hours (Lagos), 2-5 business days (interstate)',
      },
      {
        name: 'Delivered',
        color: '#059669',
        position: 6,
        purpose: 'Order successfully delivered, post-sale follow-up and repeat purchase nurturing',
        owner_role: 'Sales Rep',
        entry_criteria: [
          'Customer has confirmed receipt of order',
          'Proof of delivery on file',
        ],
        exit_criteria: [
          'Customer satisfaction confirmed',
          'Review or feedback requested',
          'Deal marked as won in CRM',
        ],
        checklist: [
          { text: 'Send thank-you message to customer via WhatsApp within 2 hours of delivery', required: true },
          { text: 'Ask customer to confirm all items received and in good condition', required: true },
          { text: 'Request Google or social media review if customer is satisfied', required: false },
          { text: 'Tag contact as repeat-buyer-candidate for future promotions', required: true },
          { text: 'Update deal as Won with final amount and close date in CRM', required: true },
          { text: 'Schedule follow-up message for 7 days later with related product suggestions', required: false },
        ],
        sla_hint: '24 hours after delivery',
      },
    ],
  },
  suggested_flows: ['welcome_menu', 'product_enquiry', 'order_status', 'feedback_collector', 'delivery_tracking_flow', 'payment_confirmation_flow'],
  suggested_automations: [
    { slug: 'welcome_message', priority: 'essential', description: 'Auto-greet new WhatsApp contacts with product catalogue link' },
    { slug: 'payment_reminder', priority: 'essential', description: 'Nudge customers who have not paid within 24 hours of quote' },
    { slug: 'delivery_notification', priority: 'essential', description: 'Notify customer when order is dispatched with rider details' },
    { slug: 'review_request', priority: 'recommended', description: 'Request review 24 hours after successful delivery' },
    { slug: 'follow_up_reminder', priority: 'recommended', description: 'Follow up on quotes not converted after 48 hours' },
    { slug: 'dormant_reactivation', priority: 'optional', description: 'Re-engage customers who have not ordered in 60+ days' },
  ],
  suggested_segments: ['active_last_30', 'dormant_60_plus', 'high_value_customers', 'repeat_buyers', 'pending_payments', 'new_contacts_7d'],
  customization_hints: [
    'Add your specific product categories as tags for better segmentation',
    'Set delivery fee tiers based on your coverage areas (within city vs interstate)',
    'Configure payment reminder timing based on your typical customer payment speed',
    'Add your bank account details to the quote template for faster payments',
    'Customise the dispatch rider assignment based on your logistics partners',
  ],
}

// ============================================================
// RETAIL — Order Fulfilment Pipeline
// ============================================================
export const RETAIL_FULFILMENT_BUNDLE: IndustryWorkflowBundle = {
  id: 'retail-fulfilment',
  industry: 'Retail',
  process: 'operations',
  name: 'Retail Order Fulfilment',
  description: 'Operations pipeline tracking orders from receipt through picking, packing, dispatch, and delivery confirmation.',
  icon: '📦',
  setup_time_minutes: 12,
  pipeline: {
    id: 'retail-fulfilment-pipeline',
    name: 'Order Fulfilment',
    icon: '📦',
    description: 'Order received to delivery confirmation',
    category: 'operations',
    stages: [
      {
        name: 'Order Received',
        color: '#6366F1',
        position: 1,
        purpose: 'New order logged in system awaiting payment verification',
        owner_role: 'Order Processor',
        entry_criteria: [
          'Customer has placed an order via WhatsApp, website, or in-store',
          'Order details captured: items, quantities, delivery address',
        ],
        exit_criteria: [
          'Order details verified with customer',
          'Payment status confirmed (paid, COD, or pending)',
        ],
        checklist: [
          { text: 'Log order with unique reference number in CRM', required: true },
          { text: 'Verify all ordered items, quantities, sizes, and colours with customer', required: true },
          { text: 'Confirm delivery address including landmark and closest bus stop', required: true },
          { text: 'Record preferred delivery date and time window', required: false },
          { text: 'Check if order qualifies for cash on delivery or requires prepayment', required: true },
        ],
        sla_hint: '1 business hour',
      },
      {
        name: 'Payment Confirmed',
        color: '#8B5CF6',
        position: 2,
        purpose: 'Payment verified and order cleared for fulfilment',
        owner_role: 'Finance / Order Processor',
        entry_criteria: [
          'Bank transfer receipt received or COD approved',
          'Payment amount matches order total',
        ],
        exit_criteria: [
          'Payment recorded in system',
          'Order flagged as ready for picking',
        ],
        checklist: [
          { text: 'Verify bank transfer amount matches order total including delivery fee', required: true },
          { text: 'Check sender name on transfer matches customer name or known alias', required: true },
          { text: 'Record payment reference number and payment method in CRM', required: true },
          { text: 'Send payment confirmation message to customer via WhatsApp', required: true },
          { text: 'Flag order as cleared for warehouse picking', required: true },
        ],
        sla_hint: '2 business hours',
      },
      {
        name: 'Picking & Packing',
        color: '#F59E0B',
        position: 3,
        purpose: 'Warehouse team locates items, quality-checks, and packs for dispatch',
        owner_role: 'Warehouse Staff',
        entry_criteria: [
          'Payment confirmed and order cleared',
          'All items available in stock',
        ],
        exit_criteria: [
          'All items picked, inspected, and packed',
          'Package labelled with delivery details',
        ],
        checklist: [
          { text: 'Pick all items from shelves and verify against order list', required: true },
          { text: 'Inspect each item for defects, damage, or wrong variant before packing', required: true },
          { text: 'Pack items securely with bubble wrap or padding for fragile goods', required: true },
          { text: 'Attach delivery label with customer name, phone, address, and order reference', required: true },
          { text: 'Take photo of packed order for records and dispute resolution', required: true },
          { text: 'Update inventory count to reflect items removed from stock', required: true },
          { text: 'Place packed order in dispatch staging area', required: true },
        ],
        sla_hint: '4 business hours',
      },
      {
        name: 'Dispatched',
        color: '#EC4899',
        position: 4,
        purpose: 'Order handed to dispatch rider or logistics partner for delivery',
        owner_role: 'Dispatch Coordinator',
        entry_criteria: [
          'Order packed and in staging area',
          'Dispatch rider or logistics partner available',
        ],
        exit_criteria: [
          'Rider has collected package',
          'Waybill or tracking number generated',
          'Customer notified of dispatch',
        ],
        checklist: [
          { text: 'Assign dispatch rider and record rider name and phone number', required: true },
          { text: 'Generate waybill number if using logistics partner (GIG, Kwik, DHL)', required: true },
          { text: 'Hand package to rider and get acknowledgement (signature or photo)', required: true },
          { text: 'Send dispatch notification to customer with rider contact and estimated arrival', required: true },
          { text: 'Record dispatch time and expected delivery window in CRM', required: true },
        ],
        sla_hint: '2 business hours',
      },
      {
        name: 'In Transit',
        color: '#10B981',
        position: 5,
        purpose: 'Package moving from warehouse to customer, tracking active',
        owner_role: 'Dispatch Coordinator',
        entry_criteria: [
          'Rider has departed with package',
          'Customer has been notified',
        ],
        exit_criteria: [
          'Rider confirms arrival at delivery address',
          'Customer contacted for handover',
        ],
        checklist: [
          { text: 'Monitor rider location or check in with rider every 2 hours for long-distance deliveries', required: false },
          { text: 'Contact customer 30 minutes before estimated arrival to confirm availability', required: true },
          { text: 'Handle any delivery issues: wrong address, customer unavailable, road closures', required: true },
          { text: 'If interstate delivery, confirm package arrived at transit hub and is on final leg', required: false },
        ],
        sla_hint: 'Same day (Lagos), 2-5 days (interstate)',
      },
      {
        name: 'Delivered',
        color: '#059669',
        position: 6,
        purpose: 'Order delivered to customer, proof collected, fulfilment complete',
        owner_role: 'Dispatch Coordinator',
        entry_criteria: [
          'Rider has arrived at delivery address',
          'Customer is available to receive package',
        ],
        exit_criteria: [
          'Customer has received and accepted the order',
          'Proof of delivery collected',
          'COD payment collected if applicable',
        ],
        checklist: [
          { text: 'Collect proof of delivery: photo of customer with package or signed delivery note', required: true },
          { text: 'If cash on delivery, collect exact amount and issue receipt to customer', required: true, description: 'Count cash in front of customer and confirm amount' },
          { text: 'Ask customer to open and inspect package in presence of rider if possible', required: false },
          { text: 'Send delivery confirmation message to customer via WhatsApp', required: true },
          { text: 'Update order status to Delivered in CRM with delivery timestamp', required: true },
          { text: 'Reconcile COD cash with finance team within same business day', required: true },
        ],
        sla_hint: '30 minutes (handover)',
      },
    ],
  },
  suggested_flows: ['order_status', 'delivery_tracking_flow', 'payment_confirmation_flow', 'feedback_collector', 'complaint_resolution_flow'],
  suggested_automations: [
    { slug: 'delivery_notification', priority: 'essential', description: 'Auto-notify customer when order moves to Dispatched stage' },
    { slug: 'payment_reminder', priority: 'essential', description: 'Remind customer if payment not received within 24 hours' },
    { slug: 'review_request', priority: 'recommended', description: 'Request feedback 24 hours after delivery confirmation' },
    { slug: 'overdue_payment_escalation', priority: 'recommended', description: 'Escalate to manager if COD not reconciled within 24 hours' },
    { slug: 'booking_confirmation', priority: 'optional', description: 'Send order confirmation when payment is verified' },
  ],
  suggested_segments: ['pending_payments', 'active_last_30', 'high_value_customers', 'repeat_buyers', 'location_lagos', 'location_abuja'],
  customization_hints: [
    'Add your warehouse locations and coverage zones for accurate delivery estimates',
    'Configure COD limits based on your risk tolerance and customer trust scores',
    'Set up dispatch rider contacts as team members for easy assignment',
    'Customise packing checklist based on your product types (fragile, perishable, etc.)',
    'Add your logistics partner waybill format for consistent tracking',
  ],
}
