/**
 * International messaging channel matrix.
 * Penetration data sourced from industry reports (2024-2025).
 * Used by the Channel Matrix dashboard in Settings.
 */

export interface ChannelInfo {
  name: string;
  icon: string; // emoji
  penetration: number; // 0-100 percentage
  businessUse: 'high' | 'medium' | 'low';
  costLevel: 'free' | 'low' | 'medium' | 'high';
  apiAvailable: boolean;
  notes: string;
}

export interface CountryChannels {
  code: string;
  name: string;
  flag: string;
  population: string;
  internetPenetration: number;
  channels: ChannelInfo[];
}

export const CHANNEL_MATRIX: CountryChannels[] = [
  {
    code: 'NG',
    name: 'Nigeria',
    flag: '🇳🇬',
    population: '230M',
    internetPenetration: 55,
    channels: [
      {
        name: 'WhatsApp',
        icon: '💬',
        penetration: 93,
        businessUse: 'high',
        costLevel: 'low',
        apiAvailable: true,
        notes: 'Dominant messaging platform. WhatsApp Business API essential for Nigerian market.',
      },
      {
        name: 'SMS',
        icon: '📱',
        penetration: 98,
        businessUse: 'high',
        costLevel: 'medium',
        apiAvailable: true,
        notes: 'Universal reach including feature phones. DND registry affects delivery (~40% opt-out).',
      },
      {
        name: 'Instagram',
        icon: '📸',
        penetration: 28,
        businessUse: 'high',
        costLevel: 'low',
        apiAvailable: true,
        notes: 'Strong for fashion, beauty, food businesses. Instagram DM API available.',
      },
      {
        name: 'Facebook Messenger',
        icon: '💭',
        penetration: 42,
        businessUse: 'medium',
        costLevel: 'free',
        apiAvailable: true,
        notes: 'Declining among youth but still strong in 35+ demographic.',
      },
      {
        name: 'Telegram',
        icon: '✈️',
        penetration: 18,
        businessUse: 'low',
        costLevel: 'free',
        apiAvailable: true,
        notes: 'Growing in tech communities. Bot API is free and powerful.',
      },
      {
        name: 'Email',
        icon: '📧',
        penetration: 35,
        businessUse: 'medium',
        costLevel: 'low',
        apiAvailable: true,
        notes: 'Lower open rates (~15-20%). Best for formal B2B communication.',
      },
      {
        name: 'Twitter/X',
        icon: '🐦',
        penetration: 12,
        businessUse: 'medium',
        costLevel: 'free',
        apiAvailable: true,
        notes: 'Strong for customer service and brand engagement. API costs increased.',
      },
      {
        name: 'TikTok',
        icon: '🎵',
        penetration: 22,
        businessUse: 'medium',
        costLevel: 'low',
        apiAvailable: false,
        notes: 'Fastest growing platform. No direct messaging API yet.',
      },
      {
        name: 'USSD',
        icon: '📞',
        penetration: 85,
        businessUse: 'medium',
        costLevel: 'high',
        apiAvailable: true,
        notes: 'Works on all phones. Used for banking, surveys. Requires telco partnership.',
      },
      {
        name: 'Voice (IVR)',
        icon: '🔊',
        penetration: 95,
        businessUse: 'low',
        costLevel: 'high',
        apiAvailable: true,
        notes: 'Highest reach. Expensive per-minute costs. Good for reminders and confirmations.',
      },
    ],
  },
  {
    code: 'GB',
    name: 'United Kingdom',
    flag: '🇬🇧',
    population: '68M',
    internetPenetration: 97,
    channels: [
      {
        name: 'WhatsApp',
        icon: '💬',
        penetration: 78,
        businessUse: 'medium',
        costLevel: 'low',
        apiAvailable: true,
        notes: 'Growing for business use. Strong in retail and hospitality.',
      },
      {
        name: 'SMS',
        icon: '📱',
        penetration: 95,
        businessUse: 'high',
        costLevel: 'medium',
        apiAvailable: true,
        notes: 'Trusted channel for transactional messages. GDPR compliance required.',
      },
      {
        name: 'Email',
        icon: '📧',
        penetration: 92,
        businessUse: 'high',
        costLevel: 'low',
        apiAvailable: true,
        notes: 'Primary B2B channel. Strong open rates (~25-30%). GDPR consent required.',
      },
      {
        name: 'Instagram',
        icon: '📸',
        penetration: 55,
        businessUse: 'high',
        costLevel: 'low',
        apiAvailable: true,
        notes: 'Essential for D2C brands. Shopping features well-adopted.',
      },
      {
        name: 'Facebook Messenger',
        icon: '💭',
        penetration: 62,
        businessUse: 'medium',
        costLevel: 'free',
        apiAvailable: true,
        notes: 'Widely used for customer service chatbots.',
      },
      {
        name: 'iMessage/RCS',
        icon: '💎',
        penetration: 52,
        businessUse: 'low',
        costLevel: 'medium',
        apiAvailable: false,
        notes: 'High iPhone market share. Apple Business Chat emerging.',
      },
      {
        name: 'Twitter/X',
        icon: '🐦',
        penetration: 38,
        businessUse: 'medium',
        costLevel: 'free',
        apiAvailable: true,
        notes: 'Key for customer service. Public nature drives accountability.',
      },
      {
        name: 'LinkedIn',
        icon: '💼',
        penetration: 42,
        businessUse: 'high',
        costLevel: 'medium',
        apiAvailable: true,
        notes: 'Essential for B2B. InMail and Sales Navigator APIs available.',
      },
      {
        name: 'TikTok',
        icon: '🎵',
        penetration: 45,
        businessUse: 'medium',
        costLevel: 'low',
        apiAvailable: false,
        notes: 'Strong Gen Z reach. TikTok Shop gaining traction.',
      },
      {
        name: 'Telegram',
        icon: '✈️',
        penetration: 12,
        businessUse: 'low',
        costLevel: 'free',
        apiAvailable: true,
        notes: 'Niche but growing. Popular in crypto and tech communities.',
      },
    ],
  },
  {
    code: 'CA',
    name: 'Canada',
    flag: '🇨🇦',
    population: '40M',
    internetPenetration: 97,
    channels: [
      {
        name: 'SMS',
        icon: '📱',
        penetration: 96,
        businessUse: 'high',
        costLevel: 'medium',
        apiAvailable: true,
        notes: 'Primary business messaging channel. CASL compliance mandatory.',
      },
      {
        name: 'Email',
        icon: '📧',
        penetration: 93,
        businessUse: 'high',
        costLevel: 'low',
        apiAvailable: true,
        notes: 'Dominant B2B channel. CASL anti-spam law requires explicit consent.',
      },
      {
        name: 'WhatsApp',
        icon: '💬',
        penetration: 42,
        businessUse: 'low',
        costLevel: 'low',
        apiAvailable: true,
        notes: 'Growing among immigrant communities. Not yet mainstream for business.',
      },
      {
        name: 'Facebook Messenger',
        icon: '💭',
        penetration: 68,
        businessUse: 'medium',
        costLevel: 'free',
        apiAvailable: true,
        notes: 'Strong adoption. Popular for local business customer service.',
      },
      {
        name: 'Instagram',
        icon: '📸',
        penetration: 58,
        businessUse: 'high',
        costLevel: 'low',
        apiAvailable: true,
        notes: 'Key for retail and lifestyle brands. Shopping features active.',
      },
      {
        name: 'iMessage/RCS',
        icon: '💎',
        penetration: 55,
        businessUse: 'low',
        costLevel: 'medium',
        apiAvailable: false,
        notes: 'High iPhone penetration. Apple Business Chat available.',
      },
      {
        name: 'LinkedIn',
        icon: '💼',
        penetration: 45,
        businessUse: 'high',
        costLevel: 'medium',
        apiAvailable: true,
        notes: 'Essential for B2B SaaS and professional services.',
      },
      {
        name: 'Twitter/X',
        icon: '🐦',
        penetration: 30,
        businessUse: 'medium',
        costLevel: 'free',
        apiAvailable: true,
        notes: 'Used for customer service and brand engagement.',
      },
      {
        name: 'TikTok',
        icon: '🎵',
        penetration: 40,
        businessUse: 'medium',
        costLevel: 'low',
        apiAvailable: false,
        notes: 'Rapidly growing. Strong for reaching younger demographics.',
      },
      {
        name: 'Telegram',
        icon: '✈️',
        penetration: 15,
        businessUse: 'low',
        costLevel: 'free',
        apiAvailable: true,
        notes: 'Niche adoption. Growing in tech and crypto communities.',
      },
    ],
  },
  {
    code: 'ZA',
    name: 'South Africa',
    flag: '🇿🇦',
    population: '62M',
    internetPenetration: 72,
    channels: [
      {
        name: 'WhatsApp',
        icon: '💬',
        penetration: 96,
        businessUse: 'high',
        costLevel: 'low',
        apiAvailable: true,
        notes: 'Dominant platform. WhatsApp Business widely adopted by SMEs.',
      },
      {
        name: 'SMS',
        icon: '📱',
        penetration: 94,
        businessUse: 'high',
        costLevel: 'medium',
        apiAvailable: true,
        notes: 'Strong for transactional messages. POPIA compliance required.',
      },
      {
        name: 'Facebook Messenger',
        icon: '💭',
        penetration: 38,
        businessUse: 'medium',
        costLevel: 'free',
        apiAvailable: true,
        notes: 'Moderate adoption. Used alongside WhatsApp.',
      },
      {
        name: 'Instagram',
        icon: '📸',
        penetration: 22,
        businessUse: 'medium',
        costLevel: 'low',
        apiAvailable: true,
        notes: 'Growing in urban areas. Strong for fashion and lifestyle.',
      },
      {
        name: 'Email',
        icon: '📧',
        penetration: 45,
        businessUse: 'medium',
        costLevel: 'low',
        apiAvailable: true,
        notes: 'Important for B2B. POPIA consent requirements apply.',
      },
      {
        name: 'USSD',
        icon: '📞',
        penetration: 80,
        businessUse: 'high',
        costLevel: 'high',
        apiAvailable: true,
        notes: 'Critical for banking and financial services. Works on all phones.',
      },
      {
        name: 'Telegram',
        icon: '✈️',
        penetration: 14,
        businessUse: 'low',
        costLevel: 'free',
        apiAvailable: true,
        notes: 'Small but growing tech community adoption.',
      },
      {
        name: 'Twitter/X',
        icon: '🐦',
        penetration: 15,
        businessUse: 'medium',
        costLevel: 'free',
        apiAvailable: true,
        notes: 'Active for customer service and public engagement.',
      },
      {
        name: 'TikTok',
        icon: '🎵',
        penetration: 30,
        businessUse: 'low',
        costLevel: 'low',
        apiAvailable: false,
        notes: 'Fast-growing among youth. Limited business messaging.',
      },
      {
        name: 'Voice (IVR)',
        icon: '🔊',
        penetration: 90,
        businessUse: 'medium',
        costLevel: 'high',
        apiAvailable: true,
        notes: 'High reach. Used for banking alerts and appointment reminders.',
      },
    ],
  },
  {
    code: 'GH',
    name: 'Ghana',
    flag: '🇬🇭',
    population: '34M',
    internetPenetration: 68,
    channels: [
      {
        name: 'WhatsApp',
        icon: '💬',
        penetration: 90,
        businessUse: 'high',
        costLevel: 'low',
        apiAvailable: true,
        notes: 'Primary messaging platform. WhatsApp Business growing rapidly.',
      },
      {
        name: 'SMS',
        icon: '📱',
        penetration: 95,
        businessUse: 'high',
        costLevel: 'medium',
        apiAvailable: true,
        notes: 'Universal reach. Hubtel and mNotify are popular local providers.',
      },
      {
        name: 'Facebook Messenger',
        icon: '💭',
        penetration: 35,
        businessUse: 'medium',
        costLevel: 'free',
        apiAvailable: true,
        notes: 'Moderate adoption. Facebook is popular for marketplace.',
      },
      {
        name: 'Instagram',
        icon: '📸',
        penetration: 15,
        businessUse: 'medium',
        costLevel: 'low',
        apiAvailable: true,
        notes: 'Growing in urban centres. Popular for fashion and food.',
      },
      {
        name: 'Telegram',
        icon: '✈️',
        penetration: 12,
        businessUse: 'low',
        costLevel: 'free',
        apiAvailable: true,
        notes: 'Small but active tech community.',
      },
      {
        name: 'Email',
        icon: '📧',
        penetration: 30,
        businessUse: 'medium',
        costLevel: 'low',
        apiAvailable: true,
        notes: 'Used primarily for formal business communication.',
      },
      {
        name: 'USSD',
        icon: '📞',
        penetration: 82,
        businessUse: 'high',
        costLevel: 'high',
        apiAvailable: true,
        notes: 'Essential for mobile money (MTN MoMo). Works on all phones.',
      },
      {
        name: 'Twitter/X',
        icon: '🐦',
        penetration: 10,
        businessUse: 'low',
        costLevel: 'free',
        apiAvailable: true,
        notes: 'Limited but vocal user base. Good for brand awareness.',
      },
      {
        name: 'TikTok',
        icon: '🎵',
        penetration: 18,
        businessUse: 'low',
        costLevel: 'low',
        apiAvailable: false,
        notes: 'Growing among youth. Entertainment-focused.',
      },
      {
        name: 'Voice (IVR)',
        icon: '🔊',
        penetration: 92,
        businessUse: 'medium',
        costLevel: 'high',
        apiAvailable: true,
        notes: 'High reach including rural areas. Used for health and agriculture.',
      },
    ],
  },
  {
    code: 'KE',
    name: 'Kenya',
    flag: '🇰🇪',
    population: '56M',
    internetPenetration: 85,
    channels: [
      {
        name: 'WhatsApp',
        icon: '💬',
        penetration: 88,
        businessUse: 'high',
        costLevel: 'low',
        apiAvailable: true,
        notes: 'Dominant messaging app. WhatsApp Business API adoption growing.',
      },
      {
        name: 'SMS',
        icon: '📱',
        penetration: 97,
        businessUse: 'high',
        costLevel: 'low',
        apiAvailable: true,
        notes: 'Highest reach. Africa\'s Talking is the leading API provider.',
      },
      {
        name: 'M-Pesa/STK Push',
        icon: '💰',
        penetration: 75,
        businessUse: 'high',
        costLevel: 'medium',
        apiAvailable: true,
        notes: 'Unique to Kenya. Payment + messaging integration via Safaricom.',
      },
      {
        name: 'Facebook Messenger',
        icon: '💭',
        penetration: 30,
        businessUse: 'medium',
        costLevel: 'free',
        apiAvailable: true,
        notes: 'Moderate adoption. Used for customer service.',
      },
      {
        name: 'Instagram',
        icon: '📸',
        penetration: 18,
        businessUse: 'medium',
        costLevel: 'low',
        apiAvailable: true,
        notes: 'Growing in Nairobi. Strong for lifestyle and hospitality.',
      },
      {
        name: 'Telegram',
        icon: '✈️',
        penetration: 20,
        businessUse: 'medium',
        costLevel: 'free',
        apiAvailable: true,
        notes: 'Popular for news channels and community groups.',
      },
      {
        name: 'Email',
        icon: '📧',
        penetration: 40,
        businessUse: 'medium',
        costLevel: 'low',
        apiAvailable: true,
        notes: 'Growing B2B adoption. Data protection act compliance needed.',
      },
      {
        name: 'USSD',
        icon: '📞',
        penetration: 88,
        businessUse: 'high',
        costLevel: 'high',
        apiAvailable: true,
        notes: 'Critical for M-Pesa and banking. Universal phone compatibility.',
      },
      {
        name: 'Twitter/X',
        icon: '🐦',
        penetration: 14,
        businessUse: 'medium',
        costLevel: 'free',
        apiAvailable: true,
        notes: 'Active tech and media community. #KOT (Kenyans on Twitter) is influential.',
      },
      {
        name: 'TikTok',
        icon: '🎵',
        penetration: 25,
        businessUse: 'low',
        costLevel: 'low',
        apiAvailable: false,
        notes: 'Rapidly growing. Strong entertainment and lifestyle content.',
      },
    ],
  },
];

/**
 * Get channels for a specific country by code.
 */
export function getCountryChannels(countryCode: string): CountryChannels | undefined {
  return CHANNEL_MATRIX.find(
    (c) => c.code.toUpperCase() === countryCode.toUpperCase(),
  );
}

/**
 * Get recommended channels for a country.
 * Recommended = high business use + penetration >= 40% + API available.
 */
export function getRecommendedChannels(countryCode: string): ChannelInfo[] {
  const country = getCountryChannels(countryCode);
  if (!country) return [];

  return country.channels.filter(
    (ch) =>
      ch.businessUse === 'high' &&
      ch.penetration >= 40 &&
      ch.apiAvailable,
  );
}
