import type { StrategySessionDocument, StrategySessionAgenda } from '@/types/packages'

// ---------- Helper ----------
function formatNaira(amount: number): string {
  return new Intl.NumberFormat('en-NG', {
    style: 'currency',
    currency: 'NGN',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount)
}

function today(): string {
  return new Date().toLocaleDateString('en-NG', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })
}

// ---------- Interfaces for template data ----------
export interface AccountContext {
  accountName: string
  industry?: string
  contactCount?: number
  conversationCount?: number
  campaignCount?: number
  reactivationRate?: number
  satisfactionScore?: number
  revenueRecovered?: number
  whatsappConnected?: boolean
  currentPackage?: string
  startDate?: string
}

// ---------- Pre-Session Documents ----------

export function generatePerformanceSummary(ctx: AccountContext): StrategySessionDocument {
  const content = `# Client Performance Summary

**Client:** ${ctx.accountName}
**Date:** ${today()}
**Current Package:** ${ctx.currentPackage ?? 'Not assigned'}

---

## Key Metrics Overview

| Metric | Value |
|--------|-------|
| Total Contacts | ${ctx.contactCount?.toLocaleString() ?? 'N/A'} |
| Total Conversations | ${ctx.conversationCount?.toLocaleString() ?? 'N/A'} |
| Active Campaigns | ${ctx.campaignCount ?? 'N/A'} |
| Reactivation Rate | ${ctx.reactivationRate != null ? (ctx.reactivationRate * 100).toFixed(1) + '%' : 'N/A'} |
| Satisfaction Score | ${ctx.satisfactionScore?.toFixed(1) ?? 'N/A'} / 5.0 |
| Revenue Recovered | ${ctx.revenueRecovered != null ? formatNaira(ctx.revenueRecovered) : 'N/A'} |
| WhatsApp Connected | ${ctx.whatsappConnected ? 'Yes ✅' : 'No ❌'} |

## Performance Assessment

### Strengths
- ${ctx.contactCount && ctx.contactCount > 500 ? 'Strong contact database foundation' : 'Growing contact base'}
- ${ctx.whatsappConnected ? 'WhatsApp channel active and connected' : 'WhatsApp setup pending'}
- ${ctx.campaignCount && ctx.campaignCount > 3 ? 'Multiple campaigns running' : 'Campaign setup in progress'}

### Areas for Improvement
- ${ctx.reactivationRate != null && ctx.reactivationRate < 0.15 ? 'Reactivation rate below 15% target' : 'Maintain reactivation momentum'}
- ${ctx.satisfactionScore != null && ctx.satisfactionScore < 3.5 ? 'Satisfaction score needs attention' : 'Continue satisfaction monitoring'}

### Recommendations
1. ${ctx.reactivationRate != null && ctx.reactivationRate < 0.10 ? 'Intensify win-back campaign messaging' : 'Scale successful reactivation patterns'}
2. ${ctx.contactCount != null && ctx.contactCount < 200 ? 'Prioritise contact database growth' : 'Focus on contact quality and segmentation'}
3. Review campaign performance weekly and adjust messaging

---
*Generated by M4E Package Execution System*
`

  return {
    type: 'performance_summary',
    title: `Performance Summary - ${ctx.accountName}`,
    content,
    generated_at: new Date().toISOString(),
  }
}

export function generateMarketOpportunity(ctx: AccountContext): StrategySessionDocument {
  const content = `# Market Opportunity Analysis

**Client:** ${ctx.accountName}
**Industry:** ${ctx.industry ?? 'General'}
**Date:** ${today()}

---

## Industry Landscape

The ${ctx.industry ?? 'Nigerian mid-market'} sector presents significant opportunities for digital customer engagement. Key trends include:

1. **WhatsApp Dominance**: 93% of Nigerian internet users actively use WhatsApp for business communication
2. **Mobile-First Economy**: 85%+ of digital interactions happen on mobile devices
3. **Trust-Based Commerce**: Personal relationships and direct communication drive purchasing decisions
4. **Growing Digital Adoption**: Post-COVID acceleration of digital business tools

## Competitive Analysis

### Current Market Position
- **Database Size**: ${ctx.contactCount?.toLocaleString() ?? 'Unknown'} contacts
- **Engagement Level**: ${ctx.conversationCount?.toLocaleString() ?? 'Unknown'} conversations
- **Digital Maturity**: ${ctx.whatsappConnected ? 'Connected' : 'Pre-connection'}

### Opportunity Areas
1. **Customer Reactivation**: Dormant customers represent untapped revenue
2. **Automated Engagement**: Reduce manual follow-up with smart automations
3. **Data-Driven Decisions**: Use campaign analytics to optimise messaging
4. **Multi-Channel Presence**: Extend beyond WhatsApp to web and social

## Revenue Potential

| Scenario | Estimated Monthly Impact |
|----------|-------------------------|
| Conservative (10% reactivation) | ${formatNaira((ctx.contactCount ?? 100) * 0.1 * 5000)} |
| Moderate (20% reactivation) | ${formatNaira((ctx.contactCount ?? 100) * 0.2 * 5000)} |
| Aggressive (30% reactivation) | ${formatNaira((ctx.contactCount ?? 100) * 0.3 * 5000)} |

*Based on average transaction value of ${formatNaira(5000)} per reactivated customer*

---
*Generated by M4E Package Execution System*
`

  return {
    type: 'market_opportunity',
    title: `Market Opportunity - ${ctx.accountName}`,
    content,
    generated_at: new Date().toISOString(),
  }
}

export function generateAudienceIntelligence(ctx: AccountContext): StrategySessionDocument {
  const content = `# Audience Intelligence Brief

**Client:** ${ctx.accountName}
**Date:** ${today()}

---

## Database Overview

- **Total Contacts**: ${ctx.contactCount?.toLocaleString() ?? 'N/A'}
- **Active Conversations**: ${ctx.conversationCount?.toLocaleString() ?? 'N/A'}
- **Engagement Rate**: ${ctx.contactCount && ctx.conversationCount ? ((ctx.conversationCount / ctx.contactCount) * 100).toFixed(1) + '%' : 'N/A'}

## Segmentation Recommendations

### By Recency (RFM)
1. **Champions** (Recent, Frequent, High Value) - VIP treatment, referral programme
2. **Loyal Customers** (Frequent) - Upsell opportunities, birthday campaigns
3. **At Risk** (Previously active, now dormant) - Win-back campaigns
4. **Lost** (Long dormant) - Re-engagement with special offers

### By Engagement Level
1. **Highly Engaged**: Responded to 3+ campaigns - nurture for referrals
2. **Moderately Engaged**: Responded to 1-2 campaigns - increase touchpoints
3. **Low Engagement**: No responses - test different messaging angles
4. **Unengaged**: No opens - verify contact validity, try different channels

## Messaging Recommendations

### Tone & Style
- Use conversational Nigerian English
- Include personalisation (first name, last purchase)
- Keep messages concise (under 160 words for WhatsApp)
- Include clear call-to-action

### Timing
- **Best Days**: Tuesday, Wednesday, Thursday
- **Best Times**: 9-11 AM, 2-4 PM (WAT)
- **Avoid**: Late evenings, weekends (unless retail)

---
*Generated by M4E Package Execution System*
`

  return {
    type: 'audience_intelligence',
    title: `Audience Intelligence - ${ctx.accountName}`,
    content,
    generated_at: new Date().toISOString(),
  }
}

export function generateBudgetModelling(ctx: AccountContext): StrategySessionDocument {
  const content = `# Budget Modelling

**Client:** ${ctx.accountName}
**Date:** ${today()}

---

## Current Investment

| Item | Monthly Cost |
|------|-------------|
| CRM Platform | Included in package |
| WhatsApp Business API | ${formatNaira(15000)} (estimated) |
| Message Costs | Variable based on volume |

## Package Options

### Package 1: Customer Reactivation - ${formatNaira(2000000)}
- 8-week programme
- 6 campaign types
- 4 automation types
- Monthly reporting
- Retainer from ${formatNaira(150000)}/month

### Package 2: Online Presence - ${formatNaira(3500000)}
- 8-week programme
- Website + brand identity
- Lead nurture campaigns
- Monthly reporting
- Retainer from ${formatNaira(150000)}/month

### Package 3: Growth Engine - ${formatNaira(5000000)}
- 12-week programme
- Paid advertising
- E-commerce integrations
- Weekly reporting
- Retainer from ${formatNaira(350000)}/month

### Complete Programme - ${formatNaira(9000000)}
- All three packages combined
- 16-week programme
- Weekly reporting
- Scale retainer at ${formatNaira(750000)}/month

## ROI Projections

| Metric | Conservative | Moderate | Optimistic |
|--------|-------------|----------|------------|
| Reactivation Rate | 10% | 20% | 30% |
| Revenue per Customer | ${formatNaira(5000)} | ${formatNaira(8000)} | ${formatNaira(12000)} |
| Monthly Revenue Lift | ${formatNaira((ctx.contactCount ?? 100) * 0.1 * 5000)} | ${formatNaira((ctx.contactCount ?? 100) * 0.2 * 8000)} | ${formatNaira((ctx.contactCount ?? 100) * 0.3 * 12000)} |
| Payback Period | 4-6 months | 2-3 months | 1-2 months |

---
*Generated by M4E Package Execution System*
`

  return {
    type: 'budget_modelling',
    title: `Budget Modelling - ${ctx.accountName}`,
    content,
    generated_at: new Date().toISOString(),
  }
}

// ---------- Post-Session Documents ----------

export function generateSessionSummary(
  ctx: AccountContext,
  notes: string
): StrategySessionDocument {
  const content = `# Strategy Session Summary

**Client:** ${ctx.accountName}
**Date:** ${today()}
**Package:** ${ctx.currentPackage ?? 'To be determined'}

---

## Session Notes

${notes || '*No notes recorded*'}

## Action Items

- [ ] Finalise package selection
- [ ] Schedule onboarding call
- [ ] Prepare data collection requirements
- [ ] Set up WhatsApp Business API (if not connected)
- [ ] Define success metrics and KPIs

## Next Steps

1. **Week 1**: Client onboarding and data collection
2. **Week 2**: Campaign configuration and approval
3. **Week 3**: Campaign activation
4. **Ongoing**: Weekly/monthly reporting and optimisation

---
*Generated by M4E Package Execution System*
`

  return {
    type: 'session_summary',
    title: `Session Summary - ${ctx.accountName}`,
    content,
    generated_at: new Date().toISOString(),
  }
}

export function generateCampaignArchitecture(ctx: AccountContext): StrategySessionDocument {
  const content = `# Campaign Architecture

**Client:** ${ctx.accountName}
**Date:** ${today()}

---

## Campaign Stack

### Phase 1: Foundation (Weeks 1-3)
1. **Win-Back Campaign** - Re-engage dormant customers with personalised offers
2. **Satisfaction Screening** - Gate reviews behind satisfaction check
3. **Welcome Message** - Automated greeting for new/returning contacts

### Phase 2: Engagement (Weeks 4-6)
4. **Birthday Campaign** - Automated birthday greetings with offers
5. **VIP Loyalty** - Reward top customers with exclusive benefits
6. **Post-Purchase Follow-up** - Automated check-in after transactions

### Phase 3: Growth (Weeks 7-8)
7. **Referral Programme** - Incentivise word-of-mouth
8. **Review Collection** - Satisfaction-gated review requests

## Automation Triggers

| Trigger | Action | Timing |
|---------|--------|--------|
| New contact added | Welcome message | Immediate |
| No activity 30 days | Win-back message | Day 30 |
| Purchase completed | Follow-up message | Day 3 |
| Birthday detected | Birthday greeting | Day of |
| Satisfaction >= 4 | Review request | Day 7 |
| Review submitted | Referral request | Day 14 |

## Message Templates

All templates will be drafted in conversational Nigerian English with:
- Personalisation tokens (first name, last purchase)
- Clear call-to-action
- Opt-out option
- Brand voice consistency

---
*Generated by M4E Package Execution System*
`

  return {
    type: 'campaign_architecture',
    title: `Campaign Architecture - ${ctx.accountName}`,
    content,
    generated_at: new Date().toISOString(),
  }
}

export function generateCreativeBrief(ctx: AccountContext): StrategySessionDocument {
  const content = `# Creative Brief

**Client:** ${ctx.accountName}
**Industry:** ${ctx.industry ?? 'General'}
**Date:** ${today()}

---

## Brand Voice

- **Tone**: Professional yet warm, conversational Nigerian English
- **Personality**: Helpful, knowledgeable, trustworthy
- **Avoid**: Overly formal language, jargon, aggressive sales tactics

## Messaging Framework

### Win-Back Messages
- **Hook**: Reference past relationship/purchase
- **Value**: Exclusive returning customer offer
- **CTA**: Simple reply or link

### Satisfaction Messages
- **Hook**: "How was your experience?"
- **Scale**: 1-5 rating
- **Follow-up**: Route based on score

### Referral Messages
- **Hook**: "Know someone who'd love this?"
- **Incentive**: Reward for both referrer and referee
- **CTA**: Share link or contact

## Visual Guidelines

- Use client's brand colours where possible
- Keep images simple and mobile-optimised
- Include logo on all branded materials
- WhatsApp-friendly formats (JPEG, PNG under 5MB)

## Approval Process

1. Draft messages created by M4E team
2. Client reviews and provides feedback
3. Revisions implemented
4. Final approval before activation
5. A/B testing on initial sends

---
*Generated by M4E Package Execution System*
`

  return {
    type: 'creative_brief',
    title: `Creative Brief - ${ctx.accountName}`,
    content,
    generated_at: new Date().toISOString(),
  }
}

export function generateTwelveWeekCalendar(ctx: AccountContext): StrategySessionDocument {
  const weekPlan: { week: number; focus: string; tasks: string }[] = [
    { week: 1, focus: 'Onboarding & Setup', tasks: 'Onboarding call, data source identification, access setup' },
    { week: 2, focus: 'Data Collection', tasks: 'Contact import, deduplication, RFM segmentation' },
    { week: 3, focus: 'Campaign Config', tasks: 'Draft messages, configure campaigns, get approval' },
    { week: 4, focus: 'Campaign Launch', tasks: 'Activate win-back, satisfaction screening' },
    { week: 5, focus: 'Response Analysis', tasks: 'Analyse responses, adjust messaging, first report' },
    { week: 6, focus: 'Lifecycle Campaigns', tasks: 'Birthday, VIP loyalty campaigns' },
    { week: 7, focus: 'Referral & Reviews', tasks: 'Launch referral programme, collect reviews' },
    { week: 8, focus: 'Mid-Point Review', tasks: 'Comprehensive report, strategy adjustment' },
    { week: 9, focus: 'Advanced Campaigns', tasks: 'Cross-sell, upsell, catalog campaigns' },
    { week: 10, focus: 'Optimisation', tasks: 'Full funnel optimisation, A/B testing' },
    { week: 11, focus: 'Automation & Scale', tasks: 'Automate winning campaigns, scaling plan' },
    { week: 12, focus: 'Final Report', tasks: 'Comprehensive report, transition recommendation' },
  ]

  const weekRows = weekPlan
    .map((w) => `| Week ${w.week} | ${w.focus} | ${w.tasks} |`)
    .join('\n')

  const content = `# 12-Week Execution Calendar

**Client:** ${ctx.accountName}
**Start Date:** ${ctx.startDate ?? 'TBD'}
**Date:** ${today()}

---

## Weekly Plan

| Week | Focus | Key Tasks |
|------|-------|-----------|
${weekRows}

## Key Milestones

- **Week 4**: First campaign messages sent
- **Week 5**: First performance report
- **Week 8**: Mid-point comprehensive review
- **Week 12**: Final report and transition recommendation

## Reporting Schedule

- **Weekly**: Quick status update (email/WhatsApp)
- **Bi-weekly**: Performance dashboard review
- **Monthly**: Comprehensive report with recommendations
- **End of Programme**: Final report with transition plan

## Communication Cadence

- **Monday**: Weekly planning and priority setting
- **Wednesday**: Mid-week check-in (if needed)
- **Friday**: Weekly summary and next week preview

---
*Generated by M4E Package Execution System*
`

  return {
    type: 'twelve_week_calendar',
    title: `12-Week Calendar - ${ctx.accountName}`,
    content,
    generated_at: new Date().toISOString(),
  }
}

// ---------- Strategy Session Agenda ----------

export function generateDefaultAgenda(): StrategySessionAgenda {
  return {
    sections: [
      {
        time: '0:00 - 0:30',
        title: 'Welcome & Context Setting',
        description: 'Introductions, review performance summary, set session objectives',
      },
      {
        time: '0:30 - 1:00',
        title: 'Market Opportunity Review',
        description: 'Industry landscape, competitive positioning, growth opportunities',
      },
      {
        time: '1:00 - 1:30',
        title: 'Audience Intelligence Deep Dive',
        description: 'Customer segmentation, messaging strategy, channel preferences',
      },
      {
        time: '1:30 - 1:45',
        title: 'Break',
        description: 'Refreshments and informal discussion',
      },
      {
        time: '1:45 - 2:15',
        title: 'Campaign Architecture',
        description: 'Campaign stack design, automation triggers, message templates',
      },
      {
        time: '2:15 - 2:45',
        title: 'Budget & ROI Modelling',
        description: 'Investment options, ROI projections, package selection',
      },
      {
        time: '2:45 - 3:00',
        title: 'Next Steps & Close',
        description: 'Action items, timeline, onboarding scheduling',
      },
    ],
  }
}
